### ISSUE TITLE
Add tolerance matcher for doubles/floats

### ISSUE THREAD

**Issue by sksamuel** [kotlintest/kotlintest#10]

**Comment by russel** [comment]
Some notion of "almost equal" is needed for doubles and floats (and BigDecimal?) and perhaps should be the default for all non-integral value testing?

a == b or assertEqual(a, b) is a big problem where a and b are floating point, and yet far too few programmers actually appreciate this.

**Comment by sksamuel** [comment]
Yep. I've added a shouldBe b within c

**Comment by sksamuel** [comment]
Maybe i could emit a warn if you test doubles or floats without a tolerance.

**Comment by russel** [comment]
Issuing a warning on detection of use of == or assertEqual or similar would be a huge USP for a testing framework!

**Comment by sksamuel** [comment]
Agreed.
