### ISSUE TITLE
Rename TestBase to Spec

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#102]
Since `TestBase` is the base class for all `Spec`s, it could be called `Spec`. This would make the places where this class is used more comprehensive. I'm using this class for example for the spec interceptors:

```kotlin
protected val  interceptors: Iterable<(TestBase, () -> Unit) -> Unit>
```

Where `TestBase` is the context for the interceptor. I think it would be more clear, if it would be called `Spec`:

```kotlin
protected val  interceptors: Iterable<(Spec, () -> Unit) -> Unit>
```

Another reason to rename this class, is that this class is not the base for test cases (aka tests).

What do you think?

Btw: I was called "the renamer" in a former project ;-)

**Comment by sksamuel** [comment]
I can see why they gave you that name.

Yep this seems a good thing.

**Comment by helmbold** [comment]
Renamed.
