### ISSUE TITLE
Remove config parameter `tag` (singular)

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#105]
As discussed in #77 I consider the `tag` parameter of the `config` method somewhat inconsistent. It is not clear what happens if you

* have `tag` and `tags`
* have already defined `tag` or `tags` in the `defaultTestCaseConfig`

In the first case it is not obvious, whether the tags are merged or not (actually it doesn't make sense to provide `tag` and `tags`).

In the second case it would be consistent to rest of the config behavior to override tags from `defaultTestCaseConfig`, but at the moment tags are merged. It gets even more confusing if you mix `tag` and `tags` (or vice versa) in the `defaultTestCaseConfig` and test case config.

Since it is not that hard to write `listOf(myTag)`, I suggest to simply remove `tag` (singular) from `config` method.

**Comment by sksamuel** [comment]
Agreed.

**Comment by helmbold** [comment]
Done.
