### ISSUE TITLE
Pass list of test cases to spec interceptors

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#106]
As suggested in [#77](https://github.com/kotlintest/kotlintest/issues/77#issuecomment-253048343) a list of all test cases of the spec should be passed to spec interceptors and the `interceptSpec` method. We should probably create a `SpecContext` to do so (analogous to `TestCaseContext`).

This issue is blocked by #51 "Running all tests in parallel" because otherwise it would probably require some changes.

**Comment by sksamuel** [comment]
What did we decide to do about this in the end?

**Comment by helmbold** [comment]
Since we have pushed #51 to 3.0, we can now only implement something that needs a refactoring in 3.0. But I think, it would be better to provide a list of test case now (and refactor later) instead of pushing this feature to 3.0, too. What do you think?

**Comment by sksamuel** [comment]
Ok agreed.

**Comment by helmbold** [comment]
Since spec interceptors already get a reference to the spec as the context, I've just added a property `testCases` to the `Spec` class. Do you agree with this solution, @sksamuel ?
