### ISSUE TITLE
Support "should..." operators with property-based testing

### ISSUE THREAD

**Issue by brescia123** [kotlintest/kotlintest#108]
All the functions used to do property-based testing (forAll, forNone) accept as last parameters a function that should returns a Boolean to indicate whether the test passes or not. 
In order to use shouldBe and similar operators you have to always return true within the mentioned above function.
It think there should be a better way to do that, maybe modifying the function to not require a Boolean as return type.

**Comment by sksamuel** [comment]
I guess the idea was that for property based testing you don't have to use an assertion, you just use a boolean function, ie, its testing a property/function. It could be changed to use an assertion, which will make things a touch more verbose.

current:

```kotlin
    "startsWith" {
      forAll(Gen.string(), Gen.string(), { a, b ->
        (a + b).startsWith(a)
      })
    }
```

alternative:

```kotlin
    "startsWith" {
      forAll(Gen.string(), Gen.string(), { a, b ->
        (a + b).startsWith(a) shouldBe true
      })
    }
```

What do you think @helmbold @brescia123

**Comment by brescia123** [comment]
Unfortunately I'm not a property based testing expert, but I think you could simply use other matchers, like this: 
```kotlin
"startsWith" {
  forAll(Gen.string(), Gen.string(), { a, b ->
    (a + b) should startWith(a)
  })
}
```

**Comment by sksamuel** [comment]
Yes ok that's a bad example :) What I was trying to show was that for ones where there is no matcher, you're forced to do shouldBe true after the predicate.

That's not a huge deal, but would rather we could keep it backwards compat.

**Comment by brescia123** [comment]
I've looked more into property based testing and now I think that in the first place you were right saying that 
> the idea was that for property based testing you don't have to use an assertion 
So I'm closing the issue.

**Comment by sksamuel** [comment]
I was thinking we could introduce an analog of property testing but for regular shouldbe matchers. It's easy to do and we can just give it another name. GeneratorTesting or something? @helmbold likes to do the naming :)

**Comment by sksamuel** [comment]
This is added in 3.0.0 RC1. They are called assertAll and assertNone.
If you have the time, please give it a try. There are some breaking changes that should be aware of by reading the changelog here: https://github.com/kotlintest/kotlintest/blob/master/CHANGELOG.md
