### ISSUE TITLE
Run some code before all tests and after all tests

### ISSUE THREAD

**Issue by michaelsproul** [kotlintest/kotlintest#110]
It seems currently as if there's no way to run initialisation/tear-down code either side of multiple test classes (`beforeAll` takes care of initialisation only for a single test class).

**Comment by sksamuel** [comment]
Coming very soon in 2.0 :)

**Comment by helmbold** [comment]
I'm glad to hear that you miss the feature, I've just implemented ;-) Please see #77

**Comment by michaelsproul** [comment]
@helmbold: Nice!
