### ISSUE TITLE
shouldEqual defines equality differently than kotlin

### ISSUE THREAD

**Issue by SilverFishCat** [kotlintest/kotlintest#111]
According to [the kotlin reference](https://kotlinlang.org/docs/reference/operator-overloading.html) the equality operator `==` is translated to `a?.equals(b) ?: b === null`. (`!=` is similarly defined)
Additionally, `equals` receives a nullable parameter.

The `shouldBe` (and `shouldEqual`) functions are defined as 

```
if (this == null && any != null)
  throw AssertionError(this.toString() + " did not equal $any")
if (this != null && any == null)
  throw AssertionError(this.toString() + " did not equal $any")
if (this != any)
  throw AssertionError(this.toString() + " did not equal $any")
```

This means that if `a == null` returns `true` (whether by design or by mistake), `a shouldBe null` will still throw. Checking `this == null` is also not needed. 
This is also in contrast to the new `equalityMatcher`, which only checks `this == value`.

**Comment by SilverFishCat** [comment]
There maybe there should be a way to check for [Referential equality](https://kotlinlang.org/docs/reference/equality.html#referential-equality).

**Comment by sksamuel** [comment]
Is this the case you're referring to or am I missing something subtle? https://github.com/kotlintest/kotlintest/blob/master/src/test/kotlin/io/kotlintest/NullTests.kt#L20

**Comment by SilverFishCat** [comment]
No, it's referring to https://github.com/kotlintest/kotlintest/blob/master/src/test/kotlin/io/kotlintest/NullTests.kt#L29

Actually, after doing some tests I have noticed a weird and inconsistent behavior in kotlin:
```kotlin
class A(var i: Int) {
  override fun equals(other: Any?): Boolean = other == null && i==0
}

var g:A? = null
println(A(0) == g) // true
println(A(0) == null) //false
```

This might be an issue in the kotlin compiler. I'm going to open an issue with JetBrains and will update this issue once they fix it/create a consistent definition for the `==` operator.
Regardless, the expected behavior in my opinion is ```println(A(0) == g) // true``` (it fits with the kotlin reference and the code behind the `==` operator). `A(0) shouldBe(g)` will still throw an AssertionError.

**Comment by sksamuel** [comment]
Did you get anywhere with raising this with Jetbrains?

**Comment by aleixmorgadas** [comment]
Resolving the inconsistent behavior.
`A(0) == null ` uses the equality of null which resolves the operation returning `false`
`A(0) == g) uses the `A.equals` method

**Comment by aleixmorgadas** [comment]
For future readings.

> The == operation is special: it is translated to a complex expression that screens for null's. null == null is always true, and x == null for a non-null x is always false and won't invoke x.equals().

[official documentation reference](https://kotlinlang.org/docs/reference/operator-overloading.html)
