### ISSUE TITLE
RxJava Sample

### ISSUE THREAD

**Issue by jmfayard** [kotlintest/kotlintest#118]
Hello, I made a little but pretty neat wrapper around `FeatureSpec` that allows to test rxjava Observable (and as such networking or pretty much everything). 

Would you be interesting if I contribute it as a sample project?

![image](https://cloud.githubusercontent.com/assets/459464/20557264/17040652-b16b-11e6-9f22-7f6920349416.png)

**Comment by helmbold** [comment]
Very nice! 

I'm just thinking about how we could handle such contributions. What do you think about adding a section to the documentation where we can collect links and descriptions of such sample projects?

**Comment by jmfayard** [comment]
I was thinking about a simple `samples/rxjava` directory inside the repository :)
