### ISSUE TITLE
Minimize visibility

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#120]
The visibility of all kinds of artifacts (classes, interfaces, properties ...) should be minimized, to avoid breaking changes through later refactorings (and to improve the internal quality as well).

**Comment by sksamuel** [comment]
Are you still planning on this for 2.0? I think we can release 2.0 as soon as Kotlin 1.1 comes out.

**Comment by helmbold** [comment]
I had some pressing things to do in the meantime, but, yes, I will do it in the next days!
