### ISSUE TITLE
Renaming proposal

### ISSUE THREAD

**Issue by elect86** [kotlintest/kotlintest#128]
I am writing test for a lib that offers unsigned support

    250.b udiv 50.b shouldBe 5.b
    250.b ucmp 251.b should be lt 1

I still find that too much verbose, I'd love to have

    250.b udiv 50.b is_ 5.b
    250.b ucmp 251.b isLt 1

or 

    250.b ucmp 251.b lessThan 1

**Comment by sksamuel** [comment]
I like the latter. I'd have to change matchers slightly to accommodate this kind of syntax. @helmbold what do you think to allowing new syntax.

**Comment by elect86** [comment]
Also

                val a = Vec2(1f)
                val b = Vec2(1f)

                a shouldBe  b
                (a != b) shouldBe true

Would be nice to have

    a isNot b

**Comment by helmbold** [comment]
I don't like the suggested style. It is not very readable and would introduce inconsistency. I wouldn't introduce it as part of KotlinTest, but it could be a good way to encourage others to create alternative assertions libraries that we could refer to.

**Comment by sksamuel** [comment]
I think 'isNot' is very readable, actually much better than should not be or whatever. The `isLt` I agree with, you could end up making all kinds of shortcuts, but a short cut for `not` is quite important IMO.

**Comment by hastebrot** [comment]
I thought this `should` stuff is somehow related to behaviour driven testing/development.
