### ISSUE TITLE
Kotlintest Support for SBT 

### ISSUE THREAD

**Issue by greatdreams** [kotlintest/kotlintest#129]
Now, I'm trying developing kotlin with set. I want to use kotlintest for test. However, I find that it doesn't work. 

The following is my code snippet

src/test/kotlin/test/MyTest1.kt
```kotlin
package test

import io.kotlintest.specs.FlatSpec
import io.kotlintest.specs.StringSpec

class MyTest1: StringSpec() {
	init {
		"strings.length should return the size of string" {
			"Hello".length shouldBe 5
	       }
        }
}

class MyTest2: FlatSpec() {
	init {
		"String.length" should  "return the length of the string" {
			"sammy".length shouldBe 5
			"".length shouldBe 1
		}
	}
}
```
Now, I run the test 
```bash
$sbt "testOnly test.Mytest1"
```
[info] No tests to run for test:testOnly

**Comment by sksamuel** [comment]
You're using sbt for kotlin ?

**Comment by greatdreams** [comment]
Yeah, use this plugin [https://github.com/pfn/kotlin-plugin](https://github.com/pfn/kotlin-plugin)

**Comment by sksamuel** [comment]
Wow cool.

**Comment by sksamuel** [comment]
I wonder if this is the cause? https://github.com/pfn/kotlin-plugin#limitations

**Comment by greatdreams** [comment]
I've read the limitation of the plugin ,especially, "testOnly <test-class> may be able to test individual classes/suites in place of test." Maybe, it's the cause. I've tried some times, but it does not work. I want to know better for the cause and make it work finally.
