### ISSUE TITLE
Mark tests as ignored

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#13]
It would be useful to be able to mark test as ignored. Something like [`@Ignore`](http://junit.sourceforge.net/javadoc/org/junit/Ignore.html) from JUnit, but not necessarily an annotation.

**Comment by sksamuel** [comment]
I never really liked the way ignore worked in scalatest. I thought an
annotation was clearer or perhaps another enclosing block.

**Comment by helmbold** [comment]
I'm not a fan of deeply nested blocks, but in the case of ignoring tests it could be useful, because several tests could be ignored with one block. However to ignore a single test a single word (annotation or not) without a block would be more convenient. I'm not sure about this.

**Comment by sksamuel** [comment]
Has become part of #14
