### ISSUE TITLE
Remove Spec.config function

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#130]
The `config` function in class `Spec` is a factory method that repeats only the TestCaseConfig constructor. The idea behind this function was to provide the same notation for spec wide test case config as for per test case config. However I'm uncertain whether we should keep this method, because it repeats the constructor and creation of the default test case config is slightly different from the per test case config.

What do you think? Keep or remove?

**Comment by sksamuel** [comment]
I don't have a strong opinion either way so I will let you decide.

**Comment by helmbold** [comment]
Following the KISS principle, the method is removed now.
