### ISSUE TITLE
Reorder members

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#131]
Classes are more readable if their elements are ordered by visibility (public first, then internal, then protected, and last private).

At least with Java IntelliJ can do the job.

**Comment by sksamuel** [comment]
I don't personally care, as I use the structure view in intellij (view 7) which will order by visibility anyway if you want it to. But if you want to change them around be my guest :)

**Comment by helmbold** [comment]
Most members were already ordered properly. In some cases it was not possible to get the desired order because of dependencies between members. So, you were right not to care ;-)
