### ISSUE TITLE
Create public beta release

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#133]
If all tasks for version 2.0 are done, we should create a beta release to get some user feedback.

**Comment by sksamuel** [comment]
Let's aim to get this out by Monday?

**Comment by helmbold** [comment]
Ok, let's target monday. It should be possible.

**Comment by helmbold** [comment]
We should check our change log then.

**Comment by sksamuel** [comment]
We do really need to release 2.0 now 1.1 has been released. I will make sure the matcher changes I want to make are completed as soon as I can, as I really want that in 2.0, because then I can start to add loads of custom ones. As for you, what do you really want to get shipped in version 2 and what can be bumped?

**Comment by helmbold** [comment]
We should fix the open bugs (#148, #142, #111), and we should implement #144, #138, and #41, because these tickets would probably cause breaking API changes after 2.0.

**Comment by aleixmorgadas** [comment]
#148 (PR already merged) and #111 (PR open) have been fixed. 

#111 comes with Jacoco and code coverage report, but some configuration is still needed. I think that it will be good for the project know the percent of code under test.

I view necessary, as you, implement those issues before 2.0 is released. I hope that I could help in everything I can

**Comment by sksamuel** [comment]
#41 I think we can bump, because configuration shouldn't break what we have, just will be an extra method on top.

#138 I will definitely finish in days. And then I need to look at #142 unless @aleixmorgadas wants to help.

**Comment by aleixmorgadas** [comment]
Hi,
Which is the current status? I've made some pull request (already merged) to close some issues but they are still open, should I wait until the issues reflects the actual status?

**Comment by sksamuel** [comment]
I've voted to close #138. I'm looking at #142 now.

**Comment by sksamuel** [comment]
#142 should be good now. I'm happy to release 2.0 once it's merged in. It's been a long time coming and I think we need to get it out there. Even spek is starting to improve now :)

**Comment by sksamuel** [comment]
Closing this as we will be releasing 2.0 this weekend.
