### ISSUE TITLE
Retrieve the string within the lambda expression

### ISSUE THREAD

**Issue by elect86** [kotlintest/kotlintest#137]
I'd like a simple way to retrieve the string within the lambda
```

class stl : StringSpec() {

    init {

        "triangle.stl" {
             ...
        }
    }
}
```

In this case `"triangle.stl"`

**Comment by helmbold** [comment]
May I ask why do want the test case name to be passed as a parameter? I felt never the need in all the years of programming.

**Comment by elect86** [comment]
Because it is also the name of the file I am trying to read

**Comment by helmbold** [comment]
But is the file name in your case actually a useful test case name? There is of corse not the one true style to write tests, but at least I prefer having a descriptive name like "should parse invalid csv file". Why don't you use a name like this and the file name as a usual variable inside the test? An alternative could be to use table driven testing, where you'd get the file names as input parameters.

I want to understand your use case to come to be able to asses your feature request.

**Comment by elect86** [comment]
Yes, I am testing several meshes, that's the name of the i-th file

[This](https://github.com/java-graphics/assimp/blob/master/src/test/kotlin/obj.kt) is what I came up with so far, I am open to any suggestions

**Comment by helmbold** [comment]
As far as I understand your code, you could replace the test cases with table driven tests, since the test logic seems to be always the same but with different values. Table driven testing would be more elegant and would reduce the amount of code significantly in you case.

**Comment by helmbold** [comment]
I suggest to close this issue, since I consider it generally not useful to get the test case name passed as parameter. What do you think @sksamuel ?

**Comment by elect86** [comment]
I have no problems closing it, however I think the table driven tests will not fit my case, or at least for the moment.

The main problem is that I have only specific fields to check about, and they are hardly the same between a mesh and another one

**Comment by helmbold** [comment]
You could create a table where some values are null or you could use some kind of container objects (aka data classes) inside the table.

**Comment by elect86** [comment]
I would need a ternary status, sometimes I have to check against null values..

However, if it's just me, we can close without problems ;)
