### ISSUE TITLE
kotlintest does not work with 1.1-beta

### ISSUE THREAD

**Issue by elect86** [kotlintest/kotlintest#143]
Whenever I try to run the tests:

```
e: Some runtime JAR files in the classpath have an incompatible version. Remove them from the classpath or pass the correct '-language-version' explicitly. Alternatively, you can use '-Xskip-runtime-version-check' to suppress this error
e: C:\Users\GBarbieri\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-reflect\1.0.4\ab1d288da47c0d798553ccea9d8b4fd6a0e3b8e4\kotlin-reflect-1.0.4.jar: Runtime JAR file has version 1.0 which is older than required for language version 1.1
```

JetBrain also suggest it:

> Seems that you're getting `kotlin-reflect:1.0.4` as a transitive dependency of one of your dependencies, and since it would cause problems when used with `kotlin-stdlib:1.1`, the compiler prohibits such dependency graph.

Would it be possible to have a build/release based on 1.1?

**Comment by sksamuel** [comment]
I'll release one this weekend.

**Comment by elect86** [comment]
Any news? Because it's a blocker for me :/

Ps: if I'd clone, change the kotlin version and produce a jar? Would that work?

**Comment by sksamuel** [comment]
Looking now.

**Comment by sksamuel** [comment]
1.3.6 is on maven central now compiled against kotlin 1.1 beta.

**Comment by elect86** [comment]
Thanks Stephen, really appreciated!

Sorry for pushing :p

**Comment by elect86** [comment]
It works like a charm, just tried

Thanks again

**Comment by elect86** [comment]
I know you hate me...

but could you release it for rc-91? :p
