### ISSUE TITLE
shouldThrow should take thunk: () -> Any?

### ISSUE THREAD

**Issue by JLLeitschuh** [kotlintest/kotlintest#148]
If the function inside of the thunk returns a null value then you get a kotlin null pointer exception.
I think the signature should be:
```kotlin
inline fun <reified T> shouldThrow(thunk: () -> Any?): T {
```
But I'm not 100% certain.

**Comment by sksamuel** [comment]
Agreed.

**Comment by aleixmorgadas** [comment]
Added into 2.0 version. 

You can view a call sample [here](https://github.com/kotlintest/kotlintest/blob/release/2.0/src/test/kotlin/io/kotlintest/matchers/ExceptionMatchersTest.kt#L38-L42) and the method definition [here](https://github.com/kotlintest/kotlintest/blob/release/2.0/src/test/kotlin/io/kotlintest/matchers/ExceptionMatchersTest.kt#L76-L80)

**Comment by JLLeitschuh** [comment]
Is there a 2.0 release somewhere?

**Comment by aleixmorgadas** [comment]
No, the 2.0 is still in development. I hope that the release could be as soon as possible 😄

**Comment by sksamuel** [comment]
https://github.com/kotlintest/kotlintest/issues/133

**Comment by aleixmorgadas** [comment]
This issue can be closed too 😄
