### ISSUE TITLE
Provide updated SNAPSHOT release

### ISSUE THREAD

**Issue by svenjacobs** [kotlintest/kotlintest#149]
Can you please provide an updated SNAPSHOT release of the 1.3.x branch which is compiled against the latest [RC version of Kotlin](https://blog.jetbrains.com/kotlin/2017/02/kotlin-1-1-release-candidate-is-here/) 1.1 EAP (`1.1.0-rc-91`)? Currently it's not possible to use KotlinTest 1.3.6 with this RC of Kotlin due to binary incompatibility :(

Thanks!

**Comment by elect86** [comment]
If interested, I forked it [here](https://github.com/elect86/kotlintest)

Use [jitpack](https://jitpack.io/#elect86/kotlintest/c4b7b397a0)

**Comment by svenjacobs** [comment]
@elect86 Thanks. As a temporary workaround this is okay.

**Comment by sksamuel** [comment]
I'll release this by Thursday night.

**Comment by svenjacobs** [comment]
@sksamuel Thanks! 👍

**Comment by sksamuel** [comment]
It's on Maven central now.

**Comment by elect86** [comment]
[kotlin 1.1](https://jitpack.io/#elect86/kotlintest/d8878d6da0)
