### ISSUE TITLE
shouldThrow should provide a reference to the caught exception

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#15]
At the moment it is only possible to test whether an exception of a certain was thrown:

```kotlin
shouldThrow<IllegalAccessException> {
  // code in here that you expect to throw a IllegalAccessException
}
```

But sometimes it is necessary to test some details of the exception like the message. This could be done by provider an overloaded `shouldThrow` method, which would provide a reference to the exception.

```kotlin
shouldThrow<IllegalAccessException> { exception ->
  // code in here that you expect to throw a IllegalAccessException
  exception.message should start with "Something went wrong"
}
```

**Comment by sksamuel** [comment]
I don't think the function can accept an exception, as that function is what generates the exception. You could do something like,

val ex = shouldThrow<IllegalAccessException> {
  // code in here that you expect to throw a IllegalAccessException
}
exception.message should start with "Something went wrong"

**Comment by helmbold** [comment]
You're right. It was a twisted thought. I'll add your example to the docs.

**Comment by sksamuel** [comment]
What I proposed doesn't exist yet, but I will add it now and publish 1.1.5 since its a very quick thing to add.

**Comment by helmbold** [comment]
Nice!

**Comment by sksamuel** [comment]
1.1.5 is on central now, if you want to update docs, please do :)

https://github.com/kotlintest/kotlintest/commit/55b323e13c45292e89f4b9a3539ab92cfce58b7e

**Comment by sksamuel** [comment]
PS. I put a blog up about testing http://www.51zero.com/blog/testing-in-kotlin
