### ISSUE TITLE
Support status for junit 5?

### ISSUE THREAD

**Issue by JLLeitschuh** [kotlintest/kotlintest#156]
Is there any support for junit 5? Is there plans to integrate with junit 5? Has junit 5 been tested with kotlin test?

**Comment by lenguyenthanh** [comment]
Yes, Junit 5 does support old unit test, so you can use kotlin test with junit 5 without any problem.

**Comment by sschuberth** [comment]
I was reading the question more like: When will kotlintest bump its own junit dependency from 4 to 5?

**Comment by sksamuel** [comment]
I'll bump it when jUnit 5 moves to final. At the moment it's still in alpha.
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.junit%22

**Comment by sschuberth** [comment]
> At the moment it's still in alpha.

Ah, sorry, I didn't realized that.

**Comment by sschuberth** [comment]
Actually, it seems JUnit 5 is split into more packages now, and a search for [org.junit.*](http://search.maven.org/#search%7Cga%7C1%7Cg%3Aorg.junit.*) shows it's at version 5.0.0-RC3 already.

**Comment by sschuberth** [comment]
FYI, JUnit 5 was released: https://github.com/junit-team/junit5/releases/tag/r5.0.0

**Comment by sksamuel** [comment]
Should update this and bump to 2.1.0 I'd say.

**Comment by helmbold** [comment]
I think we should investigate JUnit 5 a bit, since it is more modular than JUnit 4. See also [ Open Test Alliance for the JVM](https://github.com/ota4j-team/opentest4j).

**Comment by sksamuel** [comment]
We might want to be vary of junit 5 at the moment if people are having issues with it.
https://www.reddit.com/r/androiddev/comments/71drrq/which_kotlin_testing_framework_to_use/

**Comment by sksamuel** [comment]
Changed milestone to 3.0

I'm making good progress on the update to jUnit 5. One thing that has popped up @helmbold. `open fun interceptSpec(context: Spec, spec: () -> Unit)` inside the spec class - what's the point of passing in the spec instance itself, since when you are overriding the function you are already in the spec class. (I know it's useful elsewhere, but here?)

**Comment by helmbold** [comment]
You mean `context: Spec`, right? It's some time ago, since I've designed it, but if I remember correctly, the idea was to be able to have reusable interceptor functions (functions that can be used in more than one Spec).

**Comment by sksamuel** [comment]
3.0.0 RC1 is using jUnit 5.
If you have the time, please give it a try. There are some breaking changes that should be aware of by reading the changelog here: https://github.com/kotlintest/kotlintest/blob/master/CHANGELOG.md

**Comment by JLLeitschuh** [comment]
Is there now support for running specific tests in the IDE now?

**Comment by sksamuel** [comment]
You can run a single spec class. You can't run a single nested test. That requires an intellij plugin (which is in the works, but I offer no timescales https://github.com/kotlintest/kotlintest/tree/master/kotlintest-intellij )

**Comment by JLLeitschuh** [comment]
Makes sense.

**Comment by sksamuel** [comment]
You should see a little green plan icon by the spec class name in intellij.
