### ISSUE TITLE
Create a Gitter community

### ISSUE THREAD

**Issue by aleixmorgadas** [kotlintest/kotlintest#159]
Hello there!

I suggest to create a Gitter community to talk about kotlintest development/features/issues. What do you think?

**Comment by sksamuel** [comment]
I'd be up for that. @helmbold ?

**Comment by helmbold** [comment]
I've not used Gitter yet, but why not?!

**Comment by sksamuel** [comment]
https://gitter.im/kotlintest/Lobby
