### ISSUE TITLE
Run all tests in package/whole project from IntelliJ

### ISSUE THREAD

**Issue by dkandalov** [kotlintest/kotlintest#161]
When I run all tests from IJ, it says `0 test classes found in package '<default package>'`.
However, if I add class junit tests, then IJ will run them.

kotlintest 1.3.7
IntelliJ IDEA 2017.1 EAP Build #IU-171.3780.15, built on March 8, 2017

**Comment by sksamuel** [comment]
If you upgrade to 2.x this will work.
