### ISSUE TITLE
Need shouldCause<Exception>

### ISSUE THREAD

**Issue by debop** [kotlintest/kotlintest#164]
Hi

shouldThrow<T> very simple and useful.

need specify inner exception (cause exception) like assertj  (hasCause, hasCauseInstanceOf ...)

shouldCause<T> is proper name^^

**Comment by sksamuel** [comment]
You can get the exception from shouldThrow and then add a further assertion.

**Comment by debop** [comment]
Thanks.

Coding like this

`
val ex = RuntimeException("boom")
val ce = shouldThrow<CompletionException> {
                    val future = completableFutureOf<String>(ex)
                    completedOf(future)
}
ce.message?.let { it should(have) substring "boom" }
ce.cause should(be) an RuntimeException::class
ce.cause shouldEqual ex
`
