### ISSUE TITLE
Add support for test scopes

### ISSUE THREAD

**Issue by ykrasik** [kotlintest/kotlintest#167]
This a small suggestion of adding the ability to pass in a scope object (fixture) per-test.
It's supported by both Specs2 and Scalatest and is convenient for removing code that generates test data out of the test, allowing the test code itself to focus on the logic being tested.

It's a pretty minor addition that's easy to implement, for example for StringSpec it would look like this:
`fun <T> String.inScope(scope: T, test: T.() -> Unit): TestCase = this.invoke { test(scope) }`
and tests using it would look like this with StringSpec:
```
class SomeTest : StringSpec() {
    inner class Scope {
        val data = Gen.string().nextPrintableString(length = 5)
    }

    "Test something".inScope(Scope()) { 
        data.length shouldBe 5
    }
}
```

**Comment by sksamuel** [comment]
I don't understand sorry. What's the different between that and say:

```kotlin
class SomeTest : StringSpec() {
    inner class Scope {
        val data = Gen.string().nextPrintableString(length = 5)
    }

    

    "Test something") { 
        val scope = Scope()
        scope.data.length shouldBe 5
    }
}
```

**Comment by ykrasik** [comment]
You're right, it's practically the same. I tried your approach before posting the suggestion - it's fine for small examples, but for test scopes that contain a lot of data, prefixing each variable access with `scope.` is tedious.
The same effect can be achieved by using `with(Scope()) {... }`, but that would potentially add another nesting level.
So this suggestion doesn't add any new functionality that can't already be achieved, but I think it'll allow a bit more convenience.

**Comment by helmbold** [comment]
I think it is a balancing act to decide what features to add and what to leave out.

The example above could also be expressed via an ordinary property.

```kotlin
class SomeTest : StringSpec() {

    val data: String
        get() = Gen.string().nextPrintableString(length = 5)

    "Test something" { 
        data.length shouldBe 5
    }
}
```

Do you want scopes to group several objects? Like in 

```kotlin
inner class Scope {
  val data = Gen.string().nextPrintableString(length = 5) 
  val other = ...
}
```
If the grouping is relevant, why not use table-driven testing, then? If the grouping isn't relevant, could also use independent functions/properties as shown above.

**Comment by ykrasik** [comment]
Agreed - this offers nothing new and is a matter of style. I'll just keep using my own extension method :)
