### ISSUE TITLE
README.md examples should not rely on non-standard dependencies

### ISSUE THREAD

**Issue by holgerbrandl** [kotlintest/kotlintest#18]
Where is ListStack coming from? It does not seem to  be jdk or kotlin-stdlib.

Imho landing page examples should self-contained and easy to reproduce.

Also even if the readme mentions the init-block and that everything needs to go inside, it would be easier to get started if all examples would be self-contained (full classes).

**Comment by sksamuel** [comment]
Ok good points. I'll update those examples so that they use regular jdk
classes and are fully standalone.

**Comment by sksamuel** [comment]
I've updated teh readme with simpler examples https://github.com/kotlintest/kotlintest/commit/5d7f3757fe964d436c93c86fc43b56126598102b

**Comment by holgerbrandl** [comment]
Awesome, thanks a lot. Great library especially when coming from ScalaTest

**Comment by sksamuel** [comment]
Thanks
