### ISSUE TITLE
Add Matcher containTheSameElementsInOrderAs

### ISSUE THREAD

**Issue by DWiechert** [kotlintest/kotlintest#180]
It would be nice to add a matcher for `containTheSameElementsInOrderAs`.  This could be based off of the same matcher from [ScalaTest sequences](http://www.scalatest.org/user_guide/using_matchers#workingWithSequences).

**Comment by DWiechert** [comment]
I wrote a rudimentary matcher which accomplishes this for my own testing:
```
fun <E> containTheSameElementsInOrderAs(expected: List<E>) = object : Matcher<List<E>> {
	override fun test(actual: List<E>): Result {
		val errorMessage = "[$actual] did not contain the same elements in order as [$expected]"
		val expectedSize = expected.size
		val actualSize = actual.size
		if (expectedSize != actualSize) {
			return Result(false, errorMessage)
		} else {
			var eq = true
			var message = ""
			var index = 0
			while (index < expectedSize) {
				val e = expected.get(index)
				val a = expected.get(index)
				if (e != a) {
					eq = false
					message = errorMessage
				}
				index++
			}
			return Result(eq, message)
		}
	}
}
```
However, I'm not sure if there's a better way to implement this matcher.

**Comment by sksamuel** [comment]
I've added one like the Scala one, that allows duplicates, and doesn't insist on sizes being equal. If that's what you care about, you can always do `mylist shouldBe expected`. See what you think.
https://github.com/kotlintest/kotlintest/commit/5e21f557e296f292f405110795672bdc42e1c8cf
