### ISSUE TITLE
Change exception.cause shouldBe beInstanceOf

### ISSUE THREAD

**Issue by AshleyByeUK** [kotlintest/kotlintest#185]
To check for the cause of an exception, I have to use:
```
val exception = shouldThrow<RuntimeException> {
    // Whatever.
}
exception.cause shouldBe beInstanceOf(FileNotFoundException::class)
```

Any chance of fixing the matchers so that it reads like either (or both) of the following:
```
exception.cause should beInstanceOf(FileNotFoundException::class)
```
or
```
exception.cause shouldBe instanceOf(FileNotFoundException::class)
```
It's probably not the biggest issue in the world, but it does read strangely and it took me a while to figure out the correct combination of matchers. I think a more natural language flow would help.

Follows from [https://github.com/kotlintest/kotlintest/issues/164](https://github.com/kotlintest/kotlintest/issues/164).

**Comment by sksamuel** [comment]
I've added an alias, so `exception.cause shouldBe instanceOf(FileNotFoundException::class)` now works.
