### ISSUE TITLE
Test classes are not shown in correct package in test report

### ISSUE THREAD

**Issue by sschuberth** [kotlintest/kotlintest#188]
When having a test class whose file path "mismatches" the package name, like `src/test/kotlin/SimpleTest.kt` (note, no package structure in the path) which contains code like:

    package com.pany.project.tests

    class SimpleTest {
    }

Then the "Packages" view in the HTML test report (as generated via Gradle 4.0) shows the tests from `SimpleTest` to belong to `default-package` instead of `com.pany.project.tests`.

**Comment by miguelcp646** [comment]
Same here.
Also, when using BehaviorSpec the "Given" part is not used in the name of the test, only When and Then are used.
This makes it difficult to use kotlintest in jenkins for example.

**Comment by kastork** [comment]
I see the same behavior even when I follow the normal package-structure/directory-structure conventions.

`src/test/kotlin/com/pany/project/tests`

```
package com.pany.project.tests

class SimpleTest {
}
```

**Comment by sksamuel** [comment]
This behavior is fixed in 3.0. Multiple classes can reuse the same test name, and the same "string" contexts.
