### ISSUE TITLE
Gen.choose() should support negative numbers

### ISSUE THREAD

**Issue by pakoito** [kotlintest/kotlintest#192]
https://github.com/kotlintest/kotlintest/blob/master/src/main/kotlin/io/kotlintest/properties/Gen.kt#L19

The current implementation forgets that the minimum can be a negative number thus for cases like Int.MIN it'd throw `java.lang.IllegalArgumentException: bound must be positive`

**Comment by pakoito** [comment]
Thank you!

**Comment by sksamuel** [comment]
Try 2.0.6.
