### ISSUE TITLE
Consider replacing MockitoSugar with mockito-kotlin or mockito4k

### ISSUE THREAD

**Issue by sschuberth** [kotlintest/kotlintest#193]
The [current MockitoSugar](https://github.com/kotlintest/kotlintest/blob/7e768d3784665c53eeeb049fcb250f28e692a541/src/main/kotlin/io/kotlintest/mock/MockitoSugar.kt) is quite incomplete, so if mocking is required, you'd probably have to use something like [mockito-kotlin](https://github.com/nhaarman/mockito-kotlin) or [mockito4k](https://github.com/tmurakami/mockito4k) anyway. So how about kotlintest coming with either one itself?

**Comment by sksamuel** [comment]
Yes this is a good idea. @sschuberth  @helmbold do you have any preference on which project is better?

**Comment by sksamuel** [comment]
I think the one with 566 stars is probably the leading candidate.

**Comment by sschuberth** [comment]
I don't have a clear preference (yet), but just wanted to comment that mockito-kotlin probably has more stars because it's included at [awesome-kotlin](https://kotlin.link/) while is mockito4k is not.

**Comment by helmbold** [comment]
I haven't used any of the both yet. However, if it is an external depency anyway, why include it in KotlinTest? A single line in build.gradle would be enough and we could feature it in the docs.

**Comment by sksamuel** [comment]
Fair point from @helmbold. Unless there was an advantage in some level of integration.

**Comment by davidgoli** [comment]
*An* example in the documentation of how to use either MockitoSugar or mockito-kotlin with kotlintest would be terrific. It's not obvious how to perform shared setup within the test context using kotlintest "testing styles".

**Comment by davidgoli** [comment]
(specifically coming from rspec-style test formats with a `before` block to set up mocks & stubs for multiple test cases)

**Comment by davidgoli** [comment]
(and I for one do not consider Interceptors a syntactically acceptable implementation of a shared block, as an Interceptor has to be attached explicitly to each case instead of being declared once using block syntax)

**Comment by sksamuel** [comment]
You can just setup the variables outside of the test blocks, eg just put a `val name = "sam"` after `init {}`. If you need to do something more complex, you can do `val mock = mock(MyClass::class.java).apply { setup here }`

**Comment by davidgoli** [comment]
that could work in some cases, as a `beforeAll`, but I don't think it would work when you need a `beforeEach` or nested blocks, where different cases have different setup accordingly.

Maybe I'm just stuck on rspec, Quick for Swift/iOS is pretty great in that vein too.

**Comment by davidgoli** [comment]
I'm also wondering how truly useful `BehaviorSpec` is when you can't really provide a specific implementation for each `when` outside of the `then` block (as eg. Capybara allows)

**Comment by sksamuel** [comment]
The latest version 3.0.0-RC1 allows proper nesting of variables in specs, like you mention for BehaviorSpec.

**Comment by sksamuel** [comment]
In master I've removed the mockito sugar. There's really no need for it, as like people said, just import whatever mocking library you want and use it. The sugar was adding nothing and was bringing in a dependency.

**Comment by alanzhag** [comment]
Sorry for the issue-necromancy, but was [mokk](https://github.com/mockk/mockk) available as an option when this came up?
We are reviewing pro-cons of mockito-kotlin vs mokk and we just started to use KotlinTest, so we were wondering why this project was using mockito-kotlin. Any opinions regarding the issue would be appreciated!
-> [Interesting mokk vs mockito-kotlin thread](https://www.reddit.com/r/androiddev/comments/9us0a0/mockk_vs_mockitokotlin/)
