### ISSUE TITLE
Separate runner and assertion library ?

### ISSUE THREAD

**Issue by r3mi** [kotlintest/kotlintest#195]
As these are different concerns : would you consider releasing separately the spec runner (`StringSpec`...) and the assertion library (`should` ...) ?

**Comment by sksamuel** [comment]
Do you work for @helmbold  ;)

**Comment by r3mi** [comment]
thanks for the link.
sorry for being redundant if this subject was already discussed.
Is there any relation between these projects (korrekt) ?

**Comment by sksamuel** [comment]
No none. I just joke because Mr Helmbold was a big fan of splitting the
libraries and me not so much.

**Comment by sksamuel** [comment]
I think we could do this for 2.1. Ship two jars.

**Comment by sksamuel** [comment]
I'm doing to do this in 3.0

**Comment by sksamuel** [comment]
I've now split the project into core, assertions, runners and spring.

**Comment by sksamuel** [comment]
This is now part of 3.0.0 RC1.
If you have the time, please give it a try. There are some breaking changes that should be aware of by reading the changelog here: https://github.com/kotlintest/kotlintest/blob/master/CHANGELOG.md
