### ISSUE TITLE
Interceptors are not working correctly

### ISSUE THREAD

**Issue by igorwojda** [kotlintest/kotlintest#198]
I tried to use interceptors to initialize mockito mocks. It looks like they are not invoked at all. 

Here is sample project with tests
https://github.com/igorwojda/migrate-java-tests-to-kotlin

**Comment by sksamuel** [comment]
I looked at your sample project uses Spek not Kotlin test.
https://github.com/igorwojda/migrate-java-tests-to-kotlin/blob/master/core/src/test/kotlin/igorwojda/com/presentertest/core/CorePresenterTestSpek.kt
