### ISSUE TITLE
throwable does not cause test to fail

### ISSUE THREAD

**Issue by holgerbrandl** [kotlintest/kotlintest#20]
Example:
```
class MyException() : Throwable()

class Playground : FlatSpec() { init {
    "it" should "do something" {
        throw MyException()
    }

    "it" should "do something else" {
    }
}
}
```
In Intellij/gradle this gives an incorrect picture like if the first test suceeded correctly.
![image](https://cloud.githubusercontent.com/assets/200952/15626107/141aa72a-24bc-11e6-888f-e99adf7f0c01.png)

If a `class MyRunException() : RuntimeException()` instance is thrown instead, the test is tagged as failed as expected. Why don't `Throwable`s cause tests to fail but require RuntimeException as base class? 

I thought it may be a junit feature/problem after all but it does not seem to be the case:
```

public class Dummy {

    @Test
    public void runTest() throws Throwable {
        throw new Throwable();
    }

    @Test
    public void runAnotherTest() throws Throwable {
    }
}
```
Here `runTest` fails as expected:
![image](https://cloud.githubusercontent.com/assets/200952/15626133/d036b444-24bc-11e6-8479-f38a593d8fad.png)

**Comment by sksamuel** [comment]
:+1: Sounds like I just need to change Exception to Throwable.
