### ISSUE TITLE
Inspectors (like forAll, forOne) give really small amount of feedback

### ISSUE THREAD

**Issue by myhau** [kotlintest/kotlintest#206]
Currently when I for example do `forAll(someCollection, ...)` and one test failed for some element of the collection, I only receive info about how many tests failed.

I think it should be much more verbose, and give info about for which element of collection it failed (print it and in case toString is not implemented print index or use some reflection-based "toString generator")

**Comment by sksamuel** [comment]
I've made a change which means the output is now like this:

```
java.lang.AssertionError: 0 elements passed but expected at least 1

The following elements passed:
--none--

The following elements failed:
1 => expected: 6 but was: 1
2 => expected: 6 but was: 2
3 => expected: 6 but was: 3
4 => expected: 6 but was: 4
5 => expected: 6 but was: 5
```

or

```
java.lang.AssertionError: 5 elements passed but expected 0

The following elements passed:
1
2
3
4
5

The following elements failed:
--none--
```

**Comment by sksamuel** [comment]
Great idea, so thanks for the issue :)
