### ISSUE TITLE
collection matching does not work as expected

### ISSUE THREAD

**Issue by holgerbrandl** [kotlintest/kotlintest#21]
The scala-way of testing collections does not yet work correctly in kotlintest:
```
listOf("foo", "bar_1", "bar_b2") should contain "sdf" 
//nor
listOf("foo", "bar_1", "bar_b2") should be listOf("lala")
```
See http://www.scalatest.org/user_guide/using_matchers#javaCollectionsAndMaps

**Comment by sksamuel** [comment]
There are limits as to what Kotlin supports DSL wise. It's not quite as flexible as Scala in some areas. To test for collection inclusion, you do

`col should contain element x`

**Comment by holgerbrandl** [comment]
thanks

**Comment by russel** [comment]
I would have suggested:
```kotlin
col.contains(x) shouldBe true
```
or perhaps more likely for me:
```kotlin
(x in col) shouldBe true
```

**Comment by sksamuel** [comment]
'col.contains(x) shouldBe true' should work ?

**Comment by russel** [comment]
I haven't checked, but I use things like:
```kotlin
(x in col) shouldBe true
```
in a lot of my tests and they are passing.
