### ISSUE TITLE
get context in test

### ISSUE THREAD

**Issue by felixsoares** [kotlintest/kotlintest#210]
Can I get the context inside the kotlin test? Or make a mock of a context?

**Comment by helmbold** [comment]
You can get the context in an interceptor. What do you want to do with the context?

**Comment by felixsoares** [comment]
I was trying to do a test in which I took some data from the screen and in this case I would need the context

**Comment by helmbold** [comment]
You could do whatever you want to do with the context in an [interceptor](https://github.com/kotlintest/kotlintest/blob/master/doc/reference.md#interceptors-), store the result in a field and then use it in a test case. If the result object is not thread safe, you should configure KotlinTest to use one instance per test case.

**Comment by felixsoares** [comment]
Can you show me an example?

**Comment by helmbold** [comment]
You could get the context like this:

```kotlin
class MyTests : StringSpec() {

    override val oneInstancePerTest = true
    private context: TestCaseContext? = null

    init {
        "should do something with the context ..." {
            // use context here
        }
    }

    override fun interceptTestCase(context: TestCaseContext, test: () -> Unit) {
        this.context = context
        test() 
    } 
}
```

**Comment by felixsoares** [comment]
thanks, this solved my problem!
