### ISSUE TITLE
Gen<T> should return Iterable, not single random value

### ISSUE THREAD

**Issue by jankotek** [kotlintest/kotlintest#212]
I do not like `Gen.generate()` method. 

Basic reason for properties driven development is to cover corner cases: 
* For String that would be empty strings, UTF8 chars, multi lines... 
* For Long that is Long.MAX_VALUE. 
* For Double that is NaN, negative infinity....

Good generator returns all of those corner cases and some random data. However current version just returns random data. There is very tiny chance you will hit corner case such as empty string. 

So I suggest:
* extent `Gen` interface with new method, that would return iterable over corner cases. Those would be included in `forAll` together with random data. 
* To keep backward compatibility there will be default implementation of this method, that returns empty iterable. Default implementation will be removed in new version (3.0)
* We expand default gens (String, numbers...) to include corner cases

**Comment by sksamuel** [comment]
This is a good suggestion. I'll tackle it at some point unless you'd like to make a PR?

**Comment by jankotek** [comment]
no PR
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/kotlintes
> t/kotlintest","title":"kotlintest/kotlintest","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/kotlintest/kotlintest"}},"updates":
> {"snippets":[{"icon":"PERSON","message":"@sksamuel in #212: This is a
> good suggestion. I'll tackle it at some point unless you'd like to
> make a PR?"}],"action":{"name":"View
> Issue","url":"https://github.com/kotlintest/kotlintest/issues/212#iss
> uecomment-331267618"}}}

**Comment by sksamuel** [comment]
@helmbold this is a good idea, I think we should somehow change the generators to manually include corner cases (for certain generators) rather than relying on the random generator to generate them. We might need a new interface which would return an Iterable like @jankotek says. Maybe all it Generator this time instead of Gen.

**Comment by sksamuel** [comment]
Generators now return iterators of values. These iterables are combined together to form the powerset of values for the given generators.
