### ISSUE TITLE
Support for Android Studio 3.0?

### ISSUE THREAD

**Issue by captainjapeng** [kotlintest/kotlintest#217]
Running KotlinTest in Android Studio 3.0 Beta 6 (IntelliJ 2017.1.2) results into this error.

> Process finished with exit code 1
Class not found: "retrofit2.converter.jsonrpc2.JsonRPC2ConverterFactoryTest"Empty test suite.

But running tests using `gradlew test` works without any problems

**Comment by sksamuel** [comment]
Is there a full stack trace ?

**Comment by captainjapeng** [comment]
No stack trace... [Here's](https://pastebin.com/siEjrrRs) the command it runs, hope it helps...

**Comment by captainjapeng** [comment]
Updated to Beta 7 and everything seems to be fine now...

**Comment by sksamuel** [comment]
Great.
