### ISSUE TITLE
Do exist an updated changelog with the changes by version?

### ISSUE THREAD

**Issue by jrcacd** [kotlintest/kotlintest#220]

**Comment by stkent** [comment]
A changelog exists but has not been updated since v2.0.0.

**Comment by sksamuel** [comment]
3.0.0 RC1 is released and I've updated the change log. https://github.com/kotlintest/kotlintest/blob/master/CHANGELOG.md
If you have the time, please give it a try. There are some breaking changes that should be aware of which are covered by the changelog.
