### ISSUE TITLE
2.0.6 incompatible with java 7

### ISSUE THREAD

**Issue by michalbrz** [kotlintest/kotlintest#223]
I was trying to create Android unit test (aka instrumented test) with kotlintest and I got:

`Error:15:12:27.770 [ERROR] [org.gradle.api.Project] AGPBI: {"kind":"error","text":"Error converting bytecode to dex:\nCause: Dex cannot parse version 52 byte code.\nThis is caused by library dependencies that have been compiled using Java 8 or above.\nIf you are using the \u0027java\u0027 gradle plugin in a library submodule add \ntargetCompatibility \u003d \u00271.7\u0027\nsourceCompatibility \u003d \u00271.7\u0027\nto that submodule\u0027s build.gradle file.\n...while parsing io/kotlintest/JavaRandoms.class","sources":[{}],"original":"PARSE ERROR:\nunsupported class file version 52.0\n...while parsing io/kotlintest/JavaRandoms.class\n","tool":"Dex"}`

When I change (and I'm sure this is the only change) version to 2.0.5, test runs correctly. It seems that 2.0.6 was compiled to java 8 bytecode - probably not on purpose?

I inspected bytecode and I see that kotlin classes have correct bytecode version (50) but java classes (e.g. JavaRandoms from error message) have bytecode version 52.

**Comment by sksamuel** [comment]
No not on purpose and the reason I created the JavaRandoms class was to bring in some code that was only available in 1.8!. I can't see any changes other than bumping the version of the gradle release plugin.

**Comment by sksamuel** [comment]
So it's only the java files that are compiled as java 8. I wonder if gradle defaults to 1.8 and the kotlin compiler overrides it for kotlin files but not java files.

**Comment by sksamuel** [comment]
Ok I've fixed it by forcing the java files to be 1.6. Will be in 2.0.7 which I'll release shortly.

**Comment by michalbrz** [comment]
Wow, that was quick, thank you!
