### ISSUE TITLE
3.0 Breaking Changes

### ISSUE THREAD

**Issue by sksamuel** [kotlintest/kotlintest#227]
I would like to discuss whether for 2.1 we should 

a) Disable a new instance per test by default (so all the tests in a suite are a single instance of that class, which is the case with junit, spek, scalatest, specs2 etc). #163 #174
b) Disable project scan by default. #226 #225 #219
c) Upgrade to jUnit 5.1 #156  #187
d) Change generators to return an Iterable rather than a single instance #212
e) Your requirement here...

**Comment by helmbold** [comment]
First, I'm a proponent of semantic versioning and would raise the version to 3.0, if we would introduce breaking changes.

a) I'm still thinking that a new instance per test is a good thing to isolate tests. Isolated tests are helpful on parallel execution, too. The problem mentioned in #163 would not be solved, if we would switch the default, since it would only mask the root cause.  
To #174: I commented directly on the issue. I think onInstacePerTest=false wouldn't solve the problem.

b) Could probably be solved enforcing a certain class name for config.

c) ok

d) ok

**Comment by sksamuel** [comment]
@helmbold Let's go semver then, and bump to 3.0.0.
This means we can also be a little bit more adventurous in anything we like. One idea I was thinking, was that we could replace all specs with a "do what you want spec", where you have a preconfigured list of keywords - `should`, `test`, `given`, etc, and you can just lay them out like you want. The nesting is up to you, only the final String.invoke method is where the test is executed.

We should also add future based matchers. These will simply do the blocking for you in the test runner, so you can do things like, `myAsyncFun("foo") shouldBe "bar"` and `myAsyncFun` returns `Future<String>` in this case.

I'm also going to look at junit 5 see what new features it would allow.

**Comment by michalbrz** [comment]
a) What is the reason behind proposition to disable a new instance per test by default? If kotlintest wants to be easy to understand for JUnit users, it **should** create new instance for every test. This is how it works in JUnit 5 and this how it worked before - http://junit.org/junit5/docs/current/user-guide/#writing-tests-test-instance-lifecycle. Also this is not the cause of #174 as I've already commented on that issue.
c) Sure, but do you know how would that influence Android developers? Will this require any additional configuration?
d) Sounds good. Possibly it might not require to change Gen<T> interface to not break too many things?

**Comment by sksamuel** [comment]
@michalbrz I didn't realize junit was one instance per test. Maybe I've been doing Scala too long. @helmbold did you know this ?

**Comment by helmbold** [comment]
@sksamuel Yes, I was aware of JUnit using one instance per test by default. Test parametrization in JUnit 4 even only works that way (or at least, parallel test execution would be impossible otherwise).

**Comment by sksamuel** [comment]
3.0 keeps one instance per test.
Project scan now disabled.
