### ISSUE TITLE
Is it possible to modify the test name to display?

### ISSUE THREAD

**Issue by elect86** [kotlintest/kotlintest#238]
As titled, when I have

`class A : StringSpec() `

I'd like to display, for example, `B`

The real reason behind is to have the possibility to display names containing dots `.` to match 100% the file being tested by the i-th test

**Comment by sksamuel** [comment]
Don't see why not, perhaps using an annotation. Added for 3.0 release.

**Comment by sksamuel** [comment]
In KotlinTest 3.0 you can use @DisplayName on the class name, eg 
https://github.com/kotlintest/kotlintest/blob/a63f1abb4532a1b4a58b63b2dd272e8fefba7e76/kotlintest-runner-junit5/src/test/kotlin/io/kotlintest/DisplayNameTest.kt

**Comment by sksamuel** [comment]
This is now part of 3.0.0 RC1.
If you have the time, please give it a try. There are some breaking changes that should be aware of by reading the changelog here: https://github.com/kotlintest/kotlintest/blob/master/CHANGELOG.md
