### ISSUE TITLE
containExactly & containAll matchers for checking Map's

### ISSUE THREAD

**Issue by anti-social** [kotlintest/kotlintest#239]
In one of my preject I need to compare big enough maps in the tests. So I suggest `containExactly` & `containAll` matchers to check maps equality.

For example next `containExactly`:
```
mapOf("a" to mapOf("b" to 1)) should containExactly(
    mapOf("a" to mapOf("b" to 2, "c" to 3))
)
```
could produce assertion with diff:
```
java.lang.AssertionError: 
Expecting:
  {"a"={"b"=1}, "c"=2}
should be equal to:
  {"a"={"b"=2, "c"=3}}
but differs by:
  extra keys:
    "c"
  different values:
    "a":
      missing keys:
        "c"
      different values:
        "b":
          expected:
            2
          but was:
            1
```

`containAll` should ignore extra keys in the given map.

Think it would be nice to have such matchers in kotlintest upstream. I implemented simplified versions of the matchers so can create a PR.

**Comment by sksamuel** [comment]
Would love a PR, or if not I can implement from scratch.

**Comment by anti-social** [comment]
Can't test due to #260

**Comment by sksamuel** [comment]
Working on #260 at the moment, expect master to work in the next few hours.

**Comment by sksamuel** [comment]
I've added basic stubs for these if you want to finish them off (ie, the advanced error reporting). Master should now be all good to go.

**Comment by anti-social** [comment]
I have several doubts about naming clash and diff representation:

- there is already `containsAll` matcher for collections
- java represents maps and lists as `{key=value}` and `[v1, v2]` accordingly, but I decided to use representation that can be copied and pasted into REPL

**Comment by sksamuel** [comment]
I think it's so much better than before the few doubts don't really matter.
