### ISSUE TITLE
Is there a KotlinCheck?

### ISSUE THREAD

**Issue by russel** [kotlintest/kotlintest#24]
ScalaTest works best when used with ScalaCheck, this way you get example-based and property-based testing in the same test framework. If KotlinTest is ScalaTest for Kotlin (which is seems to be :-) ) is there a Kotlin equivalent of ScalaCheck (let's call it KotlinCheck), and is it integrated into KotlinTest as ScalaCheck is in ScalaTest?

**Comment by sksamuel** [comment]
I've started adding some property based testing. See
https://github.com/kotlintest/kotlintest/issues/5
I don't see a need to call it Kotlin Check. That happened in scala as
they're two separate projects. But other than that should be fairly similar
when completed for release 1.2.0.

**Comment by russel** [comment]
I agree, just having the ScalaCheck equivalent of automated value generation based on type and explicit generation for awkward cases plus shrinking is the important thing. There is no need for multiple names following Scala, put it all in KotlinTest.

I missed #5 apologies. However table-driven testing is already supported in KotlinTest with forAll cf. https://github.com/russel/Factorial/blob/master/Kotlin/src/test/kotlin/uk/org/winder/maths/factorial/Factorial_KotlinTest.kt so the emphasis must be on properties and automated test value selection. I will switch to #5 for my thoughts and so am closing this issue.
