### ISSUE TITLE
Multiplatform/Android support

### ISSUE THREAD

**Issue by jmfayard** [kotlintest/kotlintest#241]
Hello,

I wonder if it would be possible to split kotlintest between a part that works everywhere and the most advanced stuff that depends on it running on the JVM.

My motivation for asking the question is that adding kotlintest as a dependancy for the android instrumentation tests fails for me

Steps:

- create blank new android studio project
- add to `app/build.gradle` :     androidTestImplementation 'io.kotlintest:kotlintest:2.0.7'
- Try to run the default `ExampleInstrumentedTest`

```
':app:transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
```

--- 

I know some parts of kotlintest cannot work because of restrictions on the android side (like the junit runner)
But the reason why I want to do that is that I have shared code between my unit tests (JVM tests) and my android tests where I would like to at least used kotlintest matchers. Right now I'm rolling on my own poor man version of `T.shouldBe()` to have my assertions working there.

Likewise I imagine that in a multiplatform jvm/js project you won't be able to use the runner part, but it should be possible to make the matchers work.

**Comment by gzoritchak** [comment]
Maybe this issue should be renamed as Multiplatform support.

We currently ported part of kotlintest in our library to be able to use its semantic in multiplatform tests but the goal of course would to use the original library:

https://github.com/data2viz/data2viz/tree/master/tests

**Comment by sksamuel** [comment]
Closing in favour of the combined ticket here https://github.com/kotlintest/kotlintest/issues/242
