### ISSUE TITLE
Multi Platform - Kotlin JS

### ISSUE THREAD

**Issue by napperley** [kotlintest/kotlintest#242]
Kotlin Test currently works with Kotlin JVM. Are there any plans for Kotlin Test to provide support for **Kotlin JS**? Would make Kotlin multi-platform testing **SIGNIFICANTLY** easier to achieve in some scenarios where Kotlin is used on both the back-end (Kotlin JVM) and font-end (Kotlin JS).

Could Kotlin JS support be part of the Kotlin Test 3.0 plans?

**Comment by sksamuel** [comment]
I don't use kotlin.js so what would need to be done to make this work?

**Comment by napperley** [comment]
For starters **significant** changes would need to be made to the Kotlin Test API. Instead of the current API there would be a **core** API (common module - doesn't use any platform specific APIs) and **platform** APIs (platform modules for JVM, JS Android etc). Important to note that a JVM platform module **can** use JUnit APIs. Check out this [Kotlin multi-platform article](https://blog.kotlin-academy.com/multiplatform-native-development-in-kotlin-now-with-ios-a8546f436eec) and pay close attention to the architectures that are used.

Ultimately a big decision will need to be made on whether Kotlin Test will be multi-platform or not, and if so which Kotlin Test version will introduce multi-platform support.

**Comment by sksamuel** [comment]
I don't do android development myself. Is there the equivalent of junit used to execute tests?

**Comment by napperley** [comment]
Not sure since I don't have some Android development experience. Looks as though JUnit 4 can be used to cover [unit testing](https://developer.android.com/training/testing/unit-testing/local-unit-tests.html) for Android.

**Comment by napperley** [comment]
Have a look at [this video](https://youtu.be/afc5PUs_EPE?t=2181) which covers Kotlin multi-platform testing. Might provide some ideas on doing a basic implementation.

**Comment by napperley** [comment]
@sksamuel - Check out this Kotlin JS test [prototype](https://github.com/napperley/kotlinjs-test-proto). Note that reflection is close to non existent in Kotlin JS. Better to stick with the explicit programming approach.

**Comment by sksamuel** [comment]
@napperley what do people do at the moment for kotlin.js tests?

**Comment by napperley** [comment]
Kotliners mainly use a JS testing library/framework (QUnit, Jasmine, Mocha, Jest, Karma, Tape etc) with Kotlin JS. Also the Kotlin Test library (the JetBrains one) can be used, however it relies on having one of the above JS testing libraries/frameworks installed since it uses them for the backend.

In the Kotlin Examples repository there are some [Kotlin JS testing examples](https://github.com/JetBrains/kotlin-examples/tree/master/gradle/js-tests).

**Comment by gzoritchak** [comment]
I've done a partial port for our multiplatform tests: 
https://github.com/data2viz/data2viz/tree/master/tests

**Comment by ScottPierce** [comment]
This library should also work for [Kotlin/native](https://kotlinlang.org/docs/reference/native-overview.html) and [Kotlin Common](https://kotlinlang.org/docs/reference/multiplatform.html) modules.

**Comment by sksamuel** [comment]
This is on the roadmap for 4.0

**Comment by kuhnroyal** [comment]
@sksamuel Is Kotlin/native included in the roadmap or only JS?

**Comment by LeoColman** [comment]
For now we are directing to JS + JVM first.

However, a bunch of code will be in the `common` modules, so a big part of them will be useful for Native too

**Comment by sksamuel** [comment]
Native will come pretty much for free after the js work.

**Comment by sksamuel** [comment]
JS support is now working in the latest 4.0 snapshot.
