### ISSUE TITLE
New convenient function for Generator

### ISSUE THREAD

**Issue by alex-ber** [kotlintest/kotlintest#243]
Please add function to the interface Gen in package io.kotlintest.properties
for generating BigInteger.

Proposed implementation:

```
fun bigInteger(maxNumBits:Int=32): Gen<BigInteger> = object : Gen<BigInteger> {
    private val numBitsGen:Gen<Int> = Gen.choose(0, maxNumBits)

    override fun generate(): BigInteger {
        val numBits:Int = numBitsGen.generate()
        return BigInteger(numBits, RANDOM)
    }
}
```

**Comment by sksamuel** [comment]
Thanks, added to master, will be in release 3.0.0.

**Comment by sksamuel** [comment]
This is added in 3.0.0 RC1.
If you have the time, please give it a try. There are some breaking changes that should be aware of by reading the changelog here: https://github.com/kotlintest/kotlintest/blob/master/CHANGELOG.md
