### ISSUE TITLE
Support Spring Autowiring

### ISSUE THREAD

**Issue by bondpp7** [kotlintest/kotlintest#251]
Spring (and Spring-boot) are utilized by a large number of developers.  It would be tremendously helpful if the ability to use the Spring context within KotlinTest tests were "officially" supported and the process streamlined.

Some work has been done (by someone other than me) at https://github.com/Acomodeo/kotlintest-spring.    Any work that can be done to either enable the work done by that project to work "smoothly", or perhaps even integrate support for the Spring context more directly within this project, would be greatly appreciated.

**Comment by sksamuel** [comment]
Good idea, I'll look at what is required.

**Comment by sksamuel** [comment]
Spring support is added in 3.0.0 RC1. 
If you have the time, please give it a try. There are some breaking changes that should be aware of by reading the changelog here: https://github.com/kotlintest/kotlintest/blob/master/CHANGELOG.md
