### ISSUE TITLE
Gen.kt uses method from Kotlin 1.2

### ISSUE THREAD

**Issue by NersesAM** [kotlintest/kotlintest#255]
I am trying to build the project but there are compilation errors. I am not sure what I am doing wrong.

Kotlin version is set to 1.1.60
but Gen.kt `import kotlin.math.abs` which is introduced in 1.2

**Comment by NersesAM** [comment]
just saw that the build is failing as well https://travis-ci.org/kotlintest/kotlintest/builds/343241761

**Comment by sksamuel** [comment]
Will be the work I'm doing for v2 :)

**Comment by sksamuel** [comment]
Fixed in master, thanks.
