### ISSUE TITLE
create release branches

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#26]
It would be easier to contribute, if each release (1.2,  1.3, 2.0 ...) would have an own branch. I have an idea which would break backwards compatibility and that must be part of a new major release. At the moment I wouldn't be able to make a pull request for it, because it would immediately be part of the next minor version.

**Comment by sksamuel** [comment]
What I tend to do in all my projects is have master always be the "next
version", and as soon as anything is added that is major, I'll consider
that 1.(x+1).0 and further "bug fix" releases would go into a release
branch. See the branches on https://github.com/sksamuel/elastic4s. So
basically what I'm saying is, do your PR and if I need to go back and bug
fix 1.2.0 I'd make a release/1.2.x branch then from the 1.2.0 release tag.

**Comment by helmbold** [comment]
OK, then I will follow your *release branch on demand* approach and create a pull request on the master branch.

**Comment by helmbold** [comment]
I've just seen that features for 2.0.0 are now displayed on the front page (README.md). It think it would be a better separation to move future development to features branches.

**Comment by sksamuel** [comment]
Ok then, lets do it your way :)

**Comment by sksamuel** [comment]
So I will create release/1.3 which we can use for new features, which is
the way you mentioned. But I really don't want to call it 2.0 as we'll
rapidly iterate to 19.0 and although that might be the semver way, its not
common in JVM land - akka, kafka, elasticsearch, scala, kotlin, spark, etc.

**Comment by sksamuel** [comment]
Ok release/1.3 now contains the work you did and I've reset master back to
the 1.2.0 release.

**Comment by helmbold** [comment]
I thought your next features like property based testing would go to 1.3.0 and my changes would go to 2.0.0?

**Comment by sksamuel** [comment]
Any reason why yours can't go in 1.3.0? As I said, just about every other
jvm project does MASSIVE.MAJOR.MINOR

**Comment by helmbold** [comment]
It can't go into 1.3 because the method signature of `config` has changed. It is a breaking change which would require code changes by the users. We should mark such changes with new major versions. MASSIVE.MAJOR.MINOR is not useful. Lets use what is most useful, not what (some) others are doing for whatever reason ;-)

**Comment by sksamuel** [comment]
We agree that a breaking change is important. However what I'm saying is that basically every other project keeps the first number the same, unless its a complete re-write. The only example I can think of that is different is Guava. For example when you move between Scala or Spark versions sometimes there are breaking changes between x.y and x.y+1. I don't think changing the duration method is enough of a reason to warrant a complete bump to version 2.0, only a couple of months after 1.x came out - it indicates to me something far more important has happened.

That's just my viewpoint.

**Comment by helmbold** [comment]
The MASSIVE.MAJOR.MINOR scheme contradicts semantic version and the [Maven versioning scheme](https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN8855). From a library users perspective it is useful to distinguish breaking changes, new features with backwards compatiblity and bug fixes. Whether a breaking change is a complete rewrite or not is secondary. And since complete rewrites are rare, it is not worth to have a separate version number for it. If a complete rewrites happens, the users will read about it in the release notes and notice that it is breaking change anyway (since the major version changes).

I'd say that MASSIVE.MAJOR.MINOR is popular in the Scala world, whereas the MAJOR.MINOR.PATH scheme is popular in Java and many other programming languages.

**Comment by sksamuel** [comment]
Do you have examples of projects that bump the first number regularly? Off the top of my head, I can think of only Guava which is a tiny library. 

Frankly I don't disagree with what you're saying, I just think its better to stick with current JVM convention even if that's different to semver (I don't think semver is the ultimate authority on version numbers).

As another idea, what about if we renamed timeout to timeoutDuration (or other) and the other variables were kept and deprecated. Then nothing is a breaking change.

**Comment by helmbold** [comment]
There are many, many frameworks/libs that are using semantic versioning. Some of them have a low major version, because there weren't much breaking changes. Some examples:

- https://github.com/google/guice
- https://github.com/ReactiveX/RxJava
- http://hibernate.org/orm/
- https://github.com/Netflix/Hystrix
- https://commons.apache.org/
- http://joel-costigliola.github.io/assertj/
- http://www.jooq.org
- TestNG
- JUnit
- Log4j
- Spring Framework
- all parts of Java EE

I'm not sure whether we should introduce another parameter to `config`.  The idea is not bad, but from my point of view it would be sufficient to hold this change back unitl 2.0.0 gets released.

**Comment by sksamuel** [comment]
It seems like a small change to warrant a full release bump! What about if I could make overrides work, so it supports timeout for duration and timeout for int ?

**Comment by helmbold** [comment]
I would be fine with an overloaded method. We could deprecate the old method to give users some guidance and support backwards compatibility.

**Comment by sksamuel** [comment]
Yep.
