### ISSUE TITLE
Gradle build doesn't run the tests

### ISSUE THREAD

**Issue by NersesAM** [kotlintest/kotlintest#260]
`./gradlew test` doesn't run the tests. 

First as project uses Junit 5 gradle version needs to be bumped to 4.6 to support junit5 runner natively. I tried that but tests are still skipped 

I think its because we need to first build the code jar and run the tests using the jar so that Junit 5 service loader can pickup the KotlintestEngine from META-INF.

**Comment by sksamuel** [comment]
Note master is different to the latest 2.0.x releases.

**Comment by sksamuel** [comment]
Thanks for the feedback @NersesAM. It's running on master now.

**Comment by bondpp7** [comment]
Still seeing this in 3.0.0-RC2

**Comment by sksamuel** [comment]
What are you still seeing? Gradle not running the test?
It runs locally and on travis
https://travis-ci.org/kotlintest/kotlintest/builds/358268465
