### ISSUE TITLE
Additional dependencies using maven

### ISSUE THREAD

**Issue by AleksandrSl** [kotlintest/kotlintest#268]
I have a problem with version `3.0.0-RC2` with maven. 

My pom is:
https://gist.github.com/AleksandrSl/ca1ace1171b8cd907b87dd5d84f91758

From IntelliJ all tests run without problem.
However with `mvn test` command, tests are not found
```
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```

Addition of 
```
<plugin>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.19.1</version>
    <dependencies>
         <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-surefire-provider</artifactId>
            <version>${junit-platform.version}</version>
        </dependency>
    </dependencies>
</plugin>
```

which is needed for clean junit5 doesn't help.

**Comment by sksamuel** [comment]
Can you try adding the kotlintest-runner-junit5 dependency to that plugin block as well ?

**Comment by AleksandrSl** [comment]
The same result this way:
```
<plugin>
<artifactId>maven-surefire-plugin</artifactId>
<version>2.19.1</version>
<dependencies>
    <dependency>
        <groupId>org.junit.platform</groupId>
        <artifactId>junit-platform-surefire-provider</artifactId>
        <version>${junit-platform.version}</version>
    </dependency>
    <dependency>
        <groupId>io.kotlintest</groupId>
        <artifactId>kotlintest-runner-junit5</artifactId>
        <version>${kotlintest.version}</version>
    </dependency>
</dependencies>
</plugin>
```

**Comment by sksamuel** [comment]
Ok I'll add a sample maven project and get it to work.

**Comment by sksamuel** [comment]
It all works now, you need 3.0.0-RC3 and you need to setup your plugins like I have in this sample project.
https://github.com/kotlintest/kotlintest/blob/master/kotlintest-samples/kotlintest-samples-maven/pom.xml

Namely, put kotlintest-runner-junit5 on your classpath (test scope is fine) and add the junit surefire provider to the surefire plugin.

**Comment by AleksandrSl** [comment]
Thanks a lot!
