### ISSUE TITLE
improve test data generator

### ISSUE THREAD

**Issue by stalexxx** [kotlintest/kotlintest#270]
I have thought about improving Gen class by something powerfull, like flexible generators from clojure
https://github.com/clojure/test.check/blob/master/doc/intro.md (please see generators)
I feel like it should be separate module 
I've already start with some sketch https://github.com/stalexxx/sekuence. Is anybody onto this?

**Comment by sksamuel** [comment]
Did you see the changes to the Gen class in version 3? (on master). They now use sequences for the random values.

**Comment by stalexxx** [comment]
well, I see filter and map, but it is still work to do, like binding, advanced composition, smth like

```kotlin
data class User(var id: Int, var login: String, var email: String)
fun genUsers() = bind<User>(ints(1..100), names().fmap(String::toLowerCase), emails(strings())
```

**Comment by sksamuel** [comment]
For 3.1.0 lets expand this out to cover more use cases.

**Comment by sksamuel** [comment]
I've added flatMap, filterNot, and bind. You can do:

```
    data class FooC(val a: String, val b: Int, val c: Double)

    val gen = Gen.bind(Gen.string(), Gen.positiveIntegers(), Gen.double().filter { it > 0 }, ::FooC)

    assertAll(gen) {
      it.a shouldNotBe null
      it.b should beGreaterThan(0)
      it.c should gtd(0.0)
    }
```

**Comment by sksamuel** [comment]
This will be in release 3.1.0.
