### ISSUE TITLE
Test not found when run from gradle

### ISSUE THREAD

**Issue by bondpp7** [kotlintest/kotlintest#271]
Using Gradle 4.6 and KotlinTest 3.0.1, executing `gradlew clean test` returns a bunch of warnings from org.reflections, but does not run any tests.  When run using the junit runner within intellij, it works fine.

I'm currently trying to run a spring-boot integration test, shown below.  I've also listed my build.gradle for reference.

test class:
----

	@SpringBootTest
	class SampleRepositoryIntegrationSpec : BehaviorSpec() {

		override fun listeners(): List<TestListener> = listOf(SpringListener)

		@Autowired
		lateinit var repository: SampleRepository

		init {
			given("A valid instance of Sample") {
				val expected = Sample(comment = UUID.randomUUID().toString())

				When("it is persisted") {
					val persisted = repository.save(expected)

					then("a valid uuid has been generated") {
						persisted.uuid shouldNotBe null
					}

					When("it is queried by uuid") {
						val found = repository.findOne(persisted.uuid)

						then("is found") {
							found shouldNotBe null
							found.uuid shouldBe persisted.uuid
						}
					}
				}
			}
		}
	}

Build.gradle:
---

buildscript {
    ext {
        spring_boot_version = '1.5.10.RELEASE'
        spring_version = '4.3.14.RELEASE'
        kotlin_version = '1.2.31'
        junit_version = '5.1.0'
        junit_plugin_version = '1.1.0'        
        kotlin_test_version = '3.0.1'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.springframework.boot:spring-boot-gradle-plugin:$spring_boot_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-allopen:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-noarg:$kotlin_version"
        classpath "org.junit.platform:junit-platform-gradle-plugin:$junit_plugin_version"
    }
}

apply plugin: 'org.springframework.boot'
apply plugin: 'war'
apply plugin: 'java'
apply plugin: 'kotlin'
apply plugin: 'kotlin-spring'
apply plugin: 'kotlin-jpa'
apply plugin: 'org.junit.platform.gradle.plugin'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

configurations {
    providedRuntime
}

springBoot {
    buildInfo()
}

dependencies {
    //Kotlin
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

    //Load core spring-boot starters:
    compile "org.springframework.boot:spring-boot-starter:$spring_boot_version"
    compile "org.springframework:spring-web:$spring_version"

    //Load data-access dependencies:
    compile "org.springframework.boot:spring-boot-starter-data-jpa:$spring_boot_version"
    runtime 'mysql:mysql-connector-java'

    providedCompile "org.springframework.boot:spring-boot-starter-tomcat:$spring_boot_version"

    //Load test dependencies
    testCompile 'org.springframework:spring-context'
    testCompile 'org.springframework:spring-test'
    testCompile "org.springframework.boot:spring-boot-test:$spring_boot_version"

    testCompile "org.junit.platform:junit-platform-launcher:$junit_plugin_version"
    testCompile "org.junit.platform:junit-platform-runner:$junit_plugin_version"
    testCompile "io.kotlintest:kotlintest-runner-junit5:$kotlin_test_version"
    testCompile "io.kotlintest:kotlintest-extensions-spring:$kotlin_test_version"
}

compileKotlin {
    kotlinOptions.jvmTarget = java_version
}
compileTestKotlin {
    kotlinOptions.jvmTarget = java_version
}

bootRun {
    systemProperties["spring.profiles.active"] = System.properties["spring.profiles.active"] ?: "development"
}

test {
    useJUnitPlatform()
    systemProperties["spring.profiles.active"] = System.properties["spring.profiles.active"] ?: "test"
    testLogging {
        exceptionFormat = 'full'
    }
}

**Comment by bondpp7** [comment]
To keep it simple, I also added this dummy-test, which had the same results as my 'real' test:
` class MyTest : FunSpec({
    test("A test") {
        1 + 1 shouldBe 2
    }
}) `

**Comment by sksamuel** [comment]
That bug would break it but it was fixed i thought. I guess it's still
broken on windows. I'll try testing on windows somehow.

**Comment by bondpp7** [comment]
It's not the most efficient approach, but if you have changes you'd like tested, I'd be glad to help.

**Comment by sksamuel** [comment]
Ok that might help then. Can you clone the project, and change line 45 at ReflectionsHelper, so it should look like:

```
      val file = Paths.get(url.path).toFile()
      println("VFS FILE = $file")
      println("VFS FILE EXISTS = ${file.exists()}")
      println("VFS FILE LIST = ${file.list()}")
      return !file.exists() || file.list() == null || file.list().isEmpty()
```

Then just run the project with gradle test and when the error occurs can you give me the stack trace that includes the println.

**Comment by sksamuel** [comment]
Did you add the lines, just to confirm, as they're not in master.

**Comment by sksamuel** [comment]
Also you might need to do `gradle test -i`

**Comment by bondpp7** [comment]
I did add the lines, and re-ran with "-i".  Same (failed) result.

**Comment by sksamuel** [comment]
I get things like this in the log

```
VFS FILE = /usr/lib/jvm/java-8-oracle/jre/lib/ext/dnsns.jar
VFS FILE EXISTS = true
VFS FILE LIST = null
VFS FILE = /home/sam/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.2.30/2dfac33f8b4e92c9dd1422cd286834701a6f6d6/kotlin-stdlib-1.2.30.jar
VFS FILE EXISTS = true
VFS FILE LIST = null
VFS FILE = /home/sam/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-commons/1.1.0/d6aa21029f9cedfb4cc8a9e9efc0bd97987205b8/junit-platform-commons-1.1.0.jar
VFS FILE EXISTS = true
VFS FILE LIST = null
```

**Comment by sksamuel** [comment]
I've made a change on master, to the way it picks the files up which hopefully will be better on windows. Can you pull latest master and re-run ?

`git pull`
`git reset --hard origin/master`

**Comment by bondpp7** [comment]
Got the output, this time.  See attached.
[kotlintest-output.txt](https://github.com/kotlintest/kotlintest/files/1864521/kotlintest-output.txt)

**Comment by sksamuel** [comment]
Ok we can see the error now. Hopefully when you try latest mastet it should be fixed.

**Comment by bondpp7** [comment]
I can confirm the vfs error is gone and the tests now run.  Regrettably, they don't seem to be picking up the 'test' block from my build.gradle as normal tests would.  (I use that to set the 'active profile')

Relevant part of the build.gradle:

bootRun {
    systemProperties["spring.profiles.active"] = System.properties["spring.profiles.active"] ?: "development"
}

test {
    useJUnitPlatform()
//    // Always run tests, even when nothing changed.
//    dependsOn 'cleanTest'

    systemProperties["spring.profiles.active"] = System.properties["spring.profiles.active"] ?: "test"
    testLogging.showStandardStreams = true
    testLogging {
        exceptionFormat = 'full'
    }
}

**Comment by sksamuel** [comment]
Progress then.

What isn't being picked up? The `spring.profiles.active` property? Where/how would it surface?

**Comment by bondpp7** [comment]
Correct, the spring.profiles.active; it surfaces by pulling in the `application-test.properties` file to fill in configuration values; without that file, items such as database connection values are missing, and thus the tests fail.  This works with junit gradle-based testing.

**Comment by bondpp7** [comment]
I can also confirm that *both* the Junit-gradle plugin AND useJUnitPlatform() are required for the KotlinTest specs to be found and run.

**Comment by sksamuel** [comment]
Where is it used? Can you give me a simple example.

**Comment by bondpp7** [comment]
Sure.  I have a file in `src/test/resources` named `application-test.properties`.  Spring "knows" to use that file when the `spring.profiles.active` value matches `test`.  The contents of the file are:

spring.datasource.url=jdbc:mysql://localhost:3306/sample?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

**Comment by bondpp7** [comment]
I can get it to work by changing the filename to `application-default.properties`, which corresponds to the default profile, called (surprise) `default`.  When I use the renamed file, the settings are loaded and the tests run successfully.

**Comment by bondpp7** [comment]
The same thing can be achieved for junit test runner by setting the "VM Options" to `-ea -Dspring.profiles.active=test`

**Comment by sksamuel** [comment]
and you're using the spring extension for KotlinTest?

**Comment by bondpp7** [comment]
Yes.

    @SpringBootTest
    class SampleRepositoryIntegrationSpec : BehaviorSpec() {

      override fun listeners() = listOf(SpringListener)

      @Autowired
      lateinit var repository: SampleRepository

      init {
        given("A valid instance of Sample") {
            val expected = Sample(comment = UUID.randomUUID().toString())

**Comment by sksamuel** [comment]
Ok, so now we've moved onto a different problem, which is the spring listener doesn't use this system property.

The spring listener uses `org.springframework.test.context.TestContextManager`. I wonder if that just doesn't support those profiles? Because it's supposed to use an `@ContextConfiguration` on your test class.

**Comment by bondpp7** [comment]
I agree, this is a different issue that we were initially battling, and that the initial issue is resolved.  As a note, the `@SpringBootTest` provides the `@ContextConfiguration`

**Comment by sksamuel** [comment]
I can't see that inside SpringBootTest

**Comment by sksamuel** [comment]
From what I've just read you're supposed to put `spring.profiles.active=test` inside a file called `application.properties`.

**Comment by sksamuel** [comment]
Or you can use `@ActiveProfiles("test")`

**Comment by bondpp7** [comment]
Ugh, can't believe I forgot about `@ActiveProfiles("test")`; that works, for now.  It's a little messy as a final solution, but sufficient to allow me to keep working and using KotlinTest.  Thanks for all the help :)

**Comment by sksamuel** [comment]
Ok so I'll release 3.0.2 with the windows fix and you can use that.

**Comment by sksamuel** [comment]
3.0.2 has been released. Takes 15 minutes to show up at http://repo1.maven.org/maven2/io/kotlintest/ usually.

Thanks for your help in this issue.

**Comment by bondpp7** [comment]
I found why the 'active-profile' wasn't working.  It's nothing related to Kotlin-Test; when using Junit5 and spring-boot, JUnit5 w/ Gradle 4.6+ recommends using `useJUnitPlatform()` within the "test" task, rather than the (now obsolete) gradle-plugin.  Doing this means that `systemProperties["spring.profiles.active"]` must be set within JUnit's "junitPlatformTest" task, rather than the standard "test" task.  That was the root issue.

**Comment by sksamuel** [comment]
Aha, well thanks for coming back and updating the ticket.
