### ISSUE TITLE
Question: one instance per test with nested context

### ISSUE THREAD

**Issue by bbaldino** [kotlintest/kotlintest#280]
I know there's a blurb about why this was yanked in the changelog, but I'm loving being able to use nested contexts when describing my tests, and really missing the ability to have the established context reset between each test--I end up with a bunch of code trying to re-establish the state for a set of tests.  

Is there any hope of this returning?  It sounds like it wasn't that a single bug was hit so much that it affected the complexity quite a bit, but I'd be interested in playing around with re-adding this if you thought it was feasible.

**Comment by sksamuel** [comment]
It would be feasible to bring it back, but I'm just not sure the complexity - both from the point of view of kotlintest's internals, and from a user understanding how it would work - is worth it.

People will put init code inside each nested block, so then you have to selectively execute each closure that leads you down to the final test group. And what about when people put init code in between nested scopes.

```kotlin
class FreeSpecTest : AbstractFreeSpec() {

  var count = 0

  init {

    "a" - {

      count++

      "b1" - {

        count++

        "c" {
          count++
        }

        count++

        "d" {
          count++
        }
      }

      count++

      "b2" - {

        count++

        "c2" {
          count++
        }

        count++
      }

      count++
    }
  }
}
```

What's count after these tests execute if we supported one instance per test ?

**Comment by sksamuel** [comment]
I think a better approach might be to support some kind of custom context.

In scalatest you can do this:

```scala
trait Fixtures {
  val service = new Service
}

"my test" in new Fixtures {

}
```

And then you have access to all the variables inline. Maybe with Kotlin's more advanced function receivers something along these lines could be supported.

**Comment by bbaldino** [comment]
Hey thanks for the reply @sksamuel.  I of course don't know the code that well, but from what I looked at in `ShouldSpec` I thought you were doing most of the hard work already in that you build a stack of 'contexts' that lead up to a leaf (the test case itself), and because of the recursive nature of that each leaf's context would already have the pieces that should be executed leading up to that test.  But I'm probably misunderstanding something there.  Basically, the context for a given `should` should be the path of contexts established between the `should` and `init`.  

BUT, what you brought up that I didn't think about was the code placed after a given scope, I agree that does complicate things.  Logically you'd want it to evaluate as though it was running sequentially, but I'm guessing capturing the closures isn't going to work that way.  Is that case the thing you were referring to about the closures getting tricky?  If so I wonder if some more explicit syntax could be used to eliminate that case/make it clearer what would happen (like a `beforeEach` that could be added in a scope, for example)

As for the custom context, is that a single defined context that could be used by each test?  Would that support each test 'chain' having its own copy that it could modify independently?

**Comment by sksamuel** [comment]
Possibly it's worth trying to get nested contexts to work with single instance per test. But I yanked it because I wanted to release 3.0.0 as it was dragging on, and simplifying this use case meant the whole upgrade to junit 5 could be completed without much more work. I'm about to release 3.1.0 so I'm happy if you want to investigate either of the two possibilities outlined above (or another one) for 3.2.0.

**Comment by bbaldino** [comment]
Thanks @sksamuel, I'm still fairly new to Kotlin but I'll play with things a bit and report back here.

**Comment by sksamuel** [comment]
You'd need to change `KotlinTestEngine` or write an alternative implementation. It might be worth writing our own "runner" that executes `TestScope`s completely independently of junit platform, and communicates back to it via a listener of which JUnitPlatformListener could be an implementation. Effectively splitting the responsibility in half and making it easier to understand as well as do a Javascript one in the future.

**Comment by bbaldino** [comment]
@sksamuel I'm afraid I don't think I know the code well enough to follow your last few suggestions here, but I did play with this a bit and got something working (at least for a basic test case, and it doesn't appear to have broken anything else).  I've got in a branch [here](https://github.com/bbaldino/kotlintest/tree/with_context).  

Basically I added a 'beforeEach' method inside of AbstractShouldSpec and ShouldContext which allows some code to be put on a 'stack' for a TestContext.  I added a new test to [ShouldSpecTest](https://github.com/bbaldino/kotlintest/blob/with_context/kotlintest-tests/src/test/kotlin/io/kotlintest/specs/ShouldSpecTest.kt#L19) to show it.

[AbstractShouldSpec](https://github.com/bbaldino/kotlintest/blob/with_context/kotlintest-core/src/main/kotlin/io/kotlintest/specs/AbstractShouldSpec.kt) has a couple changes to handle the beforeEach calls, accumulating them as the tree is built, and then executing them before the test.

For all I know this is a terrible way of implementing this, but it was at least something I could get my head around and gets at the general idea: you can tell me how misguided it might be.

**Comment by sksamuel** [comment]
We can work with the stack idea. On issue I've ran into myself is that when you define a testcase, you can do this:

"test case" {
  // test logic
}.config(...)

Now the config method is called on the result of the "create test scope" method, but the create test scope method should start the execution of the test.

So maybe we can't support allowing test cases with initialization logic between them. The only thing we could do there is to suppor hoisting.

**Comment by bbaldino** [comment]
can you elaborate on the scenario you're referring to there? i don't think i followed what you're saying.

**Comment by LimmaPaulus** [comment]
`People will put init code inside each nested block, so then you have to selectively execute each closure that leads you down to the final test group. And what about when people put init code in between nested scopes.`

Maybe it should be just stated that one should not add code between nested scopes. Or even better if it could be prevented syntactically. I see it counter-intuitive and needless to do so.

Single instance per test would be essential feature to implement fundamental principle of unit testing which statest that "Tests should not affect each other". Of course one can implement anything what for example JUnit can do with non-nested context styles, but I think that real awesomeness of KotlinTest comes from ability to use shared initialization code between tests. But it requires that tests would not interfere each other.

**Comment by bbaldino** [comment]
For me the main appeal of nested scopes is being able to re-use code that lives in the nested scope.  Otherwise, nested scopes are just saving you a bit of copy-pasting in a test's name.  I think saving copy-pasting of code required to get into a certain state is a lot more valuable.

**Comment by LimmaPaulus** [comment]
Sorry, I expressed my idea very unclearly. So of course this is the core idea of nested context and should be supported:
```
class Test : FreeSpec() {
    init {
        "on situation A" - {
            setupSituationA()
            "it should work"{

            }
            "it should work again"{

            }
        }
    }
}
```

But this, I think, makes code execution order unclear for user and I can guess it would be hard to implement:

```
class Test : FreeSpec() {
    init {
        "when" - {
            setupSituationA()
            "on situation A it should work"{

            }
            setupSituationB()
            "on situation B it should work too"{

            }
        }
    }
}
```

So would it be possible that user could be able set only one initialization block per context, and after that only test blocks?

Something like that:

```
class Test : FreeSpec() {
    init {
        "when" - (
            initialize{
                initialSetup()
            },
            "on situation A" -(
                initialize {
                    setupSituationA()
                },
                "it should work"{

                },
                "it should work again"{

                })
            })
        }
    }
}
```

So that arguments of String.minus-function would be optional initialization block made by some initialize-function and then vararg count of test blocks. Something like this:
   
` infix operator fun String.minus(init: FreeSpecContext.() -> ReturnTypeOfInitialize_function, vararg testCases : TestContext.() -> Unit)`

**Comment by bbaldino** [comment]
Ah! I understand now.  Yeah this is what I did in the branch I created (mentioned in a previous post above)...except I called it 'beforeEach' and didn't do anything to explicitly prevent code elsewhere in the block (which may be a good idea).

**Comment by sksamuel** [comment]
The first example @LimmaPaulus posted is doable in KT3.2 I think.
The second example is the best, and _would_ be possible, except for the fact you can currently configure tests like so:

```kotlin
"my test" {
 // test
}.config(threads=5, enabled=true,...)
```

Which means that the `config` function is called on the `TestCase` object returned by the `"string" {}` function. This means that the string function must be allowed to return before the test is executed, otherwise the config function will set config on an already executed test.

Which ultimately means that the second example can't work, because all the intermingled code will have executed while we are setting up (delaying) the tests to allow `config` to work. 

I hope that makes sense (and was the answer to your question last week @bbaldino but I was away in Japan).

The last example @LimmaPaulus posted means changing the syntax somewhat, and whilst we could do that (with FreeSpec2 say), I'm more in favour of just allowing the code directly in the blocks (example 1).

**Comment by bbaldino** [comment]
@sksamuel agree that being able to just embed the code in the block would be the nicest, but as we talked about earlier it can also lead to confusing scenarios (code can be placed anywhere in that block, can we really guarantee it executes in the order that the user will expect? e.g.:
```
"my test" {
    "when A happens" {
        doSetupA();
    }
    should("have a side effect from a") {
        // test
    }
    otherSetupCode(); // Can we ensure this won't run before the test case above?
}
```
so I thought that was out.  Adding the explicit 'initialize/beforeEach' isn't as convenient from a syntax perspective, but it does limit what can be done (in a good way) to make it less likely a user writes code expecting it to be run at a certain time and then confused when it isn't?

**Comment by sksamuel** [comment]
I suppose having the `beforeEach`/`init` means users will not be surprised that it doesn't run "where they want" but on the other hand it's nicer to just be able to put your code without another nested block. Either of these options are the same in implementation time and complexity so it's really a matter of preference which we go with.

As for your code snippet, if we didn't have the `config` function issue, then yes, we could guarantee things would run in order. This is because the execution of the outer scope would stop while the inner scope ran, and so on recursively.

**Comment by bbaldino** [comment]
> As for your code snippet, if we didn't have the config function issue, then yes, we could guarantee things would run in order. This is because the execution of the outer scope would stop while the inner scope ran, and so on recursively.

If the config problem were gone and it was done this way, would it also allow for one-instance-per-test for nested-scope specs?

**Comment by sksamuel** [comment]
Hmm, when a test was discovered, instead of executing it, it would have to start a new execution, which would execute the closures up to that point. I think it could work but there's no telling if I run into some implementation issue when doing it.

**Comment by bbaldino** [comment]
I see...well I care less about one-instance-per-test specifically, it's more about making sure the chain of initialization logic is all run once per test.  If that's the case then I can reset things appropriately and get a similar effect to one-instance-per-test.

**Comment by sksamuel** [comment]
Yes, the challenge now is to come up with alternative config syntax.

**Comment by bbaldino** [comment]
> We could make the second example work if we changed the way config was set on tests. But we can't use annotations here as they won't work on a function call. So would have to have some new syntax like
> 
> ```
> "my test" with config(threads=3,...) {
>  }
> ```
> But not with as it's a keyword.

These feel like somewhat lame/misguided attempts, but I did tinker with this a bit.  I'm not quite sure all the places `.config(...)` can be called, but first I tried:

```
infix fun String.using(config: TestCaseConfig) {
   // need a TestCase to apply the config to
}
```
In order to try and get to the
```
"my test" using config(...)
```
syntax, but we don't necessarily have access to a TestCase here (maybe that means that config can't be applied here anyway though?).  It seems like maybe could go this route, but may have to hold on to the config somehow and trickle it down to places where it would need to be applied to an actual TestCase?

Then I tried
```
infix fun TestCase.using(config: TestCaseConfig): TestCase {
    this.config = config
    return this
}
```
In an effort to be able to do something like:
```
should("remove the last element from stack") using config {
```
But this doesn't work, as the `should` expects the second argument to be the function directly, so the infix just gets in the way.  This did make me wonder, what about changing every function that returns a `TestCase` (which you can call `config(...)` on), to take an optional config argument like:

```
should("remove the last element from stack", config) {
   ...
}
``` 
?

**Comment by sksamuel** [comment]
The last example works fine for things lile should ("") and given ("") bit
wont work on strings (stringspec and freespec)

**Comment by sksamuel** [comment]
I believe `"this test".config(...) {  }` will work quite well. Now the issue is how to deprecate cleanly. I don't want to break things since 3.x has just been released.

**Comment by bbaldino** [comment]
Awesome!  Looks like it ended up being pretty usable, syntax-wise.

**Comment by sksamuel** [comment]
Syntax wise it's not bad. I just need to implement the test engine now to make sure it actually works!
And then I need to decide.... do we introduce this breaking change or not.

**Comment by LimmaPaulus** [comment]
I would really encourage you to do it @sksamuel. KotlinTest has already lots of users, but I think it has potential to grow to really big player. I can't see why anybody would continue using traditional test-per-method style if KotlinTest can become mature library. Breaking changes are better to do now than in the future. I think this is something that many people will request in future too, although I personally would be happy with single initialization block per context. But of course it is better if you really could implement this.

Maybe config-sections are still pretty rarely used, aren't they? I also think that it is a bit more logical if configuration is written before the test than after it.

**Comment by sksamuel** [comment]
What do you think @helmbold

**Comment by sksamuel** [comment]
I've pushed a change in the newconfig branch, which supports the preferred syntax from this discussion. After the config changes I made, this means that each nested scope can mutate variables as desired and all it hangs together.

This won't work with one instance per test, and I think that's not possible to support with nested contexts in this way.

I've added some tests which show this working in full glory for various spec types:

https://github.com/kotlintest/kotlintest/blob/newconfig/kotlintest-tests/src/test/kotlin/com/sksamuel/kotlintest/tests/specs/FreeSpecLambdaTest.kt

https://github.com/kotlintest/kotlintest/blob/newconfig/kotlintest-tests/src/test/kotlin/com/sksamuel/kotlintest/tests/specs/BehaviorSpecLambdaTest.kt

https://github.com/kotlintest/kotlintest/blob/newconfig/kotlintest-tests/src/test/kotlin/com/sksamuel/kotlintest/tests/specs/WordSpecLambdaTest.kt

I would appreciate feedback from anyone and everyone :)

**Comment by bbaldino** [comment]
Hey @sksamuel , thanks for the work on this.  Although I do think this is a nice improvement, I know for my use cases the real value is in all "parent" context code chunks being executed once for each test (whether this is the one-instance-per-test method, or the `beforeEach` context chain run for every test method doesn't matter to me, either would be fine).

**Comment by sksamuel** [comment]
```kotlin
var name = ""
"some context" {
  name = "sam"
  "should be sam" {
    name.shouldBe("sam")
  }
  name = "tom" 
  "should be tom" {
    name.shouldBe("tom")
  }
}
```

That's what we need to support and what this branch provides. 

If we do that as one instance per test, then we need to execute the `"some context" {}` scope twice (on two spec instances) in order to get access to the nested test scopes. But both times they are executed the name will be changed to "sam" and then to "tom".

**Comment by sksamuel** [comment]
Paste up a simple example where a shared instance would not work please. It might give me some ideas. @bbaldino

**Comment by LimmaPaulus** [comment]
Thanks for your effort @sksamuel!

I encountered this problem with shared instances:

```  
var service = mock<SomeService>()
    "some context" - {
        initializeSomethingWhichCallsService()
        "should call service exactly once"{
            verify(service, times(1)).someMethod()
            //fails
        }
    }
    "another contex" - {
        initializeSomethingWhichCallsService()
        "should again call service exactly once"{
            verify(service, times(1)).someMethod()
            //fails
        }
    }
```

So because mocks are shared, it is very hard to verify calls. It would be dirty to to clear invocations every time, and it is also not recommended in documentation of Mockito.

**Comment by bbaldino** [comment]
> I have it working, with a couple of tests to fix, and assuming I've not overlooked something.
> 
> This should be what you want.
> 
> https://github.com/kotlintest/kotlintest/blob/newconfig/kotlintest-tests/src/test/kotlin/com/sksamuel/kotlintest/tests/specs/FreeSpecOneInstanceTest.kt
> 
> https://github.com/kotlintest/kotlintest/blob/newconfig/kotlintest-tests/src/test/kotlin/com/sksamuel/kotlintest/tests/specs/WordSpecOneInstanceTest.kt

That's awesome!  Does this mean it will be able to be applied to all spec types?  Or just some?

**Comment by LimmaPaulus** [comment]
Perfect! I tested it a bit and it really looks excellent! That's just what I wanted.
I will no longer consider other testing frameworks for my future projects :)

**Comment by sksamuel** [comment]
@bbaldino It will work on them all.

Running multiple invocations of a parent scope may break things though.

"parent context".config(invocations = 5) {
  "some test" {
  }
}

**Comment by sksamuel** [comment]
@LimmaPaulus are you building from source?

**Comment by LimmaPaulus** [comment]
Yes, I just tried a bit tests which you had written. Execution order etc. seemed to be quite logical for me.

**Comment by bbaldino** [comment]
Trying to give this a try in my actual repo to write some more complex tests, but I'm having trouble building the jar.  `gradle build` gives me:

```
A problem occurred evaluating project ':kotlintest-tests'.
> Could not find method useJUnitPlatform() for arguments [] on task ':kotlintest-tests:test' of type org.gradle.api.tasks.testing.Test.
```

**Comment by sksamuel** [comment]
You need gradle 4.6 or use ./gradlew

**Comment by bbaldino** [comment]
@sksamuel thanks, I had tried ./gradew before but `./gradelw build` tries to sign it seems like:
```
* What went wrong:
Execution failed for task ':signArchives'.
> Unable to retrieve secret key from key ring file '/Users/bbaldino/work/kotlintest/xx' as it does not exist
```
and `./gradlew jar` doesn't seem to do much, maybe I just don't know which target to use.

**Comment by sksamuel** [comment]
Are you trying to build the jar for local use ?
Try `gradle publishToMavenLocal`.

**Comment by bbaldino** [comment]
> Are you trying to build the jar for local use ?
> Try ./gradlew publishToMavenLocal.

Right in front of me all along.  Thanks.

**Comment by sksamuel** [comment]
@bbaldino what we need now are more test cases to ensure this works properly. More examples of tricky cases that are missed by the **OneInstance tests I added.

**Comment by bbaldino** [comment]
@sksamuel I was testing out `ShouldSpec`, but noticed the `final override fun isInstancePerTest(): Boolean = false` was still in there, is that just left in by mistake/haven't gotten to it yet?  I removed it and did a test similar to `WordSpecOneInstanceTest` (setting isInstancePerTest to `true`) and it looks good.  Haven't tried anything trickier yet.

**Comment by LimmaPaulus** [comment]
I have also problems with generating .jar. Tried `./gradlew publishToMavenLocal`, but it creates only empty jar with manifest to /build/libs

**Comment by sksamuel** [comment]
I've released 3.1.0-RC3 which has the one instance per test working on all specs.

**Comment by bbaldino** [comment]
@sksamuel awesome!  thanks for the great work on this, i started re-writing some tests with a local build of 3.1.0-RC3 last week and being able to have this flow feels really nice.  it's enabling me to get some good code re-use setting up more complex cases.

**Comment by sksamuel** [comment]
I would switch to the maven central version because it's been tricky to get this all to work and I have just finished it today. There were some annoying issues whereby intellij and gradle both have differing opinions on how to work with junit platform and getting KotlinTest to work with both has proven tiresome (but I think we are there now).

**Comment by bbaldino** [comment]
Sounds good, I'll move to that.

**Comment by sksamuel** [comment]
There's some large changes under the hood, so it may need some more tweaks to get it ready for 3.1.0, but fingers crossed that it's ok.

**Comment by sksamuel** [comment]
If there's no further issue with one instance and all specs we can close this ticket. RC4 is now released.

**Comment by sksamuel** [comment]
3.1.0 final is now released. Please re-open if further issues on this.
