### ISSUE TITLE
ProjectConfig.beforeAll() not called before initialization

### ISSUE THREAD

**Issue by LimmaPaulus** [kotlintest/kotlintest#289]
Hi!

I'm using test class like following

```
class Tests : FreeSpec(){
   init{
        initializationWhichRequiresProjectConfigBeforeAllBeingCalled();
        "test something"{
            execute()
            assert()
        }
    }
}
```
It seems that ProjectConfig.beforeAll is called after all initialization is happened, so in this case just before execute(). However, in my case I need to run configuration before any test code (my particular problem is [this](https://medium.com/pxhouse/unit-testing-with-mutablelivedata-22b3283a7819)).

For workaround I created base class for tests which calls configuration code in the beginning of init-block. However, I would see it more intuitive if configuration was called automatically.

**Comment by sksamuel** [comment]
I think we can change it so that before all is called before the spec classes are initialized.

**Comment by LimmaPaulus** [comment]
Great! Thanks!

**Comment by sksamuel** [comment]
3.0.4 has been released with this change.
