### ISSUE TITLE
The test discovery in kotlintest 3 should not get confused by global objects

### ISSUE THREAD

**Issue by sschuberth** [kotlintest/kotlintest#294]
Currently, a global class definition like `internal object Resources` seems to confuse kotlintest's test discovery and test are skipped. This should not be the case.

**Comment by sksamuel** [comment]
Fixed on master. I'll be releasing 3.0.4 and 3.1.0-rc2 later

**Comment by sksamuel** [comment]
3.0.4 released with this fix.
