### ISSUE TITLE
Make Assertions integrate with IntelliJ

### ISSUE THREAD

**Issue by JohannesRudolph** [kotlintest/kotlintest#296]
Using a plain `assertEquals` from JUnit gets special treatment by intelliJ in the form of a special rendering and a `<Click to see difference>` comparison failure window (with nice diff) in the test output window. 

As far as I recall this behavior merely hinges on a specific formatting of the assertion message.

It would be great if kotlintest would output its assertion messages in the required format so that we can leverage this feature.

**Comment by sksamuel** [comment]
Turns out it was broken completely in 3.0.0
I've fixed and released 3.0.5
