### ISSUE TITLE
Nested initialization code getting called on all tests

### ISSUE THREAD

**Issue by LimmaPaulus** [kotlintest/kotlintest#297]
I really love the ability reuse initialization code with FreeSpec. Consider following tests
```
class MyTests : FreeSpec(){

    init {
        val thermometer = mock<Thermometer>()

        "when it is cold"-{
            (1) whenever(thermometer.isCold).thenReturn(true)
            
            "increase heating"{
                (3) assertIncreasedHeating()
            }
            "turn fan off"{
                assertFanTurnedOff()
            }
        }

        "when it is not cold"-{
            (2) whenever(thermometer.isCold).thenReturn(false)

            "test something"{
                assertSomething()
            }
            "test something else"{
                assertSomethingElse()
            }
        }
    }
```

When I debug execution of test "increase heating", I see that line (2) is executed after line (1) and then line (3), which of course causes test to fail.  This makes this fantastic ability to reuse common initialization code useless in many cases. I don't know if this is related to #280, but I would love to see this working properly.

**Comment by sksamuel** [comment]
Which version are you using?

**Comment by sksamuel** [comment]
Please try 3.0.4

**Comment by LimmaPaulus** [comment]
It works on 3.0.4, great :). Thanks!

**Comment by sksamuel** [comment]
Excellent

On 20 Apr 2018 22:51, "LimmaPaulus" <notifications@github.com> wrote:

It works on 3.0.4, great :). Thanks!

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/kotlintest/kotlintest/issues/297#issuecomment-383102578>,
or mute the thread

**Comment by bbaldino** [comment]
@sksamuel i'm surprised this works in 3.0.4, did something change there with regards to code execution outside of a designated 'test'-type block?  i thought code outside of tests was executed during discovery?

**Comment by sksamuel** [comment]
In 3.0.0 nested scopes are executed "at the right time" not all at once like in 2.x
But you'll get a shared test instance for all tests, whereas in issue #280 you want a new instance per test _and_ nested tests.

**Comment by sksamuel** [comment]
In 3.0.0 nested scopes are executed "at the right time" not all at once like in 2.x
But you'll get a shared test instance for all tests, whereas in issue #280 you want a new instance per test _and_ nested tests. @bbaldino
