### ISSUE TITLE
Kotlintest 3 with jUnit 4.

### ISSUE THREAD

**Issue by psa-anddev** [kotlintest/kotlintest#299]
I was wondering how can I update to Kotlintest 3 (from 2.7) and use it with jUnit 4. The documentation only talks about its use with jUnit 5. Has the support for jUnit 4 been dropped or is it still possible to use kotlintest with it?

**Comment by sksamuel** [comment]
KotlinTest 3.x is junit5 only. What's the use case for junit4 compatibility?

**Comment by psa-anddev** [comment]
I first came to this library because Spek decided to move to jUnit 5 and stop supporting jUnit 4. After having tested this library for a while, I think I like this library better. I believe it is too soon to drop the support for jUnit 4. And, as a matter of fact, if this is done properly, this library can extend other realms by providing an easy way to support other runners.

Firstly, jUnit 5 has just come out and although Gradle, Maven and other build systems offer support for it, there are some situations that the use of jUnit 5 is difficult. 
 I like to work in many areas but my primary work is as an Android developer. In Android, jUnit 5 can be used but, in my experience, setting it up is difficult and even using it, sometimes, you have no other option than using the vintage runner to run, for instance, Robolectric tests. I think Kotlintest would be in a position of advantage by keeping jUnit 4 support now that Google has endorsed Kotlin. I think people would prefer to use this library over Spek if jUnit 4 support was not dropped. 

Supporting jUnit 4 and jUnit 5 at the same time could be a way to make this library grow. By abstracting the runner, support for other runners could be added and, eventually, this library could be compiled to Javascript or even to native. 

If you are open to that idea, I could try to write some code in order to bring jUnit 4 support back to the library. 

Anyway, it's up to you guys.

**Comment by sksamuel** [comment]
Thanks for the detailed feedback. The runner is already abstracted so in theory we can add other implementations.

I think the only thing that would be a problem with junit4 is whether it allows tests to be added at runtime, rather than up front. That's a good feature of junit5 that makes the nested scopes possible.

**Comment by sksamuel** [comment]
I've added a junit 4 runner for kotlintest 3.1 with some caveats.

1. The test output in intellij will be flat and not nested
2. Project.beforeAll and Project.afterAll can't work because in junit 4 the framework creates a new runner each time.

**Comment by psa-anddev** [comment]
That's great! I've taken a casual look to the jUnit 4's documentation. I think the runner can be made nested by using ParentRunner as the base class for the kotlintest runner. The second problem (beforeAll and afterAll) could probably be solved if we turn them into a jUnit 4 class rule. 

If it's ok with you, I'm going to take a look and see if I can tackle these problems. If I am able to solve them, I will create a PR for it.

**Comment by sksamuel** [comment]
Ok please do have a play. Even if you don't manage to solve it all, any advancement would be useful. The beforeall/afterall problem will go away if a single runner instance can be used for all specs.

**Comment by helmbold** [comment]
Sadly I don't have much time at the moment to contribute, but I still plan to unify the interceptors on the project level so that all tests can be intercepted in the same way as a singele test case and as far as I know from my experiences with the old Junit 4 implementation it is impossible to do that with JUnit 4, since there is nothing that would represent all tests in a project. I don't think that an abstraction of the test runner can hide this fact.

**Comment by sksamuel** [comment]
For 3.1 I actually am working on unifying the "test containers" with "test cases" so that every closure is treated the same way, in that a test can nest a test. Then everything is unified.

**Comment by nibuen** [comment]
3.1.0-RC4 Working great for us on Android! Thanks for this.

**Comment by sksamuel** [comment]
Good to know @nibuen.
3.1.0 final is now released. Closing ticket.

**Comment by sksamuel** [comment]
As an aside, I competed the work to unify tests. So every scope is now an instance of `TestCase` so there's no difference between "parent" scopes and "the actual tests". Makes the code simpler and allows interception on any level in the tree.
