### ISSUE TITLE
3.1.0-RC1 failing to discover all tests

### ISSUE THREAD

**Issue by martinlau** [kotlintest/kotlintest#300]
Running under maven, I have a test suite with 37 tests across 14 classes (all green when running under 3.0.4). When upgrading to 3.1.0-RC1 that drops to 9 tests in 1 class (again all green).

The class that is selected seems somewhat arbitrary (it's not the first or last lexicographically, deepest of shallowest by package depth, etc) but it is consistent (it's always the same class across multiple tests).

I suspect (haven't confirmed) this results from the change introduced in KotlinTestEngine via https://github.com/kotlintest/kotlintest/commit/fefe597ea599d2e96261df93d559e786602b33e2#diff-461861632c0613d6e9375e66399a366d - where the result of discover() is cached once per engine, but that caching doesn't take into account whether parameters provided to `discover()` have changed between calls.

**Comment by sksamuel** [comment]
I think this is fixe in master and should be ok for rc2. I'm about to fly
from Narita to Heathrow so I'll check and do a release in 12 hours or so.

**Comment by sksamuel** [comment]
And I believe you're right in that it was the caching between requests.

**Comment by martinlau** [comment]
Awesome, thanks @sksamuel.

**Comment by sksamuel** [comment]
Do you want to try 3.1.0-RC2

Of course 3.0.6 is available if you don't want to use snapshots.

@elect86 @martinlau

**Comment by martinlau** [comment]
All good now, thanks @sksamuel.
