### ISSUE TITLE
Interceptors are deprecated and sometimes removed but are still in the documentation

### ISSUE THREAD

**Issue by msesma** [kotlintest/kotlintest#303]
Interceptors are deprecated and sometimes removed as stated in the change log: https://github.com/kotlintest/kotlintest/blob/master/CHANGELOG.md

But they are still explained as the only way of executing code before or after a test in the documentation:
https://github.com/kotlintest/kotlintest/blob/master/doc/reference.md#intercepting-a-test-case

Moreover, the documentation says nothing about `beforeTest` and `afterTest` listener methods.

**Comment by sksamuel** [comment]
Yes you're quite right, I've been slow in updating the docs.
I'll update them next day or so.

**Comment by sksamuel** [comment]
I've updated the documentation to cover listeners now.

**Comment by stephenjfox** [comment]
Can I open a PR to delete that bit of documentation, then?

**Comment by sksamuel** [comment]
Yes please.

**Comment by stephenjfox** [comment]
Opened under #347

**Comment by stephenjfox** [comment]
Open under #376
