### ISSUE TITLE
Alllow mixing of property forAll with table forAll

### ISSUE THREAD

**Issue by sksamuel** [kotlintest/kotlintest#311]
Currently the functions are in different packages and shadow each other.

See #310

**Comment by russel** [comment]
The following appears to be a viable workaround for the moment:
```kotlin
import io.kotlintest.properties.forAll
import io.kotlintest.tables.forAll as tableForAll
```

**Comment by sksamuel** [comment]
Yes that'll do the trick. I'd like to make it seemless though - putting them all in the same file would work.

**Comment by sksamuel** [comment]
3.1.0 final is now released. In this version, forAll has been aliased to verifyAll so they can be combined that way, or by renaming the import as you did.

**Comment by russel** [comment]
@sksamuel Do both `io.kotlintest.properties.forAll` and `io.kotlintest.tables.forAll` have `verifyAll` aliases?

**Comment by russel** [comment]
Works a treat, thank you.

**Comment by sksamuel** [comment]
Following on from this, and after looking at table tests again after merging @ajalt pr #349 I've added another variant of table driven tests. This new variant is more like spock, and does away with the need to specify the table header, instead, the header names are _inferred_ from the function parameter names.

So, in this example:

```kotlin
    "square roots" {
      forall(
          row(2, 4),
          row(3, 9),
          row(4, 16),
          row(5, 55)
      ) { root, square ->
        root * root shouldBe square
      }
    }
```

If there was an error, it would tally up the names automatically. 5 is not the sqrt of 55, so it outputs ```Test failed for (root, 5), (square, 55) with error expected: 55 but was: 25```. The header names are picked up using reflection.
