### ISSUE TITLE
Wrong title for WordSpec tests

### ISSUE THREAD

**Issue by sschuberth** [kotlintest/kotlintest#312]
I still see a minor issue in the test report with WordSpec tests and kotlintest 3.1.0-RC2: The class name includes the name of the first test. See e.g.

![image](https://user-images.githubusercontent.com/349154/39257313-81a5a568-48b1-11e8-8461-7176ff365046.png)

"mapTimeoutErrors()" should not be there as that's the first test. In exchange, when clicking on the link to go to the tests, I see

![image](https://user-images.githubusercontent.com/349154/39257422-c0dee10e-48b1-11e8-928b-44915fa16054.png)

Here, the "ScanCodeTest" prefix should be stripped as that's the class name, not the test name.

See [here](https://github.com/heremaps/oss-review-toolkit/blob/2cc0d2c/scanner/src/test/kotlin/ScanCodeTest.kt#L29) for the test class code.

**Comment by sksamuel** [comment]
I wonder if this is related to the fix I did for gradle to work without the plugin. I need to make a standalone junit platform engine which does nothing but generate 2 unit tests to see if I can recreate the hanging outside of KT.

**Comment by sschuberth** [comment]
Hanging? Which hanging?

**Comment by sksamuel** [comment]
In < 3.1.0 if you don't use the gradle junit5 plugin then it would hang.

**Comment by sksamuel** [comment]
https://github.com/kotlintest/kotlintest/issues/279

**Comment by sksamuel** [comment]
This is something to do with the way the sources are reported back to junit I think.

**Comment by sksamuel** [comment]
@sschuberth what are you using to generate the html report ?

**Comment by sksamuel** [comment]
Never mind I've found it.

It seems with the latest code base that the class names are generated properly. But with specs that allow nested contexts, such as WordSpec, the report is going to include the parent context names all muddled up with leaf tests names. We could flatten out the names, but nested contexts can still contain initialisation logic as well as assertions themselves, so they need to appear as a test result. 

Really gradle needs to understand that junit can have hierarchy tests.

**Comment by bondpp7** [comment]
JUnit5 supports "nested" tests; do those output as desired?  I'd be okay with the flattened names, as a stop-gap.

**Comment by sksamuel** [comment]
@sschuberth Can you try 3.1.0-RC3 see what your results are like now.

**Comment by sschuberth** [comment]
Another thing I've been asking myself is whether the word "should" should actually be moved to the outer context, and not be repeated as a prefix for each test. For once that would shorten the test descriptions a bit (which can get long) and secondly that would more match how tests are defined in the source code, where the "should" keyword is also on the line of the outer context, not before each test.

**Comment by sksamuel** [comment]
Interesting. I guess I did it the way ScalaTest did it (the original source of inspiration).

**Comment by sksamuel** [comment]
Test added for the original issue.

https://github.com/kotlintest/kotlintest/blob/master/kotlintest-tests/kotlintest-tests-junit-report/src/test/kotlin/com/sksamuel/kotlintest/tests/JUnitXMLReportTest.kt

**Comment by sksamuel** [comment]
Anyone else got an opinion on whether we should change this. Personally I think it's a good idea.

@helmbold

**Comment by sksamuel** [comment]
I had a little play.

![screenshot_2018-05-10_09-08-40](https://user-images.githubusercontent.com/743706/39859471-e314dd24-5431-11e8-87f0-332605ed1e99.png)

**Comment by sksamuel** [comment]
@sschuberth can you confirm issue is fixed in 3.1.0-RC4 and we can close this ticket.

**Comment by sschuberth** [comment]
I'll hopefully able to confirm this on Monday.

**Comment by sksamuel** [comment]
3.1.0 is now released so closing this ticket. Please re-open if any issues.

PS. @sschuberth I changed the word spec to put should on the parent line, like you suggested. This is also the way scala test does it.
