### ISSUE TITLE
Custom generator for property-based testing

### ISSUE THREAD

**Issue by russel** [kotlintest/kotlintest#313]
https://github.com/kotlintest/kotlintest/blob/master/doc/reference.md gives the example:
```kotlin
data class Person(val name: String, val age: Int)
class PersonGenerator : Gen<Person> {
    override fun always() = emptyList<Person>()
    override fun random() = generateSequence {
        Person(Gen.string().random().first(), Gen.int().random().first())
    }
}
```
but following this example with Kotlintest 3.1.0 reports that `always` is not a method in the interface `Gen`, and that `constants` is not defined. Is it just that the documentation is for 3.0.x and this is a breaking change for 3.1.x?

**Comment by sksamuel** [comment]
Yes I'll fix the docs and add a deprecated migration method.

**Comment by sksamuel** [comment]
Docs updated
