### ISSUE TITLE
StringSpec produces errors when run with spring-boot thymeleaf dependency in Intellij Idea

### ISSUE THREAD

**Issue by TheNewBob** [kotlintest/kotlintest#314]
In short, a test with StringSpec produces a gazillion errors if you have spring-boot-starter-thymeleaf in your dependencies. You don't have to actually *use* it, just have the dependency in the project.

Here is a minimal project setup that will reproduce the issue in IntelliJ IDEA when you run the included test. Reproduction instructions are there also, as well as in the links further below:
https://github.com/TheNewBob/kotlin-test-thymeleaf

I have asked about the issue on [stackoverflow](https://stackoverflow.com/questions/49941784/intellij-thymeleaf-freaking-out-on-kotlintest). Somebody recommended to report the issue to Jetbrains, [which I did](https://youtrack.jetbrains.com/issue/KT-23971), and they concluded that the source of the problem is most likely in kotlintest. It seems a bit strange, since the problem does not happen when doing gradlew test instead of running it in Intellij.

**Comment by sksamuel** [comment]
Which version of KotlinTest are you using ?

**Comment by sksamuel** [comment]
Thanks I'll take a look at this now.

**Comment by sksamuel** [comment]
There's no such dependency as `testCompile 'io.kotlintest:kotlintest:3.0.6'`.

**Comment by sksamuel** [comment]
It seems ok if you change the dependency to:

`testCompile 'io.kotlintest:kotlintest-runner-junit5:3.0.6'`

And add in 

`apply plugin: 'org.junit.platform.gradle.plugin'`

And in the buildscript add

`classpath "org.junit.platform:junit-platform-gradle-plugin:1.1.0"`

The upcoming 3.1.0 release will simplify this if you use gradle 4.6+

**Comment by TheNewBob** [comment]
> There's no such dependency as testCompile 'io.kotlintest:kotlintest:3.0.6'.
Really sorry about that. I was running 2.0.7 before writing the issue report, realised there was a new version and just updated the version number and tested. For some reason the test ran, probably wasn't done rebuilding yet.

Looks like just pulling 'io.kotlintest:kotlintest-runner-junit5:3.0.6' fixes the issue now that I get around to trying again.

**Comment by sksamuel** [comment]
The error you were getting was definitely something that happened in version 2 so yes I think this issue is fixed by just upgrading. I'll close.
