### ISSUE TITLE
A simple `assert(false)` test does not fail `gradle test`

### ISSUE THREAD

**Issue by Sushisource** [kotlintest/kotlintest#318]
Just set up a brand new project and created this simple test:

```kotlin
import io.kotlintest.specs.ExpectSpec

class SomeTest : ExpectSpec() {
    init {
        context("Foo") {
            expect("bar") {
                println("!!!")
                assert(false)
            }
        }
    }
}
```

The `!!!` gets printed, so I know it's running, but `gradle test` happily passes. Running it from IntelliJ fails as expected.

My gradle file only contains the suggested inclusions from the README.

Adding a 

```
false shouldBe true
```

Makes the test fail as expected, so the problem seems to be ignoring asserts, which is very unexpected.

**Comment by sksamuel** [comment]
Which version ?

**Comment by Sushisource** [comment]
This is 3.1.0-RC2

**Comment by sksamuel** [comment]
Did you enable assertions?
From the `assert` docs:

``` * Throws an [AssertionError] if the [value] is false
 * and runtime assertions have been enabled on the JVM using the *-ea* JVM option.```

That's because `assert` is a built in java thing. It's not part of KotlinTest per say. You could use the kotlintest matchers as well, things like `name shouldBe "foo"`

**Comment by Sushisource** [comment]
Ah, ok, that clears things up. I think I was just mixing up bare asserts and junit asserts (which do fail tests as expected, as well).
