### ISSUE TITLE
StringSpec

### ISSUE THREAD

**Issue by sksamuel** [kotlintest/kotlintest#32]
Was thinking of adding a new spec, called `StringSpec` which just requires a single string, eg,

```kotlin
"haveKey should test that a map has a key" {
        val map = mapOf(Pair(1, "a"), Pair(2, "b"))
        map should haveValue("a")
}
```

Wdyt @helmbold

**Comment by helmbold** [comment]
I like it! It is clean and simple, a piece of beauty.

**Comment by sksamuel** [comment]
I'll add it tonight then.

**Comment by sksamuel** [comment]
It might become my preferred way of testing actually

**Comment by lenguyenthanh** [comment]
It looks awesome

**Comment by helmbold** [comment]
It could become my favourite style, too!

**Comment by sksamuel** [comment]
This is in on the 1.3 branch. See changelog in that branch.

**Comment by helmbold** [comment]
Awesome! I'll add the style to the documentation.
