### ISSUE TITLE
Add ability to execute async code inside spec

### ISSUE THREAD

**Issue by imanushin** [kotlintest/kotlintest#323]
For current moment only sync code is allowed under specs (under FreeSpec as example)

To execute async code you should to write something like this:

```
"my code should work in async mode" {
            runBlocking {
                executeSomethingAsCoroutine(123)
            }
        }
```

However, for my opinion, it is better to allow execution async code here too, e.g. it is better to add overload for invoke method:

```
  infix operator fun String.invoke(test: /*change is here -->*/suspend/*<--*/ TestContext.() -> Unit) =
      addTestCase(this, test, defaultTestCaseConfig)
```

Then test code can be simplified:

```
"my code should work in async mode" {
                executeSomethingAsCoroutine(123)
        }
```

**Comment by sksamuel** [comment]
This is merged into master now.
