### ISSUE TITLE
Remove unnecessary interfaces

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#33]
Some interfaces exist only to hold concrete methods. In languages like Java and Scala this is necessary, but [Kotlin supports top level functions](https://kotlinlang.org/docs/reference/functions.html#function-scope), so this code can be slightly reduced by removing the interfaces.

The following interfaces could be removed: Inspectors, Eventually, CollectionMatchers, ExceptionMatchers, IntMatchers, LongMatchers, MapMatchers, StringMatchers, TypeMatchers. This would be a breaking change.

**Comment by sksamuel** [comment]
Would it be a breaking change? Is that becausr they'd need to add an
import?

**Comment by helmbold** [comment]
Yes, the code on the user site would have to be changed due to the required imports.

**Comment by sksamuel** [comment]
Is there anyway you can inherit imports in Kotlin?

**Comment by helmbold** [comment]
At least I'm not aware of such a possibility. But you could place the functions to be inherited in interfaces and add them to the test base class :-D

**Comment by sksamuel** [comment]
I only did it as interfaces because I like them to be in scope automatically, and because its quite "scalay". I've been a Scala developer for 5 years at work, and I haven't touched Java since, so a lot of my opinions are influenced by that.

**Comment by helmbold** [comment]
When I was writing this issue, I haven't thought of the convenience aspect. I think it is ok, to just close this ticket.
