### ISSUE TITLE
Running tests on custom source sets seems to be broken in 3.1.0

### ISSUE THREAD

**Issue by sschuberth** [kotlintest/kotlintest#330]
In [ORT](https://github.com/heremaps/oss-review-toolkit) we've created a custom [funTest source set](https://github.com/heremaps/oss-review-toolkit/blob/master/build.gradle#L45) with a custom [funTest task](https://github.com/heremaps/oss-review-toolkit/blob/master/build.gradle#L107) to run functional tests. Running these with `./gradlew funTest` works fine in `master` with [kotlintest 2.0.7](https://github.com/heremaps/oss-review-toolkit/blob/master/gradle.properties#L6). However, in my [PR which ports to kotlintest 3.1.0](https://github.com/heremaps/oss-review-toolkit/pull/505) we see that those [functional tests are not being executed at all](https://ci.appveyor.com/project/heremaps/oss-review-toolkit/build/1.0.2543/tests), but only the unit tests are. Compare also the total number of tests of 128 which [should be 200](https://ci.appveyor.com/project/heremaps/oss-review-toolkit/build/1.0.2552/tests).

**Comment by sksamuel** [comment]
I suspect this is more of an issue with junit5 in gradle than anything else. I'll search around.

**Comment by sksamuel** [comment]
Does this SO link solve the issue ?
https://stackoverflow.com/questions/45297339/junit-5-under-gradle-with-multiple-source-sets

**Comment by sschuberth** [comment]
It does, thank you!

**Comment by sksamuel** [comment]
Awesome :)

**Comment by sksamuel** [comment]
I'll add something to the readme (or you can?) if you tell me which of the answers was the correct one.

**Comment by sschuberth** [comment]
> [...] which of the answers was the correct one.

[Mine](https://stackoverflow.com/a/50331660/1127485), that I just added ;-) But basically I was just refining [this answer](https://stackoverflow.com/a/48965756/1127485).
