### ISSUE TITLE
Incorrect test count

### ISSUE THREAD

**Issue by bbaldino** [kotlintest/kotlintest#335]
I notice that the passed/failed count I see when running isn't what I expect, for example in the following test file:

```
class TestCountTest : ShouldSpec() {
    override fun isInstancePerTest(): Boolean = true

    init {
        "section a" {
            "when b happens" {
                should("test 1") {
                    true shouldBe true
                }
                should("test 2") {
                    true shouldBe true
                }
            }
            "when c happens" {
                should("test 3") {
                    true shouldBe true
                }
            }
        }
        "section b" {
            "when d happens" {
                should("test 4") {
                    true shouldBe true
                }
            }
        }
    }
}
```
I'd expect there to be 4 tests, but when it runs it actually shows 9 and I can't figure out what's getting counted as a test and what isn't to explain how it's arriving at 9.  Is this a bug?  Or is it due to some limitation?  It isn't the _worst_ thing to overcount the tests, what does feel a bit worse is that if one fails, it shows up as multiple failing (3 in the case of the example above).

**Comment by sksamuel** [comment]
What is happening is that each context is considered a test. So the "section a" is a test, in addition to the nested "when b happens". This means you end up with a higher test count than you otherwise would.

The reason it does this is because free spec allows arbitrary nesting, so there is no obvious way to detect leaf nodes, but now I think about it I suppose for the other specs it could be "fixed".

**Comment by bbaldino** [comment]
Gotcha.  Yeah would be nice for the ones that could support it.

**Comment by sksamuel** [comment]
I've applied the changes I can and I'm not sure it's much better. See what you think in 3.1.5.

**Comment by sksamuel** [comment]
Did you get chance to check @bbaldino

**Comment by bbaldino** [comment]
Sorry I forgot to respond.  I just checked and yeah it does look better!  Thanks!
