### ISSUE TITLE
Bring back Duration extension properties

### ISSUE THREAD

**Issue by michalbrz** [kotlintest/kotlintest#343]
I was trying to use samples from docs and some of them use extension properties for `java.time.Duration` like `2.seconds`. The problem is, these extensions were removed two months ago: https://github.com/kotlintest/kotlintest/commit/84e3eec6d68a9022263f933c9367902c7f52f786  
There is nothing about that in commit description so it could possibly be a mistake? And if not, then docs should be updated to reflect that. I could do that but important question is: do we want to have `Duration` extensions back? I personally think they were nice so I hope they can be brought back.

**Comment by sksamuel** [comment]
They're back in latest release 3.1.5

**Comment by michalbrz** [comment]
Great, thank you!
