### ISSUE TITLE
`forAll(items) { x -> if(true) throw NullPointerException()` passes successfully!!!

### ISSUE THREAD

**Issue by iirekm** [kotlintest/kotlintest#353]

**Comment by iirekm** [comment]
the reason is that some exceptions (like NPE) have null message, and the library uses exception message to detect it there was exception at all

**Comment by sksamuel** [comment]
You're quite right, this line here: `val passed = results.filter { it.second == null }` is erroneous. Will fix and release 3.1.7.

**Comment by sksamuel** [comment]
This is fixed in master.

**Comment by sksamuel** [comment]
3.1.7 is now released with this fix.
