### ISSUE TITLE
Move tables and data packages into kotlintest-assertions package

### ISSUE THREAD

**Issue by ajalt** [kotlintest/kotlintest#354]
For people who use kotlintest's assertions with the regular JUnit test runner, being able to import just `kotlintest-assertions` is very helpful. The `table` and `data` packages are both currently in the `kotlintest-core` package. I think it would make sense to move them to the assertions package, since they don't depend on the other classes in `core`.

**Comment by sksamuel** [comment]
Actually I suppose they can go in assertions. You can add that module if you want tables/data and you don't have to use the matchers. They don't add much to the jar and have no deps.

**Comment by ajalt** [comment]
I agree. Property testing is already in the assertions module. Since property and table testing are pretty similar in scope, I think that it would make sense for them to be in the same module.

**Comment by sksamuel** [comment]
Moved.
