### ISSUE TITLE
No info about a thrown exception from a code running inside 'given' or 'when' block.

### ISSUE THREAD

**Issue by just-4-fun** [kotlintest/kotlintest#355]
Let's run that test. Here I expect some info about an exception thrown by the 'boom' function in the console. But what I see is a passed test with an orange symbol like this (-). I'm using IntelliJIdea + Kotlin.

```
fun boom() = 1 / 0

class TestBoom: BehaviorSpec() {
	init {
		Given("Test") {
			boom()
			When("running here a code that potentially throws an exception") {
				Then("no info about that exception") {
					1 shouldBe 1
				}
			}
		}
	}
}
```

Is it possible to somehow configure the framework to make it report such exceptions?

**Comment by sksamuel** [comment]
What version are you using? In the latest (master branch) I see that the Given block fails, but the actual Spec passes (which I will change if possible).

![image](https://user-images.githubusercontent.com/743706/41192807-b59f2b56-6bfb-11e8-98dc-9d9d5946aad2.png)

**Comment by just-4-fun** [comment]
I was using the 3.0.4
Now with 3.1.6, I have a correct behavior, i.e. the framework reports the exception.
Thanks
