### ISSUE TITLE
Running single tests with Gradle command line does not work

### ISSUE THREAD

**Issue by sschuberth** [kotlintest/kotlintest#356]
Running just a single test does not work when running from the command line. To reproduce, use kotlintest's own current `master` (65cd9d03b52e9936904a2d55d5087a0bcc4c86fd) and run:

    ./gradlew test --tests io.kotlintest.extensions.system.SystemExitTest

It will run all tests instead of just `io.kotlintest.extensions.system.SystemExitTest`.

**Comment by sksamuel** [comment]
Gradle 4.7 ?

**Comment by sschuberth** [comment]
No, you are using Gradle 4.6 in kotlintest 😉 See https://github.com/kotlintest/kotlintest/blob/65cd9d03b52e9936904a2d55d5087a0bcc4c86fd/gradle/wrapper/gradle-wrapper.properties.

**Comment by sksamuel** [comment]
lol I thought I had upgraded it.

**Comment by sksamuel** [comment]
It looks like --tests is not passed through to the JUnit 5 test runner, but only used by Gradle's junit 4 scanner.

**Comment by sksamuel** [comment]
I've opened an issue at gradle.
https://github.com/gradle/gradle/issues/5678

**Comment by sksamuel** [comment]
I've made some progress with the workaround I talked about in the gradle ticket. On master now, we can do --tests com.test.Class but it will fail if there is no match. It will also fail the build if there's a multi modules, as it will match in one module and not in another.

I think for the latter, we could either, if no classes match the pattern then we test all classes. This will fix the multi module issue, but will mean if you do a typo then you'll run everything. Thoughts @sschuberth

**Comment by sschuberth** [comment]
> On master now, we can do --tests com.test.Class but it will fail if there is no match.

I like that it fails it that case. While vanilla Gradle's runs all tests in that case, [I do consider that to be a bug](https://github.com/gradle/gradle/issues/5688).

> It will also fail the build if there's a multi modules, as it will match in one module and not in another.

But what if there's only one unique match throughout all modules? Would it still fail?

**Comment by sksamuel** [comment]
Yes it would because it treats each module in isolation. That's the
annoying part.

**Comment by sksamuel** [comment]
You can of course use the :project-name:test syntax to narrow down to the
submodule. Then it will work.

**Comment by sschuberth** [comment]
> You can of course use the :project-name:test syntax to narrow down to the submodule.

Ah, right. I'd say that's good enough then.

**Comment by sksamuel** [comment]
You can try in 3.1.7 and hopefully tell me it's ok :)

**Comment by sschuberth** [comment]
Confirmed to be working, thanks!
