### ISSUE TITLE
Add shouldContainExactly() to Collections matchers

### ISSUE THREAD

**Issue by bartboes** [kotlintest/kotlintest#361]
Please add `shouldContainExactly()` to Collections matchers which is already implemented for Maps.
Please also consider `shouldContainExactlyInOrder()` or an equivalent feature.

**Comment by sksamuel** [comment]
Would `shouldContainExactlyInOrder` be the same as contains a sublist ?

**Comment by ajalt** [comment]
I already added these in #360, so they'll be in the next version.

**Comment by sksamuel** [comment]
I'll release 3.1.7 once I move the co-routine stuff out to a new module. Unless I'm being to it by a PR :)

**Comment by sksamuel** [comment]
3.1.7 is now released.
