### ISSUE TITLE
intellij always executes StringSpec tests

### ISSUE THREAD

**Issue by jillesvangurp** [kotlintest/kotlintest#367]
I have a non kotlin-test unit test (junit 5) that I'm trying to run with ctrl+shift+r. When that runs a StringSpec test that I have also executes. This is unexpected. It seems that the test runner in intellij always picks it up.

Given these two tests.

```
import io.kotlintest.specs.StringSpec

class FooTest : StringSpec({
    "should_not_run" {
        println("but it does")
    }
})
```

```
import org.junit.jupiter.api.Test

class BarTest {
    @Test
    fun shouldOnlyRunThis() {
        println("test")
    }
}
```

When I run shouldOnlyRunThis with ctrl+shift+r, FooTest (and any StringSpec tests) also execute.

**Comment by sksamuel** [comment]
What versions of junit, intellij, and kotlintest are you using in your build so I can duplicate.

**Comment by jillesvangurp** [comment]
Gradle 4.8 wrapper, intellij 2018.1.5, `testCompile "io.kotlintest:kotlintest-runner-junit5:3.1.6"`

**Comment by jillesvangurp** [comment]
Yes confirmed. It seems to run all StringSpec tests in the project when you run the test method but not when you run the class.

**Comment by sksamuel** [comment]
Thanks, fixed in master. I'll be releasing 3.1.8 shortly.
