### ISSUE TITLE
Support shrinking in property-based testing

### ISSUE THREAD

**Issue by russel** [kotlintest/kotlintest#37]
QuickCheck and Hypothesis, and all good variants of these, support shrinking: whenever an error occurs in a property test, a chop search is undertaken to find the smallest value from the set that exhibits the failure. Does KotlinTest do this? If not can it be added to the agenda for fairly quick implementation. Property-based testing frameworks are evaluated on supporting domain sampling based on static type, ability to specify bizarre generators, and shrinking.

**Comment by sksamuel** [comment]
I've never heard of this feature before but it sounds absolutely fantastic. I'd make excellent use of it myself. It's definitely going on on the list.

**Comment by sksamuel** [comment]
How does this work in other frameworks, if I'm testing ints say, I would generate 100 random ints and try those. If there is a failure, do you just output the smallest one that fails from the sample of 100 ?

**Comment by superbobry** [comment]
Here's a [relevant piece of code](https://github.com/HypothesisWorks/hypothesis-python/blob/master/src/hypothesis/internal/conjecture/minimizer.py) from `hypothesis`.

I guess for integers you could try bisecting, starting from the smallest failure.

**Comment by russel** [comment]
Although not always done, it is possible to use bisection as a way of creating equivalence classes, i.e. to do equivalence partitioning, and report that. Currently though it is generally assumed that all values above the smallest fail are failures. Thus if there is a fail the do bisection between the smallest fail and the largest pass smaller than the fail. Of course this assumes a total order. For things without even a partial order. In that case, shrinkage is not really possible.

**Comment by superbobry** [comment]
On a slightly unrelated point: another very cool feature of hypothesis is example database. When re-running tests after a failure it first tries previously found counter-examples.

**Comment by dimsuz** [comment]
Swift's implementation SwiftCheck also support shrinking in property based tests, maybe it can also be used as a reference/inspiration: 

https://github.com/typelift/SwiftCheck#shrinking

**Comment by sksamuel** [comment]
I wonder how to do it. If a test fails for 700837 but passed for 0 do you do a binary search for the first failure. What if the first failure was Int.Min.

**Comment by thimes** [comment]
If the test fails for 700837, but passed for 0, @russel had said you then try 350418, then continue bisecting from there. I'd think that if the first failure was Int.Min, you'd never have had a success, and could just report that Int.Min fails.

**Comment by sksamuel** [comment]
Ok so that seems like it could work for ints/longs etc. Not much you could do with strings I suppose. 

There's also the cases where you have more than one parameter. If a 5 parameter test fails for (15, Int.MAX, 0, -1 and "hello"), how do you shrink that down. Maybe shrinking is just limited to single input tests.

**Comment by thimes** [comment]
Yeah, unsure with strings. I would suggest that if you strongly want to implement this, support Numbers, and then support anything that provides an implementation of an interface, make the caller implement the details for anything beyond `Number`s?

**Comment by sksamuel** [comment]
Basic shrinking has been added to master for release in 3.1.
Currently supports ints and strings in any combinations.

**Comment by sksamuel** [comment]
Now supports doubles and choose. Closing this ticket, will be part of the 3.1 release candidate when I publish it.
