### ISSUE TITLE
`shouldFail` &c. in WordSpec

### ISSUE THREAD

**Issue by outis** [kotlintest/kotlintest#382]
Please consider adding `shouldFail` and the various `shouldThrow[...]` functions to `WordSpec` as infix `String` functions, as `should` currently is. The presence of `String.should` in `WordSpec` suggests the existence of the others. Also, their lack leads to unwieldy DSL expressions:

    import io.kotlintest.shouldBe
    import io.kotlintest.specs.WordSpec
    
    class MathTest: WordSpec({
        "wrong assertions" should {
            shouldFail {
                1 shouldBe 2
            }
        }
    })

I tried adding them myself, but couldn't figure out how to have them call the existing functions, given both the current project structure (`AbstractWordSpec` in kotlintest-core and the functions in question in kotlintest-assertions) and Kotlin's lack of support for extending inner extensions (i.e. multiple extension receivers, e.g. `infix fun AbstractWordSpec.String.shouldFail(...`).

**Comment by sksamuel** [comment]
Should is defined there so that it doesn't clash with the keyword of the DSL.
Otherwise you can't do this

```kotlin
"my test" should {
  a should exist()
}
```

So you want something like

```kotlin
"my test" shouldFail {
 ...
}
```

But that is conflating the should of the spec DSL with should as a matcher.

**Comment by outis** [comment]
I hadn't examined the source when creating this issue, and hadn't noticed the inner description strings (`WordSpec.WordScope.String.invoke()`), which addresses the unwieldy expression aspect.

This issue originally came about when creating tests for matchers. Using inner description strings, information gets duplicated between them and tests that should fail or throw, which has development costs. The cost is small per test, but with a large number of tests gains significance. Would a spec (named e.g. PassFailSpec) with DSL terms supporting  be of use to others? If so, I could take a shot at it. Use would be:
```
"something" should {
    succeed("for some things") { ... }
    fail("for others") { "a".shouldBe("b") /* note: no `shouldFail` */ }
    abort<IndexOutOfBoundsException>("when exceeding its capacity") { ... }
    "do something more complex in certain circumstances" { ... }
}
```

`throw` could be added as an alias for `abort` (I went with `abort` as it's not a keyword). It could also potentially support non-nested terms:
```
"something" should succeed("for some things") { ... }
"something else" should fail("all the time") { ... }
"" should abort<NoSuchElementException>("when ") { ... }
```

Implementing the DSL methods is straight-forward; what's not so clear is dealing with the cross-project nature (as specs are in core and the exception handling matchers are in assertions). Should I pursue designing this further?

**Comment by sksamuel** [comment]
I see what you're saying. You want to combine naming the test with the fail / pass / exception semantics.

I guess when testing the framework itself it would be handy, but when acting as a user of the framework, instead of saying

```kotlin
"string length" should {
  shouldThrow {
    "string".shouldHaveLength(3)
  }
}
```

You would say

```kotlin
"string length" should {
  "string.shouldNotHaveLength(3)
}
```

Also in this case, the usage of _should_ is just particular to `WordSpec`. The other specs have their own nomenclature, eg for `StringSpec`:

```kotlin
"string length" {
  shouldThrow {
    "string".shouldHaveLength(3)
  }
}
```

I am in favour of anything that improves the experience for the user, but you do have the issue of the multiple project modules (assertions vs core, and there are plenty of people who only use one or the other).

What might be nice is finding some generic way to do this, so that

```kotlin
"my test" shouldThrow {
  "string".shouldHaveLength(3)
}
```

could be used in any spec, and then you could also expand this idea out to other things like table driven tests, or property tests, so they don't have to be nested inside test cases anymore, but can themselves form test cases.

**Comment by outis** [comment]
I may think about this one more. What inspired this (and what is more useful to me and, I suspect, in general) is supporting matchers on `Sequence`. I'll finish that up first (simply putting the useful extension methods in the test class).

**Comment by Kerooker** [comment]
@sksamuel 
I'm revisiting old issues that were never closed/solved.

Do you think we should support this?

**Comment by sksamuel** [comment]
I'm all in favour of improvements, but I'd have to see a concrete design before being able to offer an opinion.

**Comment by Kerooker** [comment]
I believe what could be done is something like this

```
"Foo.execute" shouldThrow<InvalidBarException> {
            "When I try to pass Bar=12" {
                foo.execute(12)
            }
            
            "When I try to pass Bar=16" {
                foo.execute(16)
            }
        }
```

For these kind of wording, it's very fluid to read, and wouldn't be very far from the original intend of the `should` keyword in `WordSpec`, as it still writes `Foo should "BAR"`, but with an extra possibility

**Comment by Kerooker** [comment]
Or something like

```
"Collect info from the database" shouldThrow<EmptyDatabaseException> {
    "When the database is empty" {
         emptyDatabase()
         database.getInfo() // This line will throw the exception, therefore succeeding the test
    }
}

```


It would be exactly the same as

```
"Collect info from the database" should {
    "Throw an EmptyDatabaseException when the database is empty" {
        emptyDatabase()
        shouldThrow<EmptyDatabaseException> { database.getInfo() } 
    }
}
```

**Comment by sksamuel** [comment]
It's adding specific syntax for a very small use case imo.
What about if someone wants the same thing to check if something is true, or > 10.
At the end of the day:

```
test("Collect info from the database should throw when db is empty"  {
  shouldThrow<EmptyDatabaseException> {
         emptyDatabase()
         database.getInfo() // This line will throw the exception, therefore succeeding the test
    }
}
```

Is just as good ?

**Comment by sksamuel** [comment]
If it could work in a spec-neutral way then I'd probably be more in favour but this kind of design only works for word spec. I'd not vote in favour of seeing one spec become more powerful than the others.

**Comment by Kerooker** [comment]
I don't see a problem in different specs working in different ways, as long as you can do everything in all of them.

`AnnotationSpec`, for example, is getting a lot of buffs recently, but all that can be done with it is also doable with any other spec. Expecting exceptions, for example.

If it's something only appliable to `WordSpec`, it's ok... Is there a way to do it in `StringSpec`? Yes. It's just written differently.

**Comment by Kerooker** [comment]
And `shouldThrow` is not that small use case. As we did with `AnnotationSpec` due to JUnit, and implemented `shouldThrow` due to more people needing it, verifying that a certain piece of code throws an exception is a very important scenario. If we can make it less verbose, I'd say we should go for it.

**Comment by Kerooker** [comment]
I'm trying to imagine that if you have 10 scenarios which you want to throw an exception, you'd have to nest 10 additional `{}` in WordSpec, and the tests will get less readable

**Comment by Kerooker** [comment]
It's different from `shouldBeTrue` and `shouldBeBiggerThan10`, because an exception is a very generic use case. Any piece of code can throw it, and it's not returned (Like a true or false), so it can be used for more use cases than a `shouldBeTrue`, which would only work for scenarios that return booleans

**Comment by sksamuel** [comment]
I think annotation spec is the odd cousin, because I don't think anyone would "choose" to use it. I created that as a way of migrating from junit with less hassle. All new tests, you are likely to pick another style right?

Can you come up with a proposal for the other specs?

**Comment by Kerooker** [comment]
I'd never use annotation spec, but maybe someone wants to? Not my business :P

Maybe we can find a way of doing this in some of the other specs, but for instance, in `BehaviorSpec` it wouldn't be possible. What would it be? `ThenThrows<FooException>("The calculator calculates")` It wouldn't be as fluid as for `WordSpec`, but we can still use `shouldThrow` there

**Comment by Kerooker** [comment]
My point is that it's ok for specs to be a little bit different

**Comment by sksamuel** [comment]
Yes you've persuaded me that specs can be different but I would like to see a "bit" of consistency.

**Comment by Kerooker** [comment]
Maybe with what we discussed here, this syntax may be applied to `WordSpec` and perhaps `ShouldSpec` ?

```
shouldThrow<EmptyDatabaseException>("when collecting values from an empty database") {
     emptyDatabase()
    database.getData()
}
```

**Comment by sksamuel** [comment]
Also need to bear in mind clashes with the the existin shouldThrow
functions.

**Comment by LeoColman** [comment]
This discussion was never followed up by the original author, and we didn't really see a big improvement with this.

Should this need rise again in the future, we may discuss it again. For now, I'll close this.
