### ISSUE TITLE
Upgrade to Kotlin 1.3 and enable co-routines 

### ISSUE THREAD

**Issue by sksamuel** [kotlintest/kotlintest#386]

**Comment by imanushin** [comment]
Is this issue related to #323 ?

**Comment by sksamuel** [comment]
Yep.

**Comment by imanushin** [comment]
@sksamuel , at least one requirement is - add ability to call [async](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.experimental/async.html) method from test. This is quite useful for cases when you need to execute two parallel tasks.

async method is just extension for [coroutineScope](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.experimental/-coroutine-scope/index.html), so there are the following options to support this:

Option 1: do nothing, however to create async invocation you have to code something like this:

```
"test" {
  coroutineScope {
       async { ... }
  }
}
```

Option 2: implement CoroutineScope in the TestContext. For example - all methods should just delegate result to the inner context (for example - blocking context). Then async method can be called simpler:

```
"test" {
  async { ... } // because TestContext inherits CoroutineScope 
}
```

Option 3: add coroutineContext property into the TestContext. This option is the same with option 2, however coroutineContext will be public here. Async method call will be:

```
"test" {
  coroutineContext.async { ... }
}
```

**Comment by sksamuel** [comment]
Thanks for the info @imanushin. I'll take a look at an implementation for kotlintest 3.2, at the moment I don't know much about coroutines so now they're going final, I'm eager to learn.

**Comment by imanushin** [comment]
Looks like kotlin 1.3 is released - https://blog.jetbrains.com/kotlin/2018/10/kotlin-1-3/
