### ISSUE TITLE
Kotlintest runner spews DEBUG logs by default

### ISSUE THREAD

**Issue by docent** [kotlintest/kotlintest#394]
Hi there, I'm running my StringSpec from IDEA and I noticed a lot of DEBUG messages coming from kotlintest package. Is there any reason this is why these are on by default? I don't think it's desirable that they are - it distracts from test output, and I don't remember such behavior among other test runners. I believe they should be off by default.

**Comment by sksamuel** [comment]
Do you have DEBUG logging enabled for all namespaces?

**Comment by docent** [comment]
@sksamuel I haven't enabled anything, but it seems it was Spring Boot's fault, they somehow configure it to be DEBUG by default. Apologies - I'm closing the issue.

**Comment by sksamuel** [comment]
No problem. I might change it to TRACE so it's harder to enable it by accident.
