### ISSUE TITLE
Code coverage report configuration in Gradle

### ISSUE THREAD

**Issue by pwittchen** [kotlintest/kotlintest#398]
Hi,

Thanks for the nice library!

Do you have any suggestions or examples showing how can I configure `kotlintest` in Gradle in order to generate test coverage reports with Jacoco (or any other tool)? It would be nice to have an example both for pure Kotlin app and Android app. Honestly, I had problems with configuring it for Kotlin project on Android with regular JUnit tests even without your library, but I'm hoping you encountered similar issue and maybe solved it during library development :-).

Regards,
Piotr

**Comment by pwittchen** [comment]
Ok, I managed to generate unit test coverage report in Kotlin Android project with pure JUnit tests. You can check this commit: https://github.com/pwittchen/RxBattery/commit/3942d5df296aea34261c67d55fbb610e42605c8f. I tried to apply the same approach in another project using `kotlintest`, but it didn't work, so now I have issues only with `kotlintest`.

**Comment by Kerooker** [comment]
Hi!
I'm sorry for the very late response. I'm revisiting old issues now and didn't see this one.

I also use Jacoco as a test coverage tool, and I use KotlinTest. Maybe something is different on our ends?

Would you please try with the new version and see if it's working?

**Comment by LeoColman** [comment]
Closing this issue for now. If you're still having troubles, please let us know.

**Comment by notquiteamonad** [comment]
@Kerooker I seem to be unable to generate reports with jacoco in my repo with KotlinTest - I wonder if you could have a look at what might be causing the issue? https://github.com/samueldple/datetimekt/blob/coverage/pom.xml

**EDIT:** Sorry - I was making a really silly mistake - please ignore this. Pom will be pushed to above repo if anyone else needs an example.

**Comment by LeoColman** [comment]
It's fine xD
