### ISSUE TITLE
Consider @AutoCleanup

### ISSUE THREAD

**Issue by sksamuel** [kotlintest/kotlintest#40]

**Comment by helmbold** [comment]
Do you want to do it with an annotation? Maybe a usual function would do the job:

```kotlin
class MyTests : ShouldSpec() {
  init {

    // 1. register single variable
    val somethingCloseable = ...
    autoClose(somethingCloseable)

    val somethingElse = ...

    val closeMe = ...

    // 2. register multiple variables
    autoClose(somethingCloseable, somethingElse, closeMe)

    should("return the length of the string") {
      ...
    }
  }
}
```

However, when used with fields, an annotation could be more handy.

But what common interface should the variables to be closed share? [AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html) was introduced with Java 7, and KotlinTest should be usable by Android devs still using Java 6.

**Comment by sksamuel** [comment]
I thought [Closeable](https://docs.oracle.com/javase/8/docs/api/java/io/Closeable.html) which most stuff implements as well as AutoCloseable. In fact, does anything only implement the latter?

**Comment by helmbold** [comment]
It seems like all JDK classes that implement `AutoCloseable` are also implementing `Closeable`. So `Closeable` should be ok.

I have another idea for my function based approach:

```kotlin
val somethingCloseable = autoClose(SomethingCloseable())
```
This function (or actually a method, but in Kotlin everything is called function) would only return the reference and register it for auto closing.

```kotlin
class Spec {
    
    private val closeables = ArrayList<Closeable>()
    
    fun <A: Closeable> autoClose(closeable: A): A {
	    closeables.add(closeable)
        return closeable
    }
    
    // ... close resources
}
```

**Comment by helmbold** [comment]
You could assign this ticket to me, and I'll happily add my suggestion to KotlinTest.

**Comment by sksamuel** [comment]
Can't seem to assign to you. I tried adding you to the project and you still don't appear in the list.

**Comment by helmbold** [comment]
I had to accept the invitation first (didn't know this).

**Comment by sksamuel** [comment]
Ok worked now

**Comment by helmbold** [comment]
Thanks!

**Comment by helmbold** [comment]
I wonder when `close()` should be called. [Spock seems to distinguish fields and local variables](http://ldaley.com/post/3133819681/spocks-autocleanup-feature):

> Automatically cleans up the object stored in the annotated field or property at the end of its life time. More precisely, auto-cleanup of an object has the same effect as, and serves as a convenient replacement for, calling the object’s close method at the end of the spec’s cleanup method. @Shared objects are cleaned up at the end of the spec’s cleanupSpec method.

Calling `close` on shared fields (if all tests are executed with a single test class instance) would be impossible after each test case. But if we need to distinguish local variables and fields of the class, the method `autoClose()` must somehow detect the scope.

Do you have any idea how to do this?

**Comment by sksamuel** [comment]
I would just close after all tests have run. If people need something to be
closed after a particularly test, they'll have to roll their own. I think
the usefulness of this is for class-wide resources.

**Comment by helmbold** [comment]
After rereading the spock documentation page, I think that spock doesn't handle local variables. And as you've said it is easy to close such resources locally. So, it should be fine to just handle fields. I've implemented it so. Before I push my changes, I want to refactore KTestJUnitRunner and TestBase, to move more logic in Testbase, so that things like calling the method to close resources can be better handled.

**Comment by helmbold** [comment]
@sksamuel Please change the order of fields in the test class, run the test, and verify whether the output is as expected. 
![two entries for one test](http://i.imgur.com/u4rlRh6.png)
