### ISSUE TITLE
Better support for comparing multi-line strings

### ISSUE THREAD

**Issue by sschuberth** [kotlintest/kotlintest#402]
When doing

    actualResult shouldBe expectedResult

where both `actualResult` and `expectedResult` are (long) multi-line strings, console output in case of a mismatch could be improved. Currently, as can be seen e.g. [here](https://ci.appveyor.com/project/heremaps/oss-review-toolkit/build/1.0.3355#L2861), console output starts with the expected text. However, as that text is long and console output is limited, it does not even come as far as also showing the actual output. To address this, it would be nice if long multi-line output was condensed by stripping matching lines, and only keeping "diff hunks" similar like Git does to display only the areas of text where there actually is a difference.

**Comment by sksamuel** [comment]
I've added my attempt.

You end up with a sequence of diffs. Each diff has a type (delete, change, addition), the line where it started, and the snippet that changed (with a line before/after for context).

The raw exception message is like this:

```
java.lang.AssertionError: 
expected: "[Change at line 1] Our neural pathways have become accustomed to your sensory input patterns.
      Mr. Crusher, ready a collision course with the Borg ship.
      A lot of things can change in twelve years, Admiral.

[Deletion at line 4] A lot of things can change in twelve years, Admiral.
      Take the ship into the Neutral Zone"

 but: was "[Change at line 1] Our neural pathways have become accustomed to your sensory input patterns.
      Mr. Crusher, ready a collision course with the Klingon ship.
      A lot of things can change in ten years, Admiral.

[Deletion at line 4] A lot of things can change in ten years, Admiral."
```

Which intellij picks up nicely and shows the diff window.
