### ISSUE TITLE
Add infix modifier to collections matchers

### ISSUE THREAD

**Issue by jensim** [kotlintest/kotlintest#404]
```
val found = repo.findAll()
found shouldContainExactly listOf("one", "two", "three")
```

```
//Before
fun <T, C : Collection<T>> C?.shouldContainExactly(expected: C) = this should containExactly(expected)

//After
infix fun <T, C : Collection<T>> C?.shouldContainExactly(expected: C) = this should containExactly(expected)
```

This is not applicable to vararg param functions due to limitation in language, but it would look better in for all collections matchers where it is possible.

**Comment by sksamuel** [comment]
Yes good idea.

**Comment by jensim** [comment]
I forked master and created a branch with the `infix` added

**Comment by sksamuel** [comment]
Excellent. Please make a PR and I'll merge.

**Comment by sksamuel** [comment]
I'll include this in 3.1.10

**Comment by sksamuel** [comment]
3.1.10 is released.

**Comment by sksamuel** [comment]
You'll be waiting hours for that UI to update.
Once it's in the repo you're good to go
http://repo1.maven.org/maven2/io/kotlintest/kotlintest-assertions/

**Comment by jensim** [comment]
Thanks @sksamuel !
