### ISSUE TITLE
Add more tests for Date Matchers

### ISSUE THREAD

**Issue by Kerooker** [kotlintest/kotlintest#406]
The code for Date Matchers (package `io.kotlintest.matchers.date`, file `matchers.kt`) has a lot of extension  functions to match Dates (LocalDateTime, LocalDate, ...).

There is one test class, called `DateMatchersTest`. However, some methods are not tested in this class. Some examples:

- `fun LocalDateTime.shouldHaveSameYearAs(date: LocalDateTime);`
- `fun ZonedDateTime.shouldBeAfter(date: ZonedDateTime)`

and some others.

----
The code is very trivial (only delegate to another function), but unit testes are needed nonetheless.

What does this solve?
--

It doesn't solve anything now, but for future refactors of these matchers, there should be a test scenario for each of them.

**Comment by Kerooker** [comment]
Currently working on this.

**Comment by sksamuel** [comment]
It will be good to cover this.

**Comment by Kerooker** [comment]
Merged, resolving this issue.
