### ISSUE TITLE
Add configuration parameters to property testing

### ISSUE THREAD

**Issue by sksamuel** [kotlintest/kotlintest#41]
- invocation count - the number of different values that should be fed in 
- minsuccessful - the mininum number of attempts that must pass
- threads - number of threads to use in the executor pool

**Comment by sksamuel** [comment]
If you want to pick this up @helmbold feel free, otherwise I'll do it after my other tickets.

**Comment by helmbold** [comment]
Yes, I would do it next week.

**Comment by sksamuel** [comment]
Is this still outstanding?

**Comment by helmbold** [comment]
Yes, it is still open. This was not on my radar ...

**Comment by sksamuel** [comment]
Check three comments up :p

**Comment by helmbold** [comment]
Yes, I know :-/ But completely forgotten this issue, though.

**Comment by sksamuel** [comment]
Ok I'll do it.

**Comment by sksamuel** [comment]
I'm closing this as since #222 we can specify the number of attempts, and the number of threads can be specified by using any standard test block.
