### ISSUE TITLE
Config with invocations > 1 stuck if test fails 

### ISSUE THREAD

**Issue by fraquack** [kotlintest/kotlintest#413]
When running a test with more than one invocation, the test keeps running forever if one of the invocations fails.
For instance, running the following code results in a never ending test.
```
class Test: StringSpec({
	"Test".config (2){
		"".shouldBe(null)
	}
})
```
Can somebody confirm this bug?

**Comment by Kerooker** [comment]
Can confirm. Happened to me when executing via Intellij and Gradle, and for the scenario above and
```
"".shouldBe("a")
```
(trying to filter out any possible problem with the null)

**Comment by sksamuel** [comment]
I've pushed a fix to master for this. Thanks for the bug report.
