### ISSUE TITLE
Add matcher shouldBeWithin for LocalDateTime, OffsetDateTime and ZonedDateTime that includes other units

### ISSUE THREAD

**Issue by Kerooker** [kotlintest/kotlintest#416]
Sometimes when dealing with dates, one must compare a date to another for equality. However, some special cases might happen, when one date is extremely close to another, but not equal:

LocalDateTimes:
- `1998/02/09 10:00:00:000001`
- `1998/02/09 10:00:00`

These should be considered somewhat equal, but they're not. One should use something like `date1 shouldBeWithin 2 seconds of date2`(pseudo-code).

The current API doesn't allow that kind of behavior. It only allows `shouldBeWithin` for `Period`, which does not have matching for Hour, Minute, Second and Nanosecond. A good unit for this would be `Duration`, from the same package of `Period` in the JVM.

---
Current Workaround:
--
Creating a custom matcher in my own application to match these date and times

Proposal:
--
Creating a matcher in the main lib that accepts `Duration` as a parameter for the `within` matcher.

**Comment by sksamuel** [comment]
Seems like an excellent idea.

**Comment by Kerooker** [comment]
This was merged.
Thanks!
