### ISSUE TITLE
The disabled test is displayed several times

### ISSUE THREAD

**Issue by BorzdeG** [kotlintest/kotlintest#418]
![](https://habrastorage.org/webt/yi/o1/pd/yio1pdh2ja3szs61sksi3h2bnnc.png)

source: https://github.com/itbasis/jvm-wrapper-ide-plugins/blob/master/plugin-common/src/test/kotlin/ru/itbasis/jvmwrapper/core/unarchiver/LinuxUnarchiverTest.kt

**Comment by Kerooker** [comment]
Which version of KotlinTest did this happen?
Failing tests don't display more than once to me.

**Comment by BorzdeG** [comment]
At the current moment (the latest stable versions of KotlinTest, Kotlin and IDEA) there is no error
