### ISSUE TITLE
`int()` `Gen` constants do not match documentation

### ISSUE THREAD

**Issue by lalunamel** [kotlintest/kotlintest#419]
Hi there! Really interesting library! I was just reading through the source for your property testing implementation (just out of curiosity) and noticed a discrepancy.

 In `properties/Gen`, the `int()` function implementation in the companion object does not match the documentation.

Specifically, the documentation states 

`The values always returned include the following edge cases: [-1, 0, 1, Int.MIN_VALUE, Int.MAX_VALUE]`

But the implementation states

```kotlin
val literals = listOf(Int.MIN_VALUE, Int.MAX_VALUE, 0)
override fun constants(): Iterable<Int> = literals
```

Looking at the history, it seems the implementation of that line changed with commits:
50903a147ef97141b55caf5f2171aeb4649a03f9
6d42236292f1e97191a3035452a861997b136690

Cheers!

**Comment by sksamuel** [comment]
Good spot thank you. Fixed.

**Comment by lalunamel** [comment]
@sksamuel Could you tell me why you wouldn't want -1 and 1 included in the constants? Is the thinking that Int.MIN_VALUE and Int.MAX_VALUE will cover those?

**Comment by sksamuel** [comment]
The more edge cases you add in, the more total runs you have.
5 edge cases, and 5 inputs, and you have 5^5=3125 combinations, and that's without running any of the random cases. I'm not sure what a good solution would be so I limited the edge cases.
