### ISSUE TITLE
Gradle does not execute custom StringSpec tests in custom source set

### ISSUE THREAD

**Issue by yonigibbs** [kotlintest/kotlintest#421]
I have a project with a custom source set for integration tests (to keep them separate from unit tests). In this custom source set, when I have a standard JUnit test (using the `@Test` annotation), a broken test successfully causes the tests to fail. However when the test is a subclass of `StringSpec`, the tests don't seem to be executed (or, at least, broken tests aren't causing the gradle task to fail as expected).

However, the same thing is all working correctly in the unit tests themselves (which aren't in a custom source set).

I have a [github repo](https://github.com/yonigibbs/kotlin-test-integration-test) where this can be reproduced (at least on my system).

Also, running the tests manually from within IntelliJ (rather than using Gradle) works correctly as well.

Is there anything I've missed, or am doing wrong?

Thanks.

**Comment by sksamuel** [comment]
My first guess would be that the custom source set is not being passed by gradle as a classpath when it invoked the junit 5 test runnner, but instead gradle is using its own test discovery. I know this behaviour will all change in gradle 5.

I'll take a look at your repo to see if I'm right and see if I can think up a workaround.

**Comment by yonigibbs** [comment]
Thanks @sksamuel, much appreciated.  However, good news, I just managed to sort it.  Had to add this to `build.gradle`:

```
integrationTest {
    useJUnitPlatform()
}
```

So the test task generated for that source set needs to be told to use the JUnit platform.

**Comment by sksamuel** [comment]
Oh right, good to know thanks!.
