### ISSUE TITLE
Add optional exception type parameter to beFailure arrow-assertions

### ISSUE THREAD

**Issue by osheari1** [kotlintest/kotlintest#422]
It would be useful to be able to easily check whether a Try returns a failure in general, and that it returned a particular underlying Exception. Currently we can do something like this:
```
val failure = Try.Failure(Exception("foo"))
failure should beFailure()
shouldThrow<Exception> {
    failure.getOrElse { fail("Could not get exception") }
}
```

However it would be a bit more aesthetically pleasing to be able to do:
```
val failure = Try.Failure(Exception("foo"))
failure should beFailure(Exception) // Passes test
failure should beFailure(SomeOtherException) // Does not pass test
```

**Comment by sksamuel** [comment]
`failure should beFailure[SomeExceptionType]` ?

Easy enough to add.

**Comment by osheari1** [comment]
Ah yes exactly. 

I'll contribute, but are there any tests for the arrow assertions? I can't seem to find any.

**Comment by sksamuel** [comment]
Yes, they are here
https://github.com/kotlintest/kotlintest/tree/master/kotlintest-tests/kotlintest-tests-core/src/test/kotlin/com/sksamuel/kotlintest/assertions/arrow

I'm not sure why I put them there. Feel free to add new tests there or move them to arrow module.

**Comment by osheari1** [comment]
Sounds good, thanks!
