### ISSUE TITLE
Warning stops test execution

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#43]
If I run all tests of the KotlinTest project, the execution (in IntelliJ 2016.1.3) stops with 109 of 110 tests. It appears the message:

> [WARN] When comparing doubles consider using tolerance, eg: a shouldBe b plusOrMinus c

![error in IntelliJ](http://i.imgur.com/gLoNPwe.png)

**Comment by sksamuel** [comment]
I don't think the warn is anything to do with that, because that's just being emitted when I test plusOrMinus in `DoubleMatchersTest`. I get something similar, but all tests pass. I think perhaps the count is just off.

**Comment by sksamuel** [comment]
Ah the issue is just that there is an ignored test in ConfigTest. It's there just to make sure the dsl doesn't change and for a visible check. I'm not sure how to check that an ignored test didn't actually run.

**Comment by helmbold** [comment]
How does JUnit gets the number of tests? Maybe ignored tests can be subtracted there.

**Comment by sksamuel** [comment]
That's certainly easy enough to do, but then it doesn't appear in the list.
What do you think is better.

**Comment by helmbold** [comment]
It is good to see (and count) ignored tests.However there is some difference between ignored JUnit tests and ignored KotlinTest tests.

JUnit counts all tests and ignored tests:
![test count in JUnit](http://i.imgur.com/0YoYqk7.png)

KotlinTest doesn't count ignored tests:
![test count with KotlinTest](http://i.imgur.com/K07uRjg.png)

I have no idea how to do it, but I'd prefer the JUnit behavior and view.

**Comment by sksamuel** [comment]
Agreed. I'll figure it out while you're doing the config stuff.

**Comment by sksamuel** [comment]
Sorted
