### ISSUE TITLE
Double Matchers should be maintained in the same file

### ISSUE THREAD

**Issue by Kerooker** [kotlintest/kotlintest#433]
Currently, there's a file called `matchers.kt` that is in the package `io.kotlintest.matchers.doubles`, and another file called `DoubleMatchers.kt` that is in the package `io.kotlintest.matchers`.

Both these matchers are about Doubles, but are in different files.

I suggest that both these matchers should be merged in file `io.kotlintest.matchers.doubles.matchers.kt`, and the file `DoubleMatchers.kt` should be deprecated for now, and removed in the future.

What do you think?

**Comment by sksamuel** [comment]
The reason I did that is because I didn't want people to have to update their imports, but the newer matchers I wanted in their own package so we could have matchers with the same name. I think for 3.2 we can migrate them and deprecate the old ones like you say.

**Comment by Kerooker** [comment]
I think that for 3.2 we can migrate and deprecate with a WARN
Some time in the future we should deprecate with an ERROR
And some time after that, delete the old file
