### ISSUE TITLE
Double should have oppostive matchers for shouldBePositive and shouldBeNegative

### ISSUE THREAD

**Issue by Kerooker** [kotlintest/kotlintest#435]
Most of the matchers have a opposite matcher. For example
```
Double.shouldBeLessThan
Double.shouldNotBeLessThan
```

This behavior should be added to the `shouldBePositive` and `shouldBeNegative` matchers.

A use case for this, is for example matching the number 0.0;

Zero is not positive, and it should match `shouldNotBePositive`. However, the opposite of this is not `shouldBeNegative`, as it won't match 0.0 (zero is also not negative).

----

I propose that we add the following matchers to the Double Matchers:

`Double.shouldNotBePositive`
`Double.shouldNotBeNegative`

**ATTENTION:** These matchers might also be useful for Int, Float, Short.... But I didn't take a look at them for now. It's a point to be kept in the radar!

**Comment by raverona** [comment]
I created a pull request to fix this issue, it also creates a `DoubleMatchersTest.kt` on a new `com.sksamuel.kotlintest.matchers.double` package inside the `kotlintest-tests/kotlintest-tests-core` module as I talked with @Kerooker beforehand and it's the aproach he is taking for these tests

**Comment by raverona** [comment]
Let me know if you guys think more test cases are necessary for this feature
