### ISSUE TITLE
Documentation on test ordering

### ISSUE THREAD

**Issue by fraquack** [kotlintest/kotlintest#439]
The note at the end of the chapter **Parallelism** (https://github.com/kotlintest/kotlintest/blob/master/doc/reference.md#parallelism) states:

> Note: Test cases inside each spec will always run sequentially (either in definition order, or in a random order, see documentation on test ordering).

However I can't find this documentation on test ordering. Where can I find it?

At the moment, my tests rely heavily on their definition order in their spec and it looks like they are actually running in this way. But I don't know if, in the future, a spec "decided" to run its tests in random order.
Should I avoid to depend on test ordering inside each spec? In this way I can save some computational time, recycling resources.

**Comment by fraquack** [comment]
I'm using 3.1.10 and I've never overridden the function `testCaseOrder()`.
Therefore, I should inherit the function `testCaseOrder()` of `AbstractProjectConfig`:
```
  /**
   * Sets the order of top level tests in a spec.
   * The value set here will be used unless overriden in a [Spec].
   * The value in a [Spec] is always taken in preference to the value here.
   * Nested tests will always be executed in discovery order.
   *
   * If this function returns null then the default of Sequential
   * will be used.
   */
  open fun testCaseOrder(): TestCaseOrder? = null
```
and my test should run in `Sequential` order.
Thank you for your quick help.

**Comment by sksamuel** [comment]
You can override it in either place.

**Comment by sksamuel** [comment]
@Kerooker we need to update the docs here too.
