### ISSUE TITLE
Allow configuration per specification

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#44]
At the moment `config` is only available per test case. But it would be useful to have a configuration per specification class, that could be overridden per test case if necessary. My suggestion is as follows:

Instantiating a `TestConfig` object directly and assign it to an overridden property :

```kotlin
class MySpec : StringSpec() {
    override val config = TestConfig(threads = 10, invocations = 100)
    ...
}
```
or using a factory method instead of a direct instantiation:

```kotlin
class MySpec : StringSpec() {
    override val config = config(threads = 10, invocations = 100)
    ...
}
```
(If `TestConfig` would be renamed to just `Config` both variants were almost the same from a users perspective.)

Another option would be to call a config method inside the init block and don't use an overridden property, but I prefer a property.

```kotlin
class MySpec : StringSpec() {
    init {
        config(threads = 10, invocations = 100)

        ...
    }
}
```
I think a class wide configuration should reside on the class level as in the examples with the property.

**Comment by sksamuel** [comment]
I like the idea.

**Comment by helmbold** [comment]
What variant do you prefer? Or do you have another suggestion?

**Comment by sksamuel** [comment]
I think the override fits in better with the afterAll, oneInstance, etc

**Comment by helmbold** [comment]
Ok, following this approach it would be consistent to leave out `config` and provide properties like `threads` or `disabled` directly:

```kotlin
class MySpec : StringSpec() {
    override val threads = 10
    override val invocations = 100
    override val ignored = true
    ...
}
```

What do you think?

**Comment by sksamuel** [comment]
I guess that is consistent, but then again the DSL style can be more powerful. I guess we can always add more later.

Let's go with the overrides.

**Comment by helmbold** [comment]
OK, we agree that overrides are the best way. But after some time thinking about it, I tend to use override with the `TestConfig` object or `config` method, since a property like `threads` doesn't belong to the specification class itself. Whereas `oneInstancePerTest` does belong to the class. So it could be confusing to have per class and per test case parameters at the same level. To be self explanatory it would need a name like `threadsPerTestCase` or something like that. And then it would be better to use a config object with a property name that makes clear that this config is per test case and not per class. My preferred way is this:

```kotlin
class MySpec : StringSpec() {
    override val defaultTestCaseConfig = config(threads = 10, invocations = 100)
    ...
}
```
I think using a `config` factory method would be good to have the same syntax as for configuration per test case. Less to remember is better.

**Comment by sksamuel** [comment]
Ok I think we can go with that.

**Comment by helmbold** [comment]
OK, I'll implement as suggested.

**Comment by helmbold** [comment]
I've made `TestConfig` immutable to avoid strange behavior I've discovered while developing. We should try to make as much as possible immutable.
