### ISSUE TITLE
Spec and TestDescriptor modifications

### ISSUE THREAD

**Issue by lsrom** [kotlintest/kotlintest#448]
Is it possible to change the `io.kotlintest.Spec` class to use *canonicalName* instead of *simpleName* as default? I'm talking about the `Class<out Spec>.displayName()` extension. If there is no issue with that breaking something, I'll gladly submit a merge request.

Also, can source class be included in TestDescriptor created in method `fun createTestCaseDescriptor(description: Description, type: TestType): TestDescriptor` from class `JUnitTestRunnerListener`. TestDescriptor from this method doesn't have set source which I need.

Can I submit these changes or are there any issues I'm not aware of? Thanks.

**Comment by sksamuel** [comment]
I'm not sure about changing the display name, it's used by gradle and other things. 

As for the source class, yes I think it could be included, I don't see why not.

**Comment by lsrom** [comment]
So can I add another method that will return the *canonicalName*? I really need it in my use case.

**Comment by sksamuel** [comment]
Absolutely.
