### ISSUE TITLE
Consider supporting pending in tests

### ISSUE THREAD

**Issue by sksamuel** [kotlintest/kotlintest#45]

**Comment by helmbold** [comment]
Does this work with JUnit? 

I like the idea, but I'm not sure whether `pending` is needed when we already have `ignored`, what comes close. I would say that `pending` makes only sense, if the JUnit runner is able to list pending tests as such. That is the way [ScalaTests handles pending tests](http://doc.scalatest.org/1.8/org/scalatest/FlatSpec.html#PendingTests).

**Comment by sksamuel** [comment]
Really I just brainstorm when I'm bored at work. Some ideas might make no sense.

**Comment by sksamuel** [comment]
Doesn't look like it would be possible using a junit runner.
