### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by Kerooker** [kotlintest/kotlintest#457]
Currently, w hen deploying KotlinTest, the CI is broken. Whenever it tries to execute `./gradlew test`, it will become stuck at the first test it tries to execute, and never finishes.

I've done some digging, and I found that the class `JUnitTestRunnerListener` had an addition from PR #449 that makes it kinda messy:

Line 222:
```
descriptor = object : AbstractTestDescriptor(id, description.name, source)
```

When creating this descriptor with a `source`, the test never completes. I'm not sure what's causing this, but if we create the descriptor with

```
descriptor = object : AbstractTestDescriptor(id, description.name)
```

It will work again.

I wasn't able to investigate further, but giving this information may be helpful to solve it. I'll keep digging, but I'm not sure how tests are actually executed

**Comment by Kerooker** [comment]
@sksamuel

**Comment by Kerooker** [comment]
Ok, I have some more information on this issue:

Currently, source is created using

```
    val source = ClassSource.from(klazz?.java) ?: null
```

For some reason, this source only fails if TestType is TestType.Test. It'll never complete the test. However, if we change it to null on TestType.Test, something interesting happen, because it works:

```
  val source = if (type == TestType.Test) {
      null
    } else {
      ClassSource.from(klazz?.java) ?: null
    }
```

**Comment by Kerooker** [comment]
I have no clue on why this works. But using this way, we're able to goto source on any descriptor that's not the final one (test one).

I'm still trying to find a real reason for this, but having this documented may help any of you to find it.

@sksamuel I also believe that JUnitRunnerListener needs a refactoring. It's pretty hard to understand right now :x

**Comment by sksamuel** [comment]
We are green again!
