### ISSUE TITLE
Listener to run before/after a set of tests

### ISSUE THREAD

**Issue by alisabzevari** [kotlintest/kotlintest#458]
I want to have a different set of tests (probably specified by different tags) and have hooks to run before and after running those set of tests. Is it possible to do this in kotlintest?

One use case for this feature is separating integration tests from unit tests. Usually, integration tests need to set up a testing environment which takes time and it is not desired to run this set up process before all the tests (`beforeProject` listener).

**Comment by sksamuel** [comment]
Can you put your integration tests into separate files, and have a "before file" "after file" setup methods? We call those `beforeSpec` and `afterSpec`.

**Comment by alisabzevari** [comment]
I want to have a piece of code running before and after **a set of tests**.

One realworld example would be preparing the database schema (run migration scripts) for testing. After running migration script I want to only clean the tables (but not the whole database). Another one would be starting the mocked dependent servers in integration tests.

**Comment by sksamuel** [comment]
Yep, I'm just asking how you intend to make a "set". Because one way is to put each set into it's own file, in which case `beforeSpec` and `afterSpec` can work, and those can be implemented in an extension like class called a `TestListener`. If that doesn't work we can think of something else?

**Comment by alisabzevari** [comment]
If there was a way to not limit to one file, that would be great.

**Comment by sksamuel** [comment]
You can make a test listener class, and then apply it to every test file that you need it in. Does work?

**Comment by sksamuel** [comment]
Ok I see what you want now. The listener should be "shared" between all the classes that use it.
I'll have a think about how we can support this for 3.2

**Comment by sksamuel** [comment]
You could do this by having a var inside the listener,

`var initialized:Boolean = false`

And each time `beforeSpec` is called, only initialise if the field is false.
And then to clean up you could use afterProject`.

Would that work ?

**Comment by sksamuel** [comment]
Another idea, is we can introduce "groups" and allow each spec to have a single group defined (or null the default). Then we can have two callbacks:

`beforeGroup(group:GroupName)`
`afterGroup(group:GroupName)`

Which would be executed only once for any given group name.

**Comment by sksamuel** [comment]
@Kerooker

**Comment by Raibaz** [comment]
Another possible way to do this would be to have something like [tags and categories](https://www.baeldung.com/junit-filtering-tests) as in JUnit.

**Comment by LeoColman** [comment]
We do have tags and theoretically that enables categories to place tests in. However, I don't think that's a solution to the issue of grouping tests and executing something before and after without boilerplate.

We don't want an user to create an extension to solve this issue, for example.

We want to create these groups

**Comment by sksamuel** [comment]
In 4.0 you can add listeners to test factories (composable dynamic tests) and these listeners only act on the tests in that composable unit.

**Comment by sksamuel** [comment]
This now works in master and is part of 4.0
Any beforeTest / afterTest methods added to a test factory only apply to the tests in that factory.
