### ISSUE TITLE
Gen.oneOf should be covariant

### ISSUE THREAD

**Issue by neilgall** [kotlintest/kotlintest#471]
A common use case for `oneOf` is to select one of a series of subclasses.

```
sealed class X {
    data class A(val a: Int): X()
    data class B(val b: Int): X()
    data class C(val c: Int): X()
}
...
val genX = Gen.oneOf(
        Gen.bind(Gen.int(), X::A),
        Gen.bind(Gen.int(), X::B),
        Gen.bind(Gen.int(), X::C)
)
```

However because `oneOf` is defined with parameters `Gen<A>` rather than covariant `Gen<out A>`, this does not compile and must be modified with unchecked casts:

```
val genX = Gen.oneOf(
        Gen.bind(Gen.int(), X::A) as Gen<X>,
        Gen.bind(Gen.int(), X::B) as Gen<X>,
        Gen.bind(Gen.int(), X::C) as Gen<X>
)
```

To work around this one can use
```
fun <A> Gen.Companion.covariantOneOf(vararg gens: Gen<out A>): Gen<A> =
    oneOf(*(gens as Array<Gen<A>>))
```
which still needs an unchecked cast, but at least it is confined to a single location. It would be best built into the library itself, not least because a direct implementation does not need such unchecked casts.

**Comment by sksamuel** [comment]
Agreed.
