### ISSUE TITLE
gradle test -Dkotlintest.tags.exclude doesn't seem to work

### ISSUE THREAD

**Issue by jsonbrooks** [kotlintest/kotlintest#474]
I've defined the following tag:
`object E2E : Tag()`

I have the following StringSpec:
`class GoogleExecutorTests : StringSpec() {
    override fun tags() = setOf(E2E)`

I've also tried adding the tags to individual specs this way:
`"...".config(tags = setOf(E2E))`

... but when I run:
`./gradlew test -Dkotlintest.tags.exclude=E2E`

All specs in GoogleExecutorTests are definitely still running.

`
./gradlew test -Dkotlintest.tags.exclude=krews.E2E
...
Gradle Test Executor 1 STANDARD_OUT
    12:04:36.712 [Test worker] DEBUG io.kotlintest.runner.junit5.KotlinTestEngine - configurationParameters=LauncherConfigurationParameters []
    12:04:36.725 [Test worker] DEBUG io.kotlintest.runner.junit5.KotlinTestEngine - uniqueId=[engine:kotlintest]
    12:04:36.732 [Test worker] DEBUG io.kotlintest.runner.junit5.KotlinTestEngine - LauncherDiscoveryRequest [
    classpathRootSelectors=[]
    classpathResourceSelectors=[]
    classSelectors=[krews.LocalExecutorTests, krews.GoogleExecutorTests, krews.Unit, krews.Integration, krews.E2E, krews.GoogleExecutorTestsKt, krews.TestUtilsKt, krews.LocalExecutorTestsKt, krews.WorkflowsKt]
    methodSelectors=[]
    directorySelectors=[]
    fileSelectors=[]
    moduleSelectors=[]
    packageSelectors=[]
    uniqueIdSelectors=[]
    uriSelectors=[]
    engineFilters=[]
    postDiscoveryFilters=[]
    classnameFilters=[]
    packageNameFilters=[]
    ]
    12:04:36.788 [Test worker] DEBUG io.kotlintest.runner.jvm.TestDiscovery - Loaded 9 classes from classnames...
    12:04:36.955 [Test worker] DEBUG io.kotlintest.runner.jvm.TestDiscovery - ...which has filtered to 2 non abstract classes
    12:04:36.957 [Test worker] DEBUG io.kotlintest.runner.jvm.TestDiscovery - 2 classes after applying discovery extensions
    12:04:36.964 [Test worker] DEBUG io.kotlintest.runner.junit5.KotlinTestEngine - JUnit execution request [configurationParameters=LauncherConfigurationParameters []; rootTestDescriptor=KotlinTestEngineDescriptor: [engine:kotlintest]]
    12:04:36.968 [Test worker] DEBUG io.kotlintest.runner.junit5.JUnitTestRunnerListener - Engine started; classes=[[class krews.GoogleExecutorTests, class krews.LocalExecutorTests]]
    12:04:36.969 [Test worker] DEBUG io.kotlintest.runner.jvm.TestEngine - Submitting 2 specs
    12:04:36.970 [Test worker] DEBUG io.kotlintest.runner.jvm.TestEngine - Waiting for spec execution service to terminate
    12:04:36.984 [kotlintest-engine-0] DEBUG io.kotlintest.runner.junit5.JUnitTestRunnerListener - prepareSpec [Description(parents=[], name=GoogleExecutorTests)]

krews.GoogleExecutorTests STANDARD_OUT
    12:04:38.029 [kotlintest-test-executor-0] DEBUG io.kotlintest.runner.junit5.JUnitTestRunnerListener - Creating test case descriptor Description(parents=[GoogleExecutorTests], name=Can run a simple workflow on Google Cloud Pipelines API)/Test
    12:04:38.030 [kotlintest-test-executor-0] DEBUG io.kotlintest.runner.junit5.JUnitTestRunnerListener - Notifying junit of start event [engine:kotlintest]/[spec:GoogleExecutorTests]/[test:Can run a simple workflow on Google Cloud Pipelines API]

krews.GoogleExecutorTests > Can run a simple workflow on Google Cloud Pipelines API STANDARD_OUT

`

**Comment by Kerooker** [comment]
Thanks for the report!

So here's what's happening: Your Gradle is not propagating the JVM configurations to the test configuration.

In Java, `-Dx=y` will add x to the System.properties() from the JVM, and that's what we're looking for. In your case, Gradle is not propagating the `System.properties()` to its JVM children, and the tag doesn't exist there.

What you can do is to explicitly tell gradle to do it, by configuring your `test` task, adding something like this:
```
test {
    //... Other configurations ...
    systemProperties = System.properties
}
```
And the tags will work as intended. I'll be adding this piece of advice to the Tags documentation

**Comment by jsonbrooks** [comment]
It'd be nice not to need that properties assignment, so if that's possible then it seems worth looking into.

Either way I have no problem with closing this ticket.

**Comment by Kerooker** [comment]
I'll try to see what can be done to that. Maybe KotlinTest can configure Gradle to propagate properties correctly, but this needs more discussion.

Thanks for the report, and thanks a lot for your time to come around and report this!

I hope to have solved your issue for now :)
