### ISSUE TITLE
gradle test include tag 

### ISSUE THREAD

**Issue by bahka** [kotlintest/kotlintest#478]
I have some number of files with specs, one spec has tag __Acceptance (just for check), but all specs has some tags (from 2 till 5 tags).

* Path to specs
../src/test/kotlin/domain/company/project/**specs**/...

All of them has the same structure :
* Spec structure with tag
```
class NameSpec : DescribeSpec({
    describe("i do some staff") {
        // pass
    }
}) {
    override val defaultTestCaseConfig: TestCaseConfig
        get() = TestCaseConfig(tags = setOf(_Acceptance, _Regression))
}
```
* TestCaseConfig
```
data class TestCaseConfig(
    val enabled: Boolean = true,
    val invocations: Int = 1,
    val timeout: Duration = Duration.ofSeconds(600),
    val threads: Int = 1,
    val tags: Set<Tag> = emptySet(),
    val extensions: List<TestCaseExtension> = emptyList()) {
  init {
    require(threads > 0, { "Theads must be > 0" })
    require(invocations > 0, { "Invocations must be > 0" })
  }
}
```

* gradle command to run tests 
```
./gradlew clean test -Dkotlintest.tags.include=_Acceptance
```

And I wait 7 minutes...  and 1 test runs (from IDEA it takes 20sec for run this test) than for uploading some files and check this tags takes more than 6 minutes!  Seems like gradle walks through all specs and check tags in tests. It takes ~2s per each file. 

How do that faster?  What do I do wrong?

**Comment by Kerooker** [comment]
Doesn't seem to me that you're doing anything wrong.

However, the only way for us to identify which tests should be run based on tags is to find all tests with the specified tag.

I'm not sure if there's a lot to be done one this, but I'll see what can be optimized in that way. Any ideas, @sksamuel ?

**Comment by sksamuel** [comment]
So we obviously have to scan all tests to find out which tags they have.
But 2 seconds a test is very slow.
The upgrade to use ClassGraph might help here as it's miles faster than Reflections.

**Comment by Kerooker** [comment]
But maybe we can do some tweaks at Spec tags.
I see that we only scan for spec tags when we're about to run the test. Maybe we should do it when we're about to run the spec too. This way we won't scan for tests that we don't need to.

**Comment by sksamuel** [comment]
The only time that would work is when a spec has an exclude tag that is active.

If you run `-Dkotlintest.tags.include=_Acceptance` and a spec doesn't have the tag, it doesn't matter. The test may still have the tag so you have to check tests.

We should just figure out why it takes 2 seconds a test. Let's try it without reflections (ie current master) and take it from there.

**Comment by sksamuel** [comment]
@bahka if you try 3.2.1 you should find scanning is much faster.

**Comment by LeoColman** [comment]
Closing this issue for now. @bahka if you face any other issues in this matter, please let us know.
