### ISSUE TITLE
kotlintest-assertions-json and kotlintest-assertions-ktor don't seem to be published

### ISSUE THREAD

**Issue by tw** [kotlintest/kotlintest#480]
I can see https://bintray.com/bintray/jcenter/io.kotlintest%3Akotlintest-assertions-arrow

but not https://bintray.com/bintray/jcenter/io.kotlintest%3Akotlintest-assertions-ktor and https://bintray.com/bintray/jcenter/io.kotlintest%3Akotlintest-assertions-json

am I doing something silly?

**Comment by sksamuel** [comment]
They're new modules in 3.2 which isn't ready yet.

**Comment by tw** [comment]
@sksamuel thanks :) it was most confusing given they were added many months ago

**Comment by sksamuel** [comment]
We'll speed up the release of 3.2!
