### ISSUE TITLE
Clicking on a test on android studio does not open the corresponding code

### ISSUE THREAD

**Issue by jrcacd** [kotlintest/kotlintest#499]
![image](https://user-images.githubusercontent.com/26005662/49591894-99ad0180-f967-11e8-8dc8-4a273f258d56.png)

**Comment by Kerooker** [comment]
Thanks for taking your time to report!

Currently, the specific test scenario doesn't have the source/corresponding code. Depending on the spec you're running, it's not quite possible to identify which line executed the scenario.

The top-level spec has the source attached, and you can find it through there.

I'll see what's possible to do to include the source in the test case, but for now that's not a feature.

**Comment by Kerooker** [comment]
@sksamuel 
I believe this might be possible if we add the calling line together with the Class Source. JUnit might be able to point the user to the line.

I'm running some tests with inlined functions, to see if they screw anything up

**Comment by sksamuel** [comment]
Not yet. They have issues for it but their progress has been glacial imo.

**Comment by LeoColman** [comment]
Perhaps with our IntelliJ plugin this is working correctly.

If this issue rises again with no fix, we may discuss it again.

For now I'll close it.
