### ISSUE TITLE
Make oneInstancePerTest = true as default

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#50]
In class `TestBase` is `oneInstancePerTest` set to false by default. Although a testcase should be stateless and independent from other tests, it is a safer default to create a new instance per test case. 

This is, by the way, the default in some other frameworks, too. In JAX-RS for example is a resource object created per request, although it would be possible to have stateless resources and reuse a resource object for many requests. I guess they have chosen this default, because it helps to avoid bugs.

**Comment by sksamuel** [comment]
I think that having a single instance is probably what is most expected? If you open a DB connection etc, then you'd probably expect that to only be opened once. There's nothing in the DSL that indicates (at least to me) that you would expect to have each nested test in its own instance.

**Comment by helmbold** [comment]
Yes, nothing in the testing DSL indicates that a test is running in its own instance - but there is also nothing that indicates the opposite. My idea was only to help avoiding bugs.

What was your intention for `oneInstancePerTest = false`? Performance?

**Comment by sksamuel** [comment]
Just because that's the scalatest default.

**Comment by helmbold** [comment]
[Spock](https://spockframework.github.io/spock/docs/1.0/spock_primer.html) runs each test in its own instance: "Objects stored into instance fields are not shared between feature methods. Instead, every feature method gets its own object."

**Comment by sksamuel** [comment]
But this project was started as a port of ScalaTest not Spock :)

**Comment by helmbold** [comment]
Yes, it *started* as a port of ScalaTest, but although the source of inspiration is undeniable, KotlinTest stands for itself now. We shouldn't base technical decision only on what ScalaTest does. 90 % of the users will come from JUnit, 10 % will come from TestNG, and only the rest will come from ScalaTest ;-) In this case, I think a new instance per test case is the safer (=better) default.

**Comment by helmbold** [comment]
My idea was like this: http://sweng.the-davies.net/Home/rustys-api-design-manifesto Get it right without thinking about it.

**Comment by sksamuel** [comment]
I guess we just disagree on what the "obvious default" would be :)

**Comment by helmbold** [comment]
I think it is not so much about personal preference (actually I don't have one in this case), but about what is a safer default. And isolating test cases by separate instances is *safe*, especially in combination with parallelism #51.

**Comment by sksamuel** [comment]
Lots of people write tests where each test falls through to the next one (ie the 2nd test builds on the state of the 1st test). Changing this would break those kinds of tests too. My biggest concern is that if you have loads of setup code, you only want to run it once. Quite often I create embedded databases in a unit test, eg https://github.com/sksamuel/elastic4s/blob/master/elastic4s-core-tests/src/test/scala/com/sksamuel/elastic4s/GetTest.scala

I'm wavering on which is better as if we do #51 then we have to enforce no shared state.

**Comment by helmbold** [comment]
It is generally a bad practice to write tests that are depending on each other, though there might be reasons to do so. But then the tests should be explicitly designed for it. If we want to support such a style, we should make it explicit in the API. By default it should be hard to make errors in the test code, and Isolating tests through instances would help to achieve this.

**Comment by sksamuel** [comment]
Ok.

**Comment by la10736** [comment]
@helmbold 's point of view is not just an opinion but is a solid principle. I found that is just hard enough try to write independent from each others tests in legacy code when you have an instance for each test that I cannot imagine what the mess can be if I use just a single instance.

IMHO a good test framework should be suitable for testing both legacy and new projects.

**Comment by sksamuel** [comment]
Would have to be 2.0 since it's a breaking change.

**Comment by la10736** [comment]
That sounds good!

**Comment by helmbold** [comment]
If I change `oneInstancePerTest` to `true`, all tests are failing.

![instancepertest](https://cloud.githubusercontent.com/assets/5079980/16805730/de37e918-4911-11e6-910b-095daf1901aa.png)

Do you have any idea what could be wrong? @sksamuel

**Comment by sksamuel** [comment]
In latest 2.0 ?

**Comment by helmbold** [comment]
Yes, it is the latest code from 2.0.

**Comment by sksamuel** [comment]
It's because `instance.performAfterAll(notifier)` is being called after each test, and that calls `afterAll`, so we're running `afterAll` before all the tests have completed and breaking things. We need to fix to run it only once, on the main instance perhaps.
