### ISSUE TITLE
Running all tests in parallel

### ISSUE THREAD

**Issue by sksamuel** [kotlintest/kotlintest#51]
Specs2 in scala runs its tests using akka. We don't have to do that (could use an executor pool) but atm we're not taking advantage of multi cores to run the tests concurrently. @helmbold

**Comment by helmbold** [comment]
Goode idea! (Although I thought tests were already running in parallel with the executor in TestBase.)

**Comment by sksamuel** [comment]
The executor is dependent on the thread count you specify. If you don't change it and have 200 tests, you get serial testing. Also it only makes sense if we go for one instance per test by default as you want :)

**Comment by mfriedenhagen** [comment]
You need to implement `org.junit.runners.ParentRunner` to execute tests parallely (at least for usage with Maven).

**Comment by helmbold** [comment]
@sksamuel Any progress on this issue? Can I support you in some way?

**Comment by sksamuel** [comment]
I haven't started it yet. I've been busy writing my Kotlin book. I can pick this up soon or you can if you wish? I thought we could use a normal thread pool executor service and drop each test into it as a task.

**Comment by helmbold** [comment]
You write a Kotlin book? Cool! :-)

The idea to use a thread pool sounds good and I would implement it - however I'm not that deep in JUnit, that I have an idea how to use the ParentRunner mentioned by @mfriedenhagen . Maybe you could give me a little hint.

**Comment by sksamuel** [comment]
Yep should be published by end of year, we're about half way through it.

I can pick it up, but it won't be for 1-2 weeks, or if you want to do it then I think you can skip ParentRunner, and just implement it yourself. I would add a shared thread pool executor service to our jUnit runner, and for each test, submit a task that executes that test into the executor. Then once all tests are submitted, you block waiting for them to finish. You need to take into account the config options regarding concurrency and replay as well.

**Comment by helmbold** [comment]
Ok, it sounds like you'd have the implementation pretty much in your head and one or two weeks more or less doesn't matter. I think it would be the best if you implement it. I'll try to design an extension mechanism (#77) in the mean time.

**Comment by sksamuel** [comment]
Ok sounds good.

**Comment by sksamuel** [comment]
I might bump this to 2.1, if there's no objection @helmbold

**Comment by helmbold** [comment]
I wonder whether this would be a breaking change. The API wouldn't change, but the behavior could change, so that tests could break. This would require another major version bump. Maybe we should just delay 2.0 a bit.

**Comment by sksamuel** [comment]
Ok good point.

**Comment by sksamuel** [comment]
Playing around with this, it's clear its problematic. This might be the reason junit is single threaded, and why sbt / gradle runs their tests in order too. I vote to close this without an implementation.

**Comment by mfriedenhagen** [comment]
Well, junit is not single threaded, it uses the aforementioned ParallelRunner and has an implementation for running methods or classes in parallel in junit.run  It is by no means trivial and a similar issue is open for a Groovy test framework called Spock for a long time.

**Comment by sksamuel** [comment]
I think the ParentRunner (is that what you mean rather than ParallelRunner because you refer to ParentRunner earlier) will run suites in parallel but not tests inside suites. (So the docs say on ParentRunner).

**Comment by helmbold** [comment]
We should definitely look for a way to run tests in parallel. In large projects it is the only way to run tests again and again. Maybe TestNG as the underlying test runner could help. http://testng.org/doc/documentation-main.html#parallel-running But I haven't thought about any details.

**Comment by sksamuel** [comment]
I don't see what mechanism we can use in junit. ParentRunner isn't suitable. I can put the tests in an execution pool but it gets confused on output. Most build tools allow tests to be split off and run in parallel at the class file level.
I vote to close and maybe re-consider for a 3.0 release. Then we fix up last remaining bugs and released 2.0.

**Comment by helmbold** [comment]
Sad to hear that :-( I'v thought about trying it with TestNG, but that would be a pretty big change I think, and I don't know how to do it (but maybe we could ask @cbeust for help, since he uses Kotlin himself). 

There more reasons to try TestNG:

* unresolved problems with JUnit/KotlinTest/IntelliJ interop
* we could unify the interceptor model for the whole project (instead of `before`/`after` methods)

However, I can not estimate how big the effort would be.

**Comment by sksamuel** [comment]
I would be keen to release 2.0 before (if) we decided to move to TestNG.

**Comment by helmbold** [comment]
agreed. I think 2.0 is an important release for KotlinTest and we shouldn't delay it in such a dimension. So, lets move this issue to 3.0.

**Comment by cbeust** [comment]
Let me know how I can help...

**Comment by helmbold** [comment]
Thanks, @cbeust , we'll come back to you ...

**Comment by sksamuel** [comment]
3.0.0 RC1 supports parallelism. Instructions are in the change log.
If you have the time, please give it a try. There are some breaking changes that should be aware of by reading the changelog here: https://github.com/kotlintest/kotlintest/blob/master/CHANGELOG.md
