### ISSUE TITLE
Confusing block execution with isInstancePerTest=true

### ISSUE THREAD

**Issue by bbaldino** [kotlintest/kotlintest#510]
I was trying to debug some test issues and was getting really confused following the code flow when `isInstancePerTest` is set to `true`.  I really like `isInstancePerTest` as it makes ensuring state is correct a lot easier, but it's confusing how many times each block is executed.  In this example test:

```
internal class ClassUnderTestTest : ShouldSpec() {

    override fun isInstancePerTest(): Boolean = true

    init {
        "Scope 1" {
            println(this.context.description().name)
            "Scope 1a" {
                println(this.context.description().name)
                should("1aa") {
                    println(this.description().name)
                    1 shouldBe 1
                }
                "Scope 1ab" {
                    println(this.context.description().name)
                    should("1aba") {
                        println(this.description().name)
                        1 shouldBe 1
                    }
                }
            }
            "Scope 1b" {
                println(this.context.description().name)
                should("1ba") {
                    println(this.description().name)
                    1 shouldBe 1
                }
                "Scope 1bb" {
                    println(this.context.description().name)
                    should("1bba") {
                        println(this.description().name)
                        1 shouldBe 1
                    }
                }
            }
            "Scope 1c" {
                println(this.context.description().name)
                should("1ca") {
                    println(this.description().name)
                    1 shouldBe 1
                }
            }
        }
    }
}
```

With `isInstancePerTest` set to false, it prints:
```
Scope 1
Scope 1a
should 1aa
Scope 1ab
should 1aba
Scope 1b
should 1ba
Scope 1bb
should 1bba
Scope 1c
should 1ca
```
Which seems expected.  With `isInstancePerTest` set to true, it prints:
```
Scope 1
Scope 1
Scope 1a
Scope 1
Scope 1a
should 1aa
Scope 1
Scope 1a
Scope 1ab
Scope 1
Scope 1a
Scope 1ab
should 1aba
Scope 1
Scope 1b
Scope 1
Scope 1b
should 1ba
Scope 1
Scope 1b
Scope 1bb
Scope 1
Scope 1b
Scope 1bb
should 1bba
Scope 1
Scope 1c
Scope 1
Scope 1c
should 1ca
```
Whereas I would have expected:
```
Scope 1
Scope 1a
should 1aa
Scope 1
Scope 1a
Scope 1ab
should 1aba
Scope 1
Scope 1b
should 1ba
Scope 1bb
should 1bba
Scope 1
Scope 1c
should 1ca
```
I've posted on here before about test execution order and I know it's a tricky thing, but it's pretty surprising to try and step through the code with the current way it executes using `isInstancePerTest=true`

**Comment by bbaldino** [comment]
I just dug up the [spec isolation bug](https://github.com/kotlintest/kotlintest/issues/379) and it sounds like maybe that will address this?

**Comment by Kerooker** [comment]
I believe the current development of this issue is at the master branch. I don't believe there's a way for you to test it outside KotlinTest, unless you buid it yourself

**Comment by bbaldino** [comment]
Cool, I'll build master and try it out.

**Comment by bbaldino** [comment]
For some reason gradle doesn't pull down the right dependencies when I try it locally.  Is there going to be a release soon?

**Comment by Kerooker** [comment]
We're planning on 3.2 for a bit now, but I'm not sure how soon it will be released. We're trying to add coroutines support before releasing

**Comment by sksamuel** [comment]
Coroutines is done now (pending review) so release should be imminent.

**Comment by sksamuel** [comment]
Can you try 3.2.0-RC1 @bbaldino

**Comment by Kerooker** [comment]
Let me look what's going on

**Comment by bbaldino** [comment]
I added the string to a queue but get the same order

**Comment by Kerooker** [comment]
Yes, I noticed that maybe I wasn't correct on that. I'll investigate further

**Comment by bbaldino** [comment]
Although I'll note I tried printing from the queue in `afterProject` but it wasn't run.  If I do it in `afterSpec` it runs multiple times.

**Comment by Kerooker** [comment]
How did you try to do in `afterProject`?

Use `afterSpecClass` if you want it run only once

**Comment by bbaldino** [comment]
This is my afterProject:
```
override fun afterProject() {
    super.afterProject()
    println("printing from queue")
    scopeList.forEach(::println)
}
```

`afterSpecClass` sees my list member as empty somehow?  Here's my test:

```
internal class ClassUnderTestTest : ShouldSpec() {

//    override fun isInstancePerTest(): Boolean = true
    override fun isolationMode(): IsolationMode? {
        return IsolationMode.InstancePerLeaf
    }

    fun fprintln(msg: String) {
//        println(msg)
//        System.out.flush()
    }

    val scopeList = mutableListOf<String>()

    override fun afterProject() {
        super.afterProject()
        println("printing from queue")
        scopeList.forEach(::println)
    }

    override fun afterSpecClass(spec: Spec, results: Map<TestCase, TestResult>) {
        super.afterSpecClass(spec, results)
        println("printing from queue")
        scopeList.forEach(::println)
    }

    init {
        "Scope 1" {
            fprintln(this.context.description().name)
            scopeList.add(this.context.description().name)
            "Scope 1a" {
                fprintln(this.context.description().name)
                scopeList.add(this.context.description().name)
                should("1aa") {
                    fprintln(this.description().name)
                    scopeList.add(this.description().name)
                    1 shouldBe 1
                }
                "Scope 1ab" {
                    fprintln(this.context.description().name)
                    scopeList.add(this.context.description().name)
                    should("1aba") {
                        fprintln(this.description().name)
                        scopeList.add(this.description().name)
                        1 shouldBe 1
                    }
                }
            }
            "Scope 1b" {
                fprintln(this.context.description().name)
                scopeList.add(this.context.description().name)
                should("1ba") {
                    fprintln(this.description().name)
                    scopeList.add(this.description().name)
                    1 shouldBe 1
                }
                "Scope 1bb" {
                    fprintln(this.context.description().name)
                    scopeList.add(this.context.description().name)
                    should("1bba") {
                        fprintln(this.description().name)
                        scopeList.add(this.description().name)
                        1 shouldBe 1
                    }
                }
            }
            "Scope 1c" {
                fprintln(this.context.description().name)
                scopeList.add(this.context.description().name)
                should("1ca") {
                    fprintln(this.description().name)
                    scopeList.add(this.description().name)
                    1 shouldBe 1
                }
            }
        }
    }
}
```

(I was seeing weird newline issues, so tried to flush after each print, hence the `fprintln`--though it didn't make any difference)

**Comment by Kerooker** [comment]
Ok, that's odd

**Comment by bbaldino** [comment]
I can't seem to access `spec.scopeList` (it doesn't autocomplete, but if I put a break point there I do see it present as part of `spec`?).  But, when I break both `this.scopeList` and `spec.scopeList` have size 0.

After looking more closely, I had to cast `spec` to `ClassUnderTestTest`.  But either way both are still size 0 in `afterSpecClass`

**Comment by Kerooker** [comment]
I think that it should either be on a static variable or on an object, as the spec is getting restarted everytime

**Comment by Kerooker** [comment]
So the list is being erased everytime the spec is instantiated, as expected by IsolationType

**Comment by bbaldino** [comment]
Ah good idea, yeah that fixed it.  Still see the same (unexpected) order though.

**Comment by sksamuel** [comment]
> I would've thought `Scope 1bb` would've run after `Scope 1ba`, instead of after `Scope 1c`, is that expected? It'd be nice, but I don't think I care too much about that...the main thing was the number of executions of each scope per leaf. Nice work!

It could be done that way I suppose. It's just an artifact of the way the tests are queued up in the runner. I'll change it because I think it makes more sense your way.

**Comment by bbaldino** [comment]
cool, thanks @sksamuel.  Excited to upgrade to 3.2.

**Comment by sksamuel** [comment]
I've fixed this so will be in the next release candidate.

**Comment by Kerooker** [comment]
Fixed.
