### ISSUE TITLE
Add support to Koin

### ISSUE THREAD

**Issue by Kerooker** [kotlintest/kotlintest#515]
The Dependency Injection library [Koin](https://github.com/InsertKoinIO/koin) is being accepted in many projects that use Kotlin.

KotlinTest has support for Spring Boot already, and we should have support for other frameworks as well. `Koin` implementation would be pretty good!

There's already a [pull request](https://github.com/InsertKoinIO/koin/pull/107/) there to add support to Spek, but I think we don't need to add any code to Koin for this. We may use and abuse Listeners to do it.

A guide on how to test with Koin can be found [here](https://insert-koin.io/docs/1.0/documentation/reference/index.html#_testing_with_koin) (using JUnit)

**Comment by sksamuel** [comment]
This might have some ideas too.
https://proandroiddev.com/testing-with-koin-ade8a46eb4d
