### ISSUE TITLE
Should CollectionMatchers `containOnlyNulls` fail if collection is empty?

### ISSUE THREAD

**Issue by Kerooker** [kotlintest/kotlintest#516]
In Collection Matchers, we have a matcher to verify if a Collection should `containOnlyNulls`. This matcher returns `true` if the collection is empty. But should it?

Semantically, when you're saying "This list contain only nulls", if the list is empty it doesn't contain anything, and you're saying "All elements of this empty bag are X". Well.. You're not wrong, as the bag has no element to look into anyways.

I think that when trying to assert this kind of thing over empty collections, we should throw an exception. It's not an Assertion Failure, but a bad scenario writing, as it's ambiguous.

Whatever decision we take on this should apply to all Collection matchers (not only nulls), as with all Sequence matchers.

This is important for my work in https://github.com/kotlintest/kotlintest/issues/498.

**Comment by Kerooker** [comment]
This would only be valid for methods that are semantically incorrect.

For example, `list.shouldContainNoNulls()` should pass if the collection is empty, as it contain no nulls, but I don't know what should happen with `list.shouldNotContainNoNulls()` if the collection is empty

**Comment by sksamuel** [comment]
What about adding two new ones which are very clear in their wording ?

**Comment by Kerooker** [comment]
And what to do with the ones that are somewhat ambiguous? Deprecate them?

I'm afraid that way too many things are getting deprecated :P

**Comment by Kerooker** [comment]
Thinking about this again:

I believe there's no need to create a new matcher, and that this is a bug.

Semantically, `containOnlyNulls` and the likes translates to "It contains elements, and all elements are null", and not "It contains elements and all are null OR it is empty"

If the user wants to verify that a collection is empty, they can use `list.shouldBeEmpty()`, and not depend on `containOnlyNulls` for that.

I don't believe any user depends on this kind of behavior for their tests to work, and if they do, their code is probably testing with the wrong assertion.

What do you think, @sksamuel ?

**Comment by Kerooker** [comment]
But particularly, the negative case will be a little hard to describe.

I believe `list.shouldNotContainOnlyNulls()`  should also not pass for an empty collection, for the same reason, but I'm not sure for all the cases

**Comment by Kerooker** [comment]
I said above that depending on the case, an empty collection makes sense, but I believe that if you want an empty collection, you test it using `isEmpty`, not with a collateral of another matcher.

Independently of what we decide, this behavior will be added to the docs

**Comment by sksamuel** [comment]
I would just leave it as it is and document it clearly. I want to improve the matchers anyway.

**Comment by Kerooker** [comment]
I'm working on them for 3.3 - Assertion Improvements. Is there anything you'd like to improve in that way? Or else what I'm doing will soon be legacy again :P

**Comment by sksamuel** [comment]
Haha, would be nice if we could combine the matchers better. But I'm not sure how.
