### ISSUE TITLE
Time limits

### ISSUE THREAD

**Issue by sksamuel** [kotlintest/kotlintest#517]
Just been writing a test for https://github.com/sksamuel/elastic4s/issues/1542 and I needed to assert that a piece of code would time out within a period (and interrupt it). That's useful functionality to have here.

http://doc.scalatest.org/1.8/org/scalatest/concurrent/TimeLimitedTests.html

**Comment by Kerooker** [comment]
Somewhat similar to the timeout configuration, but for a specific piece of code, and not the entire test?

**Comment by sksamuel** [comment]
Kind of the opposite. It passes only if it times out.

**Comment by Kerooker** [comment]
Cool idea

**Comment by ashishkujoy** [comment]
@sksamuel  We already have ```shouldTimeout``` and ```shouldCompleteWithin``` in [concurrent.kt](https://github.com/kotlintest/kotlintest/blob/5de3419ff131e715b74f4fd1ac0a90df6c52cc0e/kotest-assertions/src/jvmMain/kotlin/io/kotest/matchers/concurrent/concurrent.kt)
I think that should be sufficient to achieve that.

**Comment by sksamuel** [comment]
Agreed. Closing.
