### ISSUE TITLE
SkipTestException

### ISSUE THREAD

**Issue by sksamuel** [kotlintest/kotlintest#522]
Should we support skipling a test by thowing this exception like junit.

**Comment by Kerooker** [comment]
Something like `@Expected`?

**Comment by sksamuel** [comment]
I don't know what @expected is.
I just mean inside a test you can throw `SkipTestException` and instead of failing, it acts like the test is ignored.

**Comment by Kerooker** [comment]
Ah, I see...
I've never seen a test with this, but I don't think it will be hard to implement

**Comment by LeoColman** [comment]
Reviving this issue:

Do we actually need this? Would this be useful to any of our users? I don't see this as being really necessary, as it's not very different from a return inside a test, is it?

Tell me if we need this, or if we can close this issue for now.

**Comment by sksamuel** [comment]
I suppose you can just return yeah so close away. Although other test
frameworks have it. Maybe they found a reason for it.

**Comment by sksamuel** [comment]
You can include a reason if you use an exception.

**Comment by LeoColman** [comment]
I mean, it's very easy to implement, I just want to see if we want it. Perhaps it's so easy to implement that we can just do it xD

**Comment by sksamuel** [comment]
Yeah can do, as in the exception you can include a message which is then
displayed as the skip reason in the output.
