### ISSUE TITLE
Retry Helpers

### ISSUE THREAD

**Issue by sksamuel** [kotlintest/kotlintest#523]
Might be handy to have a way to re-run a test once or more, based on some retry strategy.

```
class MyTest : FunSpec({
  test("foo") {
    retry(3) {
      // test here
    }
  }

  test("bar") {
    retry(exponential(16)) {
      // test here
    }
  }
}
```

This would be similar to `eventually`, but is based on a number of retries rather than a period of time.

**Comment by sksamuel** [comment]
Your thoughts @Kerooker

**Comment by Kerooker** [comment]
What would `exponential`  mean? I think this is good

**Comment by sksamuel** [comment]
Means you try again afafter yer 2 seconds then after 4 then 8 and so on.

**Comment by sksamuel** [comment]
https://github.com/jhalterman/failsafe/
