### ISSUE TITLE
See / issue in config 

### ISSUE THREAD

**Issue by sksamuel** [kotlintest/kotlintest#525]
Might be handy to have an option to set "see" and "issue" links, perhaps in the TestConfig ?

**Comment by sksamuel** [comment]
Your thoughts @Kerooker

**Comment by Kerooker** [comment]
Something similar to a `Warn` and `Error`?

**Comment by sksamuel** [comment]
Some reports like allure allow you to link to an issue eg jira. We don't
have a way for users to add these other than the metadata map I added which
i dislike

**Comment by Kerooker** [comment]
Oh, I see.
I actually don't hate the metadata map too much
