### ISSUE TITLE
ExpectedException for AnnotationSpec

### ISSUE THREAD

**Issue by Kerooker** [kotlintest/kotlintest#527]
In the same line of https://github.com/kotlintest/kotlintest/issues/522, JUnit has a parameter in `@Test` called `expected`
This parameter verifies that the test threw an Exception or a subclass of it.

For example:

```
@Test(expected = FooException::class)
fun foo() {
    throw FooException() // Test passes
}

@Test(expected = BarException::class)
fun bar() {
    println("Bar?")  // Test fails, BarException wasn't thrown
}
```

Should we also support it?

**Comment by sksamuel** [comment]
Yes I suppose for AnnotationSpec we should.
