### ISSUE TITLE
Redirect kotlintest.io to Github

### ISSUE THREAD

**Issue by Kerooker** [kotlintest/kotlintest#529]
The domain http://kotlintest.io should be redirected to this github repository

**Comment by sksamuel** [comment]
Done

**Comment by leonampd** [comment]
Hello everyone!
kotlintest.io is down. Should we do something about it? I was wondering yesterday that would be great if we have the docs in github pages organized with good template.

**Comment by sksamuel** [comment]
kotlintest.io is working for me ?

**Comment by LeoColman** [comment]
I think the `https` version isn't working

**Comment by leonampd** [comment]
@Kerooker that's it. I'm using "Https Everywhere" and yes, kotlintest.io with https isn't working.
