### ISSUE TITLE
Provide range-based numeric generators

### ISSUE THREAD

**Issue by breandan** [kotlintest/kotlintest#530]
As [discussed in #214](https://github.com/kotlintest/kotlintest/issues/214#issuecomment-452160769), it would be useful for certain applications to provide a configurable range-based Double generator. Since the default `Double` generator is, [by design](https://github.com/kotlintest/kotlintest/issues/214), unable to compare two `Double` values as a consequence of the [JVM specification](https://stackoverflow.com/questions/8819738/why-does-double-nan-double-nan-return-false/8819776#8819776), it would be nice to have a generator implementation which does not consider such extrema. Furthermore, since this behavior extends to other floating point types [per the IEEE standard](https://ieeexplore.ieee.org/document/30711), it would be nice to circumvent these cases for the purposes of checking other numerical properties.

Further motivation for range-based generators would be to cover the space input values more extensively, for a smaller subset of the input domain.

@Kerooker

**Comment by sksamuel** [comment]
Or Gen.realDoubles with some word for real that means not nan or infinity.

**Comment by Kerooker** [comment]
I think that by definiton, `realDoubles` would be correct, in a strictly mathematical point of view

**Comment by Kerooker** [comment]
Actually... I'm not sure if irrational numbers can be represented

**Comment by Kerooker** [comment]
We actually can.

```
public static final double E = 2.7182818284590452354;
    public static final double PI = 3.14159265358979323846;

```

**Comment by sksamuel** [comment]
Well approximated. Can't represent an irrational exactly.

**Comment by Kerooker** [comment]
You stand correct. Only a subset of real numbers are representable.

I liked `numericDoubles`

**Comment by sksamuel** [comment]
exactDoubles, representableDoubles, numericDoubles
