### ISSUE TITLE
Add documentation for IsolationMode

### ISSUE THREAD

**Issue by Kerooker** [kotlintest/kotlintest#533]

**Comment by Kerooker** [comment]
Currently, the documentation only addresses `isInstancePerTest`
https://github.com/kotlintest/kotlintest/blob/master/doc/reference.md#one-instance-per-test

As it is now deprecated, we should replace the documentation to include the new format and how to use it

**Comment by sksamuel** [comment]
Most of the docs can be lifted from the javadocs I've already added to the isolation modes and the runner implementations. I'll do this issue later tonight.
