### ISSUE TITLE
Verify 3.2.0 release on branch release/3.2.0

### ISSUE THREAD

**Issue by Kerooker** [kotlintest/kotlintest#538]
To continue developing for 3.3.*, let's move 3.2.0 progress to branch release/3.2.0. If there are bugfixes that must happen in the release candidates, they can be on that branch.

Any other change can be made to Master branch.

**Comment by sksamuel** [comment]
I would say lets wait until we release 3.2 proper, then do it.
We might want to make last minute changes. In the meantime, we can prepare PRs and just not merge them yet.

**Comment by Kerooker** [comment]
Ok, i'll leave it to master only hten
