### ISSUE TITLE
Process for testing artefact

### ISSUE THREAD

**Issue by russel** [kotlintest/kotlintest#54]
Is there a nightly build, or are people just compiling from master/HEAD locally? If the former is there a repository that can be used in Gradle builds? If the latter is there a standard policy of where to put the artefact for use with Gradle?

**Comment by mfriedenhagen** [comment]
👍 for something like a CONTRIB.md. Please layout where to branch off for bugfixes or features. A lot of projects just use `master`, it seems this project uses `release` branches.

**Comment by helmbold** [comment]
I tried to write down [how you could contribute and how Git branching is used](https://github.com/kotlintest/kotlintest/wiki/contribute) (or should be used) in this project. Let me know if something is unclear or missing or if you have other ideas. But let's use the [forum](https://groups.google.com/forum/#!topic/kotlintest/-PpdUqC0aw8) for this discussion.
