### ISSUE TITLE
Bump used Kotlin version to 1.0.3

### ISSUE THREAD

**Issue by Hikaru755** [kotlintest/kotlintest#56]
Kotlin is at 1.0.3 by now, while KotlinTest is still using 1.0.1-2, which causes intelliJ to fail the gradle sync because of mismatching dependency version. I don't really want to go back to an earlier Kotlin version for my project and miss out on the faster compiling just to use KotlinTest...

**Comment by sksamuel** [comment]
I've released 1.3.1 which runs on Kotlin 1.0.3.
