### ISSUE TITLE
Request for BehaviorSpec sample

### ISSUE THREAD

**Issue by JustinTullgren** [kotlintest/kotlintest#562]
Hi,

Version: "io.kotlintest:kotlintest-runner-junit5:3.1.11"
Kotlin Version: 1.3.11

I am curious how to use the `And` syntax with a BehaviorSpec.
```kotlin
given("a stateful object") {
  `when`("the stateful object is configured with A") {
      victim.setA("foo");
      and("the statefule object is configured with B") {
        victim.setB("bar");
         then("it should print hello") {
          victim.print() shouldBe "hello"
        }
      }
    }
}
```

When trying to do this the receiver context can't be determined:
`Unit can't be called in this context by implicit receiver. Use explicit context if necessary`.

Adding the context `this@given.and` does not resolve the issue and the test context is never executed.

I couldn't find a concrete example.

Thanks!

**Comment by sksamuel** [comment]
And can only be used at the given scope.
We should probably allow it inside the when scope too.
@Kerooker an easy one ?

**Comment by Kerooker** [comment]
The problem to do it in the `When` scope is when will it stop? We were discussing this earlier today hahah

```
Given("A") {
    And("B") {
        And("C") {
            And("D") {
                When("E"){
                    And("F"){
                        And("G"){

                         }
                    }
                }
           }
        }
    }
}

```

But maybe this is users' choice?

**Comment by sksamuel** [comment]
If you want to go crazy why not.
No difference to using free spec and nesting 200 times.

**Comment by LeoColman** [comment]
@JustinTullgren 
Please take a look at #593 and see if it suits you correctly.

**Comment by JustinTullgren** [comment]
@Kerooker fast turnaround! That works just fine thanks!

**Comment by LeoColman** [comment]
It might get released soonish.
We will just fix a bug in another part of the framework and this might go along with it
