### ISSUE TITLE
New style like "fun spec", but with "should"

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#6]
I've pretty good experience writing unit test methods starting with `should`. This simple words leads to much better names compared to `test`. Therefore I suggest, to support another style like fun spec, but using the word `should`. Example:

    should("remove the last element from stack") {
      val stack = ListStack<String>()
      stack.push("hello")
      stack.push("world")
      stack.size() shouldBe 2

      val element = stack.pop() 

      element shouldBe "world"
      stack.size() shouldBe 1
    }

Compared to the existing style with `test` it is even more concise, since it is already known what object is tested in a certain unit test class.  

    should("remove the last element from stack")
    test("ListStack.pop should remove the last element from stack")

**Comment by sksamuel** [comment]
I like it, what do you suggest this *Spec should be called

**Comment by helmbold** [comment]
It is hard to find a good name. On the other hand, if I read "fun spec", I have no idea, how the code could look like. So maybe it is enough if the name is useful for developers already knowing the different styles. 

Here are my suggestions:

* should spec
* should fun spec
* fun should spec
* should simple spec
* simple should spec

I prefer "should spec" since it describes pretty good what is typical for this style: the word "should". Whether it is a variant of "fun spec" is not that important. Since I find this kind of spec most simple, the word "simple" could be used.

**Comment by sksamuel** [comment]
I think ShouldSpec is fine.

**Comment by helmbold** [comment]
Fine! I'm looking forward to the new style. Thanks for your effort.

**Comment by sksamuel** [comment]
This changes allows

should("some test") { }

and

"some text" {
   should("some test") { }
}

**Comment by sksamuel** [comment]
@helmbold did you try this out of interest?

**Comment by helmbold** [comment]
... sorry, not yet. My job is still Java dominated ... However I'm planning to use it in the near future.

**Comment by sksamuel** [comment]
booo to java :)
