### ISSUE TITLE
Logical operators (and or) for matchers

### ISSUE THREAD

**Issue by sksamuel** [kotlintest/kotlintest#60]

**Comment by sksamuel** [comment]
You mean how do I think it should look like ?

**Comment by helmbold** [comment]
Oh sorry, I've written it with a smartphone... Yes, that is what I meant.

**Comment by sksamuel** [comment]
I was thinking something like

`x shouldBe (between(1,10) and even)`

**Comment by sksamuel** [comment]
Check out the commit I just made on release/2.0. If you're happy with it I'll add it to the readme. If not I'll make changes.

**Comment by helmbold** [comment]
I like it, but I wonder whether the same could be achieved with plain Kotlin. If we would use just `&&` and `||` we would get an exception, too. Or do I miss something?

**Comment by sksamuel** [comment]
And would work. Or wouldn't.

**Comment by helmbold** [comment]
You're right! And only having `or` without `and` would be a bit funny.

**Comment by sksamuel** [comment]
And we can do cleverer things like wrap up all the errors if we wanted and show you which ones failed.

**Comment by sksamuel** [comment]
I'll close this then if you're happy with what we have for now.
