### ISSUE TITLE
Provide a way to run a single test in isolation

### ISSUE THREAD

**Issue by Hikaru755** [kotlintest/kotlintest#63]
It would be nice to have a way to do the opposite of the "ignore" option in the test config so that only one test is run and all others are temporarily disabled.

**Comment by sksamuel** [comment]
What happens if you have two tests tagged in such way ?

**Comment by helmbold** [comment]
I think that this is the job of an IDE plug-in or Gradle/Maven plug-in.

**Comment by sksamuel** [comment]
Agreed. But at the moment there's no way for them to do that in KotlinTest.
They need a way to interact with the test runner.

**Comment by Hikaru755** [comment]
If two tests are tagged that way I would expect them to run both, but no other test. I'm somehow thinking in audio editing terms here, where you can usually "mute" or "solo" a track. If you solo two tracks, both will play but no other. If you're familiar with [Spek](https://jetbrains.github.io/spek/), they are calling this feature "focus". You can activate it by prefixing any testing method with an f, in their syntax it looks like this:
```
it("should do something") {
   // test/assertion goes here
}
```
which can be focussed on to only run that specific test:
```
fit("should do something") {
   // assertion goes here
}
```
Now all other tests will be ignored, and only tests that are prefixed will be run.
Their ignore features works similarly, just with an x instead of an f.

**Comment by sksamuel** [comment]
Ok I see. Sounds like you could add a tag called solo and just run that
tag. We could add a short hand for it.

**Comment by Hikaru755** [comment]
@sksamuel Either like that, or maybe just another parameter to the config method?
```
test("my test") {
  // test code
}.config(focused = true)
```
I feel like this would be more in line with the already existing option for ignoring tests. Oh that's another thing to think about, what should happen when someone sets both focused and ignored to true? Which one should override which? Or should it just throw an error in that case?

**Comment by sksamuel** [comment]
BTW since the way it works with junit is you are fed one test class at a time, we can only focus tests inside a given classfile.

**Comment by helmbold** [comment]
I'm still  not sure if this feature should be added, but if so, we see should use the existing config method. The parameter could be called `focused` or `selected`.

**Comment by sksamuel** [comment]
I like focused but happy to use whatever.

**Comment by helmbold** [comment]
We already have the solution! Just use a tag:
```kotlin
"should do the right thing" {
    ...
}.config(tag = "focus")
```
This should be fine until an IDE/Maven/Gradle plug-in offers the desired functionality.

**Comment by Hikaru755** [comment]
@helmbold That won't work as wanted in this case, as it says in the docs:

> Any test that has no tags is always run.

And I actually am not using tags, so adding the focus tag just for this won't achieve anything.

**Comment by helmbold** [comment]
I have to look at the code but it shouldn't be the case that all tests without tags are always executed. And if the behavior would be changed (if it is not already like I would expect) you could do it with tags.

**Comment by sksamuel** [comment]
I think non tagged tests are always run.

**Comment by helmbold** [comment]
On, then we should change the behavior. Maybe we could introduce a flag to allow the current behavior.

**Comment by sksamuel** [comment]
I think we can change it in 2.0

**Comment by helmbold** [comment]
I've created an issue for it #67 .
