### ISSUE TITLE
run only tagged tests

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#67]
At the moment all tests without tags are always executed, even if a certain tag is selected. This makes tagging generally less useful as you can not run only a certain group of tests (e. g. smoke tests). 

Only the tests of the given group(s) should be executed. It should be possible to run all non-tagged tests with a certain flag ("non-tagged"?).

**Comment by helmbold** [comment]
Instead of inventing a special case for non-tagged tests, we could have two properties `includeTags` and `excludeTags`.

- If only `includeTags` is given, only the tests with the given tags are executed. 
- If only `excludeTags` is given, all tests but tests with the given tags are executed. 
- If `includeTags` and `excludeTags` are given, only tests tagged with the tags listed in `includeTags` but not tagged with a tag from `excludeTags` is executed. 

This is, by the way, the same behaviour as in [TestNG](http://testng.org/doc/documentation-main.html#exclusions).

What do you think?

**Comment by sksamuel** [comment]
This sounds good.

**Comment by helmbold** [comment]
I've left two TODO's in the code, because the `System.getProperty` call should be mocked, because it interferes with other tests. However, I wasn't able to mock a static method with PowerMock, jmock, and jmockit.

**Comment by helmbold** [comment]
Done.
