### ISSUE TITLE
Create a KotlinTest forum

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#69]
The discussions happens mostly in comments to issues, but there are some topics that are not related to issues, like general discussion about future development, coding conventions, or questions about usage. Maybe we should create a forum like a Google group.

For example I've just created the first wiki page about [How to Contribute](https://github.com/kotlintest/kotlintest/wiki/contribute) and there is no good place to discuss it at the moment.

What do you think?

**Comment by sksamuel** [comment]
Slack #kotlintest already exists. Or gitter.

**Comment by la10736** [comment]
What is the slack address? Is it open?

2016-07-08 8:54 GMT+02:00 Stephen Samuel <notifications@github.com>:

**Comment by la10736** [comment]
Nevermind... I found and joined it

**Comment by helmbold** [comment]
OK.  We should mention it on the wiki.

**Comment by helmbold** [comment]
However I like classical forums better since slack is a unstructured chat. Previous questions (e. g. how to use the framework in a certain case) are not googleable in slack and even if you'd be able to find one the answers are unstructured and possibly mixed with other topics.

**Comment by russel** [comment]
From what I can tell Slack and Gitter are IRC systems with no email. My workflow is focused entirely on my Inbox, so if people want my input on anything that doesn't have an email prompt associated with it, please let me know and I will endeavour to find out how to access Slack and Gitter.

**Comment by reckter** [comment]
I couldn't find the slack link, can somebody point me to it?

**Comment by sksamuel** [comment]
https://kotlinlang.slack.com/messages/kotlintest/

**Comment by reckter** [comment]
Ok Well I don't have a @Jetbrains.com account sadly :/

**Comment by sksamuel** [comment]
You just need to request a slack login.

**Comment by helmbold** [comment]
Join the new [KotlinTest Forum](https://groups.google.com/forum/#!forum/kotlintest)!
