### ISSUE TITLE
Replace string tags with object tags

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#71]
Tags are simple strings, what is a mild form of [stringly typing](http://c2.com/cgi/wiki?StringlyTyped). [ScalaTests uses objects](http://www.scalatest.org/user_guide/tagging_your_tests) instead. 

I suggest to introduce a base class for tags and allow only instances of this class to be used as tags.  

```kotlin
// base class of all tags
abstract class Tag(repr: String? = null) {
  val repr: String = repr ?: javaClass.simpleName
  override fun toString = repr
}

// definition of a concrete tag
object Smoke : Tag("smoke")

// usage
"should have a tag" {
    ...
}.config(tag = Smoke)
```

The string representation is needed to select a tag with command line arguments.

Any opinions?

**Comment by sksamuel** [comment]
Sometimes I agree with the stringly typed argument (where you want say an enum or where you want to enforce some criteria on the string value) but other times you are just inventing types for no reason. In this case, what do we gain from having the type?

**Comment by helmbold** [comment]
The type system would help to prevent typos here. If a tag is misspelled it is unlikely that you'd ever notice that a certain test doesn't run.

**Comment by sksamuel** [comment]
That's a good point.

**Comment by helmbold** [comment]
I've replaced the occurrences of string tags with the new tag class, but I get strange errors, when I try to run  the tests.
![tagclass](https://cloud.githubusercontent.com/assets/5079980/16817955/9075b492-4945-11e6-8860-b7449025006d.png)

I cannot find something suspicious in the code. Could you please have a look, @sksamuel ? I've create the branch feature/#71_tag_class to avoid breaking the work on 2.0.

**Comment by helmbold** [comment]
The mentioned problem was a problem with the direct call of `System.setProperty`, what conflicted with other tests. We would need proper mocking of static methods (with JMockit), to avoid it. For now I've set the two problematic tests to "ignored". They can be run in isolation.

**Comment by sksamuel** [comment]
If you set it back after the test it should work fine?

**Comment by helmbold** [comment]
At the moment class `Tag` looks like this:

```kotlin
abstract class Tag(name: String? = null) {
  val name: String = name ?: javaClass.simpleName
  override fun toString() = name
}
```

But I wonder, whether we should allow to set custom names. There is no reason to type another name when running the tests (includeTags, excludeTags). The only possible case, that comes to mind would be a name clash,  but then it would be better to use a different tag object name.

What do you think?

**Comment by sksamuel** [comment]
I'd say don't make it anymore complicated. Why not even derive the name
from the simple class name ?

`object MyTag extends Tag`

**Comment by helmbold** [comment]
Done.

**Comment by sksamuel** [comment]
What was your final decision

**Comment by helmbold** [comment]
My final decision was to go with the simple name of the singleton objects:

```
object MyTag : Tag()
```

That's simple and without surprises. In a large code base you don't have to look up the actual tag name, but you can just use the singleton name.

**Comment by sksamuel** [comment]
I think this is the best way.
