### ISSUE TITLE
before/after Each does not run around `each` invocation of a test

### ISSUE THREAD

**Issue by hoangtranwork** [kotlintest/kotlintest#73]
Demonstration code: https://gist.github.com/hoangtranwork/8166d7c7d1202d3113ddb835f82f014e

If I understand correctly, if we set `invocation = x (x > 0)` as well as overriding the `beforeEach/afterEach` hook, then those hooks should run around `each` invocation (of the same test), but as I tested with the code above, it doesn't.

So is this a bug or do I misunderstand the feature?

**Comment by hoangtranwork** [comment]
probably a mistake here: https://github.com/kotlintest/kotlintest/blob/master/src/main/kotlin/io/kotlintest/TestBase.kt#L87

it should call beforeEach(), instead of afterEach()

**Comment by hoangtranwork** [comment]
well, and after looking at the `runTest()` function I can see that invocation configuration is used there, which completely inside the beforeEach/afterEach circle.

So it left the question: is this by design or a bug?

**Comment by sksamuel** [comment]
Your PR fixes that.

**Comment by helmbold** [comment]
@sksamuel Do you release 1.3.3 with this fix? I've made the same fix in release/2.0.

**Comment by sksamuel** [comment]
Not yet, but I will.

**Comment by sksamuel** [comment]
Fixed in 1.3.3. Helmbold has made same fix in 2.0
