### ISSUE TITLE
Allow overriding single value of `config`

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#75]
It is possible to set a custom `defaultTestCaseConfig` per class. All the values from this config instance are overridden, if a test case is has it's own config:

```kotlin
class MyTest: StringSpec() {
  override val defaultTestCaseConfig = config(ignored = true)
  init {
    "should be ignored" { ... }.config(tag = "x")
  }
}
```

The test case will be executed, because the local test case config will override the complete defaultTestCaseConfig. It would be more intuitive and more useful to override only per property. In this case the resulting config should be equal to `config(ignored = true, tag = "x")` on the test case.

**Comment by helmbold** [comment]
I fear that it is not that easy to allow the suggested of overriding config values. I see no possibility to distinguish an explicitly set value and a default value. Let's say the default config for the test class sets `invocations` to 3, but a certain test should only run once. Then the config for this test would be `config(invocations = 1)`, but that is also the default value.

The only idea, that comes to mind, is using builder style methods:

```
"should use config" {
  ...
}.invocations(2).threads(5).ignored
```

But I think that a method with all parameters with default values is more idiomatic. 

Or maybe there is a reflection hack to find out, what parameters are actually passed and what are just default values, but I'm not aware of such a possibility.

**Comment by sksamuel** [comment]
A solution is to have a default value placeholder, such as -1, which is then overridden at the use site.

**Comment by helmbold** [comment]
But what about boolean? There is no good value that could be interpreted as "value bit set".

**Comment by sksamuel** [comment]
Could be null?

**Comment by helmbold** [comment]
Yes, maybe that's the best solution. I'll implement it next week.

**Comment by helmbold** [comment]
Implemented with nullable now.
