### ISSUE TITLE
IntelliJ IDEA 2016.2: 0 test classes found in package

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#76]
If I try to run the tests in IntelliJ IDEA 2016.2 by clicking on the test/kotlin folder, I get: 

> 0 test classes found in package '<default package>'

If I select a certain test class, I get:

> Exception in thread "main" java.lang.NoSuchMethodError: io.kotlintest.TestBase.getDescription$kotlintest_compileKotlin()Lorg/junit/runner/Description;
>     at io.kotlintest.KTestJUnitRunner.getDescription(KTestJUnitRunner.kt:11)
>     at com.intellij.junit4.JUnit4IdeaTestRunner.getDescription(JUnit4IdeaTestRunner.java:121)
>     at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:97)
>     at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
>     at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:253)
>     at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:497)
>     at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

If I run the Gradle task "test" all tests are executed as expected. Maybe this is an IntelliJ IDEA bug.

**Comment by sksamuel** [comment]
I sometimes get something similar if I compile in gradle and then try to run in intellij.

**Comment by helmbold** [comment]
The behavior is the same if I compile with IntelliJ.

**Comment by helmbold** [comment]
IntelliJ 2016.2 seems to be a shitty release! For example the class TestCaseTest is not displayed and it is not possible, to use "scroll from source" with this class. However, it is possible to open this class directly via its name.

**Comment by helmbold** [comment]
The error still exists with Intellij 2016.2.4.

**Comment by helmbold** [comment]
The first part, "0 test classes found in package '', is fixed with #39. The second point seems to be fixed as well.
