### ISSUE TITLE
make FlatSpec config regular

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#78]
All specification style with the exception of FlatSpec have the `config` after the test block:

```
"FlatSpec".config(invocations = 3) should "support config syntax" {
 }
```

It should be 

```
"FlatSpec" should "support config syntax" {
 }.config(invocations = 3)
```

**Comment by sksamuel** [comment]
I couldn't get it to parse.

**Comment by helmbold** [comment]
I'll try it. And in the worst case it would remain as is ;-)

**Comment by helmbold** [comment]
FlatSpec is removed now.
