### ISSUE TITLE
Fake data generation

### ISSUE THREAD

**Issue by hastebrot** [kotlintest/kotlintest#82]
Consider the integration of one of the Java fake data generator libraries (based on Perl's `Data::Faker` library). For instance: https://github.com/DiUS/java-faker.

I wonder if the faker concept workes conceptionally with kotlintest's property testing (`Gen` and `forAll()`).

**Comment by hastebrot** [comment]
And of course, fake data could also be used for table-based testing.

**Comment by sksamuel** [comment]
We could provide generators that use the fake data. Eg a "last name generator".

**Comment by sksamuel** [comment]
I've found this project which seems to do what is requested. https://github.com/DiUS/java-faker
