### ISSUE TITLE
Investigate how to run a single test in IntelliJ

### ISSUE THREAD

**Issue by sksamuel** [kotlintest/kotlintest#86]
Intellij has support for scala test and testng, so you can run a single test.

**Comment by manhhavu** [comment]
It seems that last time I checked, I was able to run a single **Kotlintest** (1.3.5) in **IntelliJ** (2016.3) without any issue.

**Comment by helmbold** [comment]
I can run a single spec in IntelliJ (2016.3.2) but not a single test case with KotlinTest 2.0.

**Comment by sksamuel** [comment]
This would need https://github.com/kotlintest/kotlintest/issues/184 so closing this one, we can track whether this happens in https://github.com/kotlintest/kotlintest/issues/184
