### ISSUE TITLE
forAll and forNone examples in README use Scala syntax

### ISSUE THREAD

**Issue by yole** [kotlintest/kotlintest#88]

**Comment by yole** [comment]
Also the last example in "Exceptions" section

**Comment by sksamuel** [comment]
They are actually methods provided by KotlinTest in the interface called Inspectors. They're used to iterate over collections and assert that the block applies to all / none of the elements in the iteration. Maybe the method names are a bit more idomatic Scala than idomatic Kotlin.

**Comment by yole** [comment]
Method names are fine, but I'm pretty sure that Kotlin doesn't support using `=>` in a lambda. :)

**Comment by sksamuel** [comment]
Oops

**Comment by sksamuel** [comment]
I've fixed it now. That was quicker than Kotlin changing the lamba symbol :)

**Comment by helmbold** [comment]
By the way, I like `->` better than `=>` ;-)

**Comment by sksamuel** [comment]
I don't, I think its because I've been doing Scala for 5 years :)
