### ISSUE TITLE
shouldThrow should be able to accept a function that returns a nullable reference

### ISSUE THREAD

**Issue by MichaelRocks** [kotlintest/kotlintest#90]
Consider the following example:

```
fun toTest(string: String?): String? {
  return string?.substring(1)
}
```

The function above cannot be tested with `shouldThrow()` because it returns a nullable `String`.
```
shouldThrow<IndexOutOfBoundsException> { toTest("") }
// Type mismatch. Required: Any. Found: String?.
```

The compilation error can be fixed with `!!` but I think it would be better if kotlintest allowed such expressions.

**Comment by helmbold** [comment]
Why is this marked with milestone 1.2? Current is 1.3.

**Comment by sksamuel** [comment]
updated
