### ISSUE TITLE
Test conditions

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#91]
Let's say you have tests that should run only on Linux or only if a certain JDBC driver is used (e. g. h2 instead of Oracle). To include or exclude such tests we could use tags. But someone needs to decide what tags should be executed and there is at the moment no mechanism in KotlinTest to do so. 

What do you think of

* adding something to decide what tags should be use to the global config suggested in #77, or 
* adding conditions to the config object

?

The latter could like this:

```kotlin
// example condition
val linux: () -> Boolean = { SystemUtils.IS_OS_LINUX }


"should run on linux only" {
  ...
}.config(conditions = listOf(linux))
```

What do you think?

**Comment by sksamuel** [comment]
So you're talking about tags that are really evaluations ?

**Comment by helmbold** [comment]
My first idea with tags was, maybe a bit confused. I think we shouldn't mix conditions and tags. Tags should be simple and completely user driven. Conditions could be a useful addition. In theory both concepts could be unified, since a tag could be seen as a condition that is true, if a given tag equals a tag on a test. But I see it as two different things.

It would be enough to allow a single condition, since the use can combine more conditions himself.

```kotlin
"should run on linux only" {
  ...
}.config(condition = linux && postgresql, tags = DB)
```

**Comment by sksamuel** [comment]
I like it, and we should include some built in conditions out of the box.

**Comment by helmbold** [comment]
Should we mark tests with unmet conditions as ignored or should we remove them from the list of executed tests?

**Comment by sksamuel** [comment]
Hmm not sure really. Make it an option ?

**Comment by reckter** [comment]
I would mark them as ignored, just because then the user actually sees them and he has to think about why it didn't run. If you just exclude them all they will see is: "oh I passed every test" without realising that maybe the relevant test wasn't even run

**Comment by sksamuel** [comment]
What @reckter says makes sense.

**Comment by helmbold** [comment]
I agree, let's mark them as ignored.

**Comment by helmbold** [comment]
@sksamuel (or everyone else) What standard conditions should we include?

**Comment by sksamuel** [comment]
Linux windows mac.

Single core multi core

**Comment by helmbold** [comment]
While implementing this feature, I came to the conclusion that, in effect, it is the same as the `config` paremter `ignored`. Whether you pass a lambda expression and let the test framework evaluate it or perform the evaluation within the spec doesn't matter.

As suggested in this issue, it would look like this:

```kotlin
val isLinux: () -> Boolean = { true } // simplified

"some test" {
  ...
}.config(condition = isLinux)
```

The same with the existing `ignored` flag would like this:
```kotlin
"some test" {
  ...
}.config(ignored= !isLinux())
```

However `ignored` sounds a bit inappropriate for this usage. I suggest (for the second time, but this time with a solid reason) to **rename `ignored` to `enabled`** (and invert the logic, of course). And we could provide some "conditions" which can be used with `enabled`. This would look like this:

```kotlin
"some test" {
  ...
}.config(enabled= isLinux()) // could also be property syntax: isLinux
```

In any case, I think it is not worth to have two boolean flags (`ignored`, `condition`) that could mark a test as ignored. 

What do you think?

**Comment by sksamuel** [comment]
I think it makes sense.

**Comment by helmbold** [comment]
Ok, I've renamed it and added some documentation to guide users to do more with it than just setting `enabled` to `true´ or `false`.

I've added an example with limiting a test cases to Linux and added a link to Apache Commons Lang, which contains some static fields to detect the OS. I prefer to (optionally) reuse Apache Commons instead of duplicating this part of it. Is this ok?

For the number of of core, I think it is pretty specific. I never had the desire to limit the execution of a test case by the number of available cores. And if someone want to do it, it is not that hard to write one line to do it:

```kotlin
val cores = Runtime.getRuntime().availableProcessors()

"should run" {
  ...
}.config(enabled = cores > 4)
```

**Comment by sksamuel** [comment]
As a mostly scala developer I'm used to doing `Properties.isWin` etc :)

I don't know what other conditions we can add out of the box.

**Comment by helmbold** [comment]
So, you propose that we should provider our own version?

**Comment by sksamuel** [comment]
If it's just a couple of lines then its better than a dependency.

**Comment by helmbold** [comment]
Implementing something like `isLinux` wouldn't be too hard, but I see no real benefit to reinvent it. Apache Commons `SystemUtils` are pretty comprehensive and include other potentially useful properties like JAVA_RUNTIME_VERSION, JAVA_VERSION, OS_NAME, OS_VERSION, USER_LANGUAGE, IS_JAVA_1_7, IS_JAVA_1_8, IS_OS_AIX. IS_OS_HP_UX, IS_OS_LINUX, IS_OS_MAC, IS_OS_FREE_BSD ...

I suggest that we refer the user to Apache Commons `SystemUtils` and that we don't include this dependency by default.

**Comment by sksamuel** [comment]
Ok agreed.

**Comment by helmbold** [comment]
Ok, then everything is done here.
