### ISSUE TITLE
Rename TestConfig to TestCaseConfig

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#97]
If we agree that we want to call a test case "TestCase" in the code (and documentation), we should call it so consistently. Different names for the same thing are confusing. `TestConfig` should be Rename to `TestCaseConfig`.

See: https://groups.google.com/forum/#!topic/kotlintest/NCH_jABYrEA

**Comment by sksamuel** [comment]
Agreed

**Comment by helmbold** [comment]
Duplicate of 103.
