### ISSUE TITLE
Replace "ignored" with "enabled"

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest#98]
A test is disabled with `config(ignored = true)` at the moment. This word resembles the annotation from JUnit 4 and (the somewhat awkward) ignore syntax from ScalaTest. JUnit 5 switches to "disabled", while TestNG uses "enabled". If you look at APIs in general "enabled" is pretty common. "ignore" would make more sence, if it were a method. But if we don't focus on the action (ignoring) but on the value (enabled or not), we could use the more common word for this status.

I suggest that we replace "ignored" with "enabled". Any objections?

**Comment by sksamuel** [comment]
I think in this case, you could argue for either, so its changing it just based on someone's preference.

**Comment by helmbold** [comment]
I think you're right, it is a matter of taste and not worth the change.
